/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.newline53.sdk.models.components.Security;
import com.newline53.sdk.models.operations.CreateCustomerAddressRequest;
import com.newline53.sdk.models.operations.CreateCustomerDetailsRequest;
import com.newline53.sdk.models.operations.CreateCustomerRequest;
import com.newline53.sdk.models.operations.CreateCustomerResponse;
import com.newline53.sdk.models.operations.CustomerTypeRequest;
import com.newline53.sdk.models.operations.DeleteCustomerRequestBody;
import com.newline53.sdk.models.operations.DeleteCustomerResponse;
import com.newline53.sdk.models.operations.GetCustomerResponse;
import com.newline53.sdk.models.operations.ListCustomersRequest;
import com.newline53.sdk.models.operations.ListCustomersResponse;
import com.newline53.sdk.models.operations.QueryParamCustomerType;
import com.newline53.sdk.models.operations.UpdateCustomerAddressRequest;
import com.newline53.sdk.models.operations.UpdateCustomerDetailsRequest;
import com.newline53.sdk.models.operations.UpdateCustomerRequestBody;
import com.newline53.sdk.models.operations.UpdateCustomerResponse;
import com.newline53.sdk.utils.Utils;
import java.lang.Exception;
import java.time.LocalDate;
import org.junit.jupiter.api.Test;

public class CustomersTests {

    @Test
    public void testCustomers_ListCustomersCustomerList() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("listCustomers-customer_list");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        ListCustomersRequest req = ListCustomersRequest.builder()
                .uid("uKxmLxUEiSj5h4M3")
                .includeInitiated(true)
                .customerType(QueryParamCustomerType.PRIMARY)
                .firstName("Olive")
                .lastName("Oyl")
                .email("olive.oyl@popeyes.com")
                .locked(false)
                .programUid("pQtTCSXz57fuefzp")
                .businessName("Business inc")
                .externalUid("client-generated-id")
                .poolUid("wTSMX1GubP21ev2h")
                .build();

        ListCustomersResponse res = sdk.customers().list()
                .request(req)
                .call();
        assertEquals(200, res.statusCode());
    }

    @Test
    public void testCustomers_CreateCustomerPrimary() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("createCustomer-primary");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        CreateCustomerRequest req = CreateCustomerRequest.builder()
                .externalUid("client-generated-42")
                .email("tomas@example.com")
                .build();

        CreateCustomerResponse res = sdk.customers().create()
                .request(req)
                .call();
        assertEquals(201, res.statusCode());
    }

    @Test
    public void testCustomers_CreateCustomerSecondary() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("createCustomer-secondary");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        CreateCustomerRequest req = CreateCustomerRequest.builder()
                .customerType(CustomerTypeRequest.SECONDARY)
                .primaryCustomerUid("dc6PApa2nn9K3jwL")
                .externalUid("client-generated-42")
                .email("tomas@example.com")
                .build();

        CreateCustomerResponse res = sdk.customers().create()
                .request(req)
                .call();
        assertEquals(201, res.statusCode());
    }

    @Test
    public void testCustomers_CreateCustomerPrimaryEmpty() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("createCustomer-primary-empty");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        CreateCustomerRequest req = CreateCustomerRequest.builder()
                .build();

        CreateCustomerResponse res = sdk.customers().create()
                .request(req)
                .call();
        assertEquals(201, res.statusCode());
    }

    @Test
    public void testCustomers_CreateCustomerEmptyCustomer() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("createCustomer-empty_customer");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        CreateCustomerRequest req = CreateCustomerRequest.builder()
                .externalUid("partner-generated-id")
                .email("olive.oyl@newline53.com")
                .details(CreateCustomerDetailsRequest.builder()
                    .firstName("Olive")
                    .middleName("Olivia")
                    .lastName("Oyl")
                    .suffix("Jr.")
                    .phone("5555551212")
                    .businessName("Oliver's Olive Emporium")
                    .ssn("111-22-3333")
                    .dob(LocalDate.parse("1919-12-08"))
                    .address(CreateCustomerAddressRequest.builder()
                        .street1("123 Abc St.")
                        .city("Chicago")
                        .state("IL")
                        .postalCode("60301")
                        .street2("Suite 4A")
                        .build())
                    .build())
                .build();

        CreateCustomerResponse res = sdk.customers().create()
                .request(req)
                .call();
        assertEquals(201, res.statusCode());
    }

    @Test
    public void testCustomers_GetCustomer() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("getCustomer");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        GetCustomerResponse res = sdk.customers().get()
                .uid("<id>")
                .call();
        assertEquals(200, res.statusCode());
    }

    @Test
    public void testCustomers_UpdateCustomer() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("updateCustomer");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        UpdateCustomerResponse res = sdk.customers().update()
                .uid("<id>")
                .body(UpdateCustomerRequestBody.builder()
                    .externalUid("partner-generated-id")
                    .email("olive.oyl@newline53.com")
                    .details(UpdateCustomerDetailsRequest.builder()
                        .firstName("Olive")
                        .middleName("Olivia")
                        .lastName("Oyl")
                        .suffix("Jr.")
                        .phone("5555551212")
                        .businessName("Oliver's Olive Emporium")
                        .ssn("111-22-3333")
                        .dob(LocalDate.parse("1919-12-08"))
                        .address(UpdateCustomerAddressRequest.builder()
                            .street1("123 Abc St.")
                            .city("Chicago")
                            .state("IL")
                            .postalCode("60301")
                            .street2("Suite 4A")
                            .build())
                        .build())
                    .build())
                .call();
        assertEquals(200, res.statusCode());
    }

    @Test
    public void testCustomers_DeleteCustomer() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("deleteCustomer");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        DeleteCustomerResponse res = sdk.customers().delete()
                .uid("<id>")
                .body(DeleteCustomerRequestBody.builder()
                    .archiveNote("for inactivity")
                    .destinationSyntheticAccountUid("oBASVwLQB4RojU5X")
                    .build())
                .call();
        assertEquals(200, res.statusCode());
    }
}