/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.newline53.sdk.models.components.Security;
import com.newline53.sdk.models.operations.GetCustodialAccountClosingBalanceResponse;
import com.newline53.sdk.models.operations.GetCustodialAccountResponse;
import com.newline53.sdk.models.operations.ListCustodialAccountClosingBalancesRequest;
import com.newline53.sdk.models.operations.ListCustodialAccountClosingBalancesResponse;
import com.newline53.sdk.models.operations.ListCustodialAccountsQueryParamType;
import com.newline53.sdk.models.operations.ListCustodialAccountsRequest;
import com.newline53.sdk.models.operations.ListCustodialAccountsResponse;
import com.newline53.sdk.utils.Utils;
import java.lang.Exception;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Test;

public class CustodialaccountsTests {

    @Test
    public void testCustodialaccounts_ListCustodialAccounts() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("listCustodialAccounts");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        ListCustodialAccountsRequest req = ListCustodialAccountsRequest.builder()
                .customerUid("uKxmLxUEiSj5h4M3")
                .externalUid("client-generated-id")
                .type(ListCustodialAccountsQueryParamType.DDA)
                .build();

        ListCustodialAccountsResponse res = sdk.custodialAccounts().list()
                .request(req)
                .call();
        assertEquals(200, res.statusCode());
    }

    @Test
    public void testCustodialaccounts_GetCustodialAccount() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("getCustodialAccount");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        GetCustodialAccountResponse res = sdk.custodialAccounts().get()
                .uid("<id>")
                .call();
        assertEquals(200, res.statusCode());
    }

    @Test
    public void testCustodialaccounts_ListCustodialAccountClosingBalances() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("listCustodialAccountClosingBalances");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        ListCustodialAccountClosingBalancesRequest req = ListCustodialAccountClosingBalancesRequest.builder()
                .custodialAccountUid("yqyYk5b1xgXFFrXs")
                .custodialAccountExternalUid("4XkJnsfHsuqrxmeX")
                .netUsdClosingBalanceAsOf(OffsetDateTime.parse("2020-01-01T00:00:00Z"))
                .netUsdClosingBalanceBefore(OffsetDateTime.parse("2020-01-01T00:00:00Z"))
                .netUsdClosingBalanceAfter(OffsetDateTime.parse("2020-01-01T00:00:00Z"))
                .build();

        ListCustodialAccountClosingBalancesResponse res = sdk.custodialAccounts().listClosingBalances()
                .request(req)
                .call();
        assertEquals(200, res.statusCode());
    }

    @Test
    public void testCustodialaccounts_GetCustodialAccountClosingBalance() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("getCustodialAccountClosingBalance");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        GetCustodialAccountClosingBalanceResponse res = sdk.custodialAccounts().getClosingBalance()
                .uid("<id>")
                .call();
        assertEquals(200, res.statusCode());
    }
}