/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.newline53.sdk.models.components.Security;
import com.newline53.sdk.models.operations.GetSyntheticAccountClosingBalanceResponse;
import com.newline53.sdk.utils.Utils;
import java.lang.Exception;
import org.junit.jupiter.api.Test;

public class SyntheticaccountclosingbalancesTests {

    @Test
    public void testSyntheticaccountclosingbalances_GetSyntheticAccountClosingBalance() throws Exception {

        var testHttpClient = Utils.createTestHTTPClient("getSyntheticAccountClosingBalance");
        NewlineSDK sdk = NewlineSDK.builder()
                .serverURL(Utils.environmentVariable("TEST_SERVER_URL", "http://localhost:18080"))
                .security(Security.builder()
                    .programUid("NEWLINE_PROGRAM_UID")
                    .hmacKey("NEWLINE_HMAC_KEY")
                    .build())
                .client(testHttpClient)
            .build();

        GetSyntheticAccountClosingBalanceResponse res = sdk.syntheticAccountClosingBalances().get()
                .uid("<id>")
                .call();
        assertEquals(200, res.statusCode());
    }
}