/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuthorizationStatusRequest
 * 
 * <p>The current status of the transaction authorization.
 */
public enum AuthorizationStatusRequest {
    CLIENT_APPROVED("client_approved"),
    CLIENT_DENIED("client_denied");

    @JsonValue
    private final String value;

    AuthorizationStatusRequest(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuthorizationStatusRequest> fromValue(String value) {
        for (AuthorizationStatusRequest o: AuthorizationStatusRequest.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

