/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class CreateSyntheticAccountInstantPaymentResponse {
    /**
     * Address of the business or individual who owns the external account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_address")
    private CreateSyntheticAccountInstantPaymentCounterpartyAddressResponse counterpartyAddress;

    /**
     * Name of the business or individual who owns the counterparty Account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_name")
    private String counterpartyName;

    /**
     * Email address of the counterparty
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    private JsonNullable<String> email;

    /**
     * Exactly 10 digits long (no hyphens, parentheses, or spaces)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone")
    private JsonNullable<String> phone;

    @JsonCreator
    public CreateSyntheticAccountInstantPaymentResponse(
            @JsonProperty("counterparty_address") @Nullable CreateSyntheticAccountInstantPaymentCounterpartyAddressResponse counterpartyAddress,
            @JsonProperty("counterparty_name") @Nullable String counterpartyName,
            @JsonProperty("email") @Nullable JsonNullable<String> email,
            @JsonProperty("phone") @Nullable JsonNullable<String> phone) {
        this.counterpartyAddress = counterpartyAddress;
        this.counterpartyName = counterpartyName;
        this.email = Optional.ofNullable(email)
            .orElse(JsonNullable.undefined());
        this.phone = Optional.ofNullable(phone)
            .orElse(JsonNullable.undefined());
    }
    
    public CreateSyntheticAccountInstantPaymentResponse() {
        this(null, null, null,
            null);
    }

    /**
     * Address of the business or individual who owns the external account.
     */
    public Optional<CreateSyntheticAccountInstantPaymentCounterpartyAddressResponse> counterpartyAddress() {
        return Optional.ofNullable(this.counterpartyAddress);
    }

    /**
     * Name of the business or individual who owns the counterparty Account.
     */
    public Optional<String> counterpartyName() {
        return Optional.ofNullable(this.counterpartyName);
    }

    /**
     * Email address of the counterparty
     */
    public JsonNullable<String> email() {
        return this.email;
    }

    /**
     * Exactly 10 digits long (no hyphens, parentheses, or spaces)
     */
    public JsonNullable<String> phone() {
        return this.phone;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Address of the business or individual who owns the external account.
     */
    public CreateSyntheticAccountInstantPaymentResponse withCounterpartyAddress(@Nullable CreateSyntheticAccountInstantPaymentCounterpartyAddressResponse counterpartyAddress) {
        this.counterpartyAddress = counterpartyAddress;
        return this;
    }


    /**
     * Name of the business or individual who owns the counterparty Account.
     */
    public CreateSyntheticAccountInstantPaymentResponse withCounterpartyName(@Nullable String counterpartyName) {
        this.counterpartyName = counterpartyName;
        return this;
    }


    /**
     * Email address of the counterparty
     */
    public CreateSyntheticAccountInstantPaymentResponse withEmail(@Nullable String email) {
        this.email = JsonNullable.of(email);
        return this;
    }


    /**
     * Exactly 10 digits long (no hyphens, parentheses, or spaces)
     */
    public CreateSyntheticAccountInstantPaymentResponse withPhone(@Nullable String phone) {
        this.phone = JsonNullable.of(phone);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSyntheticAccountInstantPaymentResponse other = (CreateSyntheticAccountInstantPaymentResponse) o;
        return 
            Utils.enhancedDeepEquals(this.counterpartyAddress, other.counterpartyAddress) &&
            Utils.enhancedDeepEquals(this.counterpartyName, other.counterpartyName) &&
            Utils.enhancedDeepEquals(this.email, other.email) &&
            Utils.enhancedDeepEquals(this.phone, other.phone);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            counterpartyAddress, counterpartyName, email,
            phone);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateSyntheticAccountInstantPaymentResponse.class,
                "counterpartyAddress", counterpartyAddress,
                "counterpartyName", counterpartyName,
                "email", email,
                "phone", phone);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private CreateSyntheticAccountInstantPaymentCounterpartyAddressResponse counterpartyAddress;

        private String counterpartyName;

        private JsonNullable<String> email;

        private JsonNullable<String> phone;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Address of the business or individual who owns the external account.
         */
        public Builder counterpartyAddress(@Nullable CreateSyntheticAccountInstantPaymentCounterpartyAddressResponse counterpartyAddress) {
            this.counterpartyAddress = counterpartyAddress;
            return this;
        }

        /**
         * Name of the business or individual who owns the counterparty Account.
         */
        public Builder counterpartyName(@Nullable String counterpartyName) {
            this.counterpartyName = counterpartyName;
            return this;
        }

        /**
         * Email address of the counterparty
         */
        public Builder email(@Nullable String email) {
            this.email = JsonNullable.of(email);
            return this;
        }

        /**
         * Exactly 10 digits long (no hyphens, parentheses, or spaces)
         */
        public Builder phone(@Nullable String phone) {
            this.phone = JsonNullable.of(phone);
            return this;
        }

        public CreateSyntheticAccountInstantPaymentResponse build() {
            return new CreateSyntheticAccountInstantPaymentResponse(
                counterpartyAddress, counterpartyName, email,
                phone);
        }

    }
}
