/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * CreateSyntheticAccountSyntheticAccountCategory
 * 
 * <p>The name of the Synthetic Account Category associated with the Synthetic Account Type for this
 * account. Refer to the Synthetic Account Type for details.
 */
public class CreateSyntheticAccountSyntheticAccountCategory {

    public static final CreateSyntheticAccountSyntheticAccountCategory GENERAL = new CreateSyntheticAccountSyntheticAccountCategory("general");
    public static final CreateSyntheticAccountSyntheticAccountCategory ACH_EXTERNAL = new CreateSyntheticAccountSyntheticAccountCategory("ach_external");
    public static final CreateSyntheticAccountSyntheticAccountCategory INSTANT_PAYMENT_EXTERNAL = new CreateSyntheticAccountSyntheticAccountCategory("instant_payment_external");
    public static final CreateSyntheticAccountSyntheticAccountCategory WIRE_EXTERNAL = new CreateSyntheticAccountSyntheticAccountCategory("wire_external");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, CreateSyntheticAccountSyntheticAccountCategory> values = createValuesMap();
    private static final Map<String, CreateSyntheticAccountSyntheticAccountCategoryEnum> enums = createEnumsMap();

    private final String value;

    private CreateSyntheticAccountSyntheticAccountCategory(String value) {
        this.value = value;
    }

    /**
     * Returns a CreateSyntheticAccountSyntheticAccountCategory with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as CreateSyntheticAccountSyntheticAccountCategory
     */ 
    @JsonCreator
    public static CreateSyntheticAccountSyntheticAccountCategory of(String value) {
        synchronized (CreateSyntheticAccountSyntheticAccountCategory.class) {
            return values.computeIfAbsent(value, v -> new CreateSyntheticAccountSyntheticAccountCategory(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<CreateSyntheticAccountSyntheticAccountCategoryEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CreateSyntheticAccountSyntheticAccountCategory other = (CreateSyntheticAccountSyntheticAccountCategory) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "CreateSyntheticAccountSyntheticAccountCategory [value=" + value + "]";
    }

    // return an array just like an enum
    public static CreateSyntheticAccountSyntheticAccountCategory[] values() {
        synchronized (CreateSyntheticAccountSyntheticAccountCategory.class) {
            return values.values().toArray(new CreateSyntheticAccountSyntheticAccountCategory[] {});
        }
    }

    private static final Map<String, CreateSyntheticAccountSyntheticAccountCategory> createValuesMap() {
        Map<String, CreateSyntheticAccountSyntheticAccountCategory> map = new LinkedHashMap<>();
        map.put("general", GENERAL);
        map.put("ach_external", ACH_EXTERNAL);
        map.put("instant_payment_external", INSTANT_PAYMENT_EXTERNAL);
        map.put("wire_external", WIRE_EXTERNAL);
        return map;
    }

    private static final Map<String, CreateSyntheticAccountSyntheticAccountCategoryEnum> createEnumsMap() {
        Map<String, CreateSyntheticAccountSyntheticAccountCategoryEnum> map = new HashMap<>();
        map.put("general", CreateSyntheticAccountSyntheticAccountCategoryEnum.GENERAL);
        map.put("ach_external", CreateSyntheticAccountSyntheticAccountCategoryEnum.ACH_EXTERNAL);
        map.put("instant_payment_external", CreateSyntheticAccountSyntheticAccountCategoryEnum.INSTANT_PAYMENT_EXTERNAL);
        map.put("wire_external", CreateSyntheticAccountSyntheticAccountCategoryEnum.WIRE_EXTERNAL);
        return map;
    }
    
    
    public enum CreateSyntheticAccountSyntheticAccountCategoryEnum {

        GENERAL("general"),
        ACH_EXTERNAL("ach_external"),
        INSTANT_PAYMENT_EXTERNAL("instant_payment_external"),
        WIRE_EXTERNAL("wire_external"),;

        private final String value;

        private CreateSyntheticAccountSyntheticAccountCategoryEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

