/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateTransferPaymentTypeRequest
 * 
 * <p>Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
 * default value populated in the NACHA file is for a single entry.
 */
public enum CreateTransferPaymentTypeRequest {
    R("R"),
    S("S"),
    ST("ST");

    @JsonValue
    private final String value;

    CreateTransferPaymentTypeRequest(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateTransferPaymentTypeRequest> fromValue(String value) {
        for (CreateTransferPaymentTypeRequest o: CreateTransferPaymentTypeRequest.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

