/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * CreateSyntheticAccountWireRequest
 * 
 * <p>Contains wire-specific information. Only populated if the Synthetic Account is in the
 * `wire_external` category.
 */
public class CreateSyntheticAccountWireRequest {
    /**
     * Address of the business or individual who owns the external account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_address")
    private JsonNullable<CreateSyntheticAccountWireCounterpartyAddressRequest> counterpartyAddress;

    /**
     * Name of the business or individual who owns the counterparty Account. Required for synthetic
     * accounts in the wire_external category. Maximum 35 characters.
     */
    @JsonProperty("counterparty_name")
    private String counterpartyName;

    /**
     * Address of the financial institution where the external account is held.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_bank_address")
    private JsonNullable<CreateSyntheticAccountCounterpartyBankAddressRequest> counterpartyBankAddress;

    /**
     * Name of the financial institution where the counterparty account is held.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_bank_name")
    private JsonNullable<String> counterpartyBankName;

    @JsonCreator
    public CreateSyntheticAccountWireRequest(
            @JsonProperty("counterparty_address") @Nullable JsonNullable<CreateSyntheticAccountWireCounterpartyAddressRequest> counterpartyAddress,
            @JsonProperty("counterparty_name") @Nonnull String counterpartyName,
            @JsonProperty("counterparty_bank_address") @Nullable JsonNullable<CreateSyntheticAccountCounterpartyBankAddressRequest> counterpartyBankAddress,
            @JsonProperty("counterparty_bank_name") @Nullable JsonNullable<String> counterpartyBankName) {
        this.counterpartyAddress = Optional.ofNullable(counterpartyAddress)
            .orElse(JsonNullable.undefined());
        this.counterpartyName = Optional.ofNullable(counterpartyName)
            .orElseThrow(() -> new IllegalArgumentException("counterpartyName cannot be null"));
        this.counterpartyBankAddress = Optional.ofNullable(counterpartyBankAddress)
            .orElse(JsonNullable.undefined());
        this.counterpartyBankName = Optional.ofNullable(counterpartyBankName)
            .orElse(JsonNullable.undefined());
    }
    
    public CreateSyntheticAccountWireRequest(
            @Nonnull String counterpartyName) {
        this(null, counterpartyName, null,
            null);
    }

    /**
     * Address of the business or individual who owns the external account.
     */
    public JsonNullable<CreateSyntheticAccountWireCounterpartyAddressRequest> counterpartyAddress() {
        return this.counterpartyAddress;
    }

    /**
     * Name of the business or individual who owns the counterparty Account. Required for synthetic
     * accounts in the wire_external category. Maximum 35 characters.
     */
    public String counterpartyName() {
        return this.counterpartyName;
    }

    /**
     * Address of the financial institution where the external account is held.
     */
    public JsonNullable<CreateSyntheticAccountCounterpartyBankAddressRequest> counterpartyBankAddress() {
        return this.counterpartyBankAddress;
    }

    /**
     * Name of the financial institution where the counterparty account is held.
     */
    public JsonNullable<String> counterpartyBankName() {
        return this.counterpartyBankName;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Address of the business or individual who owns the external account.
     */
    public CreateSyntheticAccountWireRequest withCounterpartyAddress(@Nullable CreateSyntheticAccountWireCounterpartyAddressRequest counterpartyAddress) {
        this.counterpartyAddress = JsonNullable.of(counterpartyAddress);
        return this;
    }


    /**
     * Name of the business or individual who owns the counterparty Account. Required for synthetic
     * accounts in the wire_external category. Maximum 35 characters.
     */
    public CreateSyntheticAccountWireRequest withCounterpartyName(@Nonnull String counterpartyName) {
        this.counterpartyName = Utils.checkNotNull(counterpartyName, "counterpartyName");
        return this;
    }


    /**
     * Address of the financial institution where the external account is held.
     */
    public CreateSyntheticAccountWireRequest withCounterpartyBankAddress(@Nullable CreateSyntheticAccountCounterpartyBankAddressRequest counterpartyBankAddress) {
        this.counterpartyBankAddress = JsonNullable.of(counterpartyBankAddress);
        return this;
    }


    /**
     * Name of the financial institution where the counterparty account is held.
     */
    public CreateSyntheticAccountWireRequest withCounterpartyBankName(@Nullable String counterpartyBankName) {
        this.counterpartyBankName = JsonNullable.of(counterpartyBankName);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSyntheticAccountWireRequest other = (CreateSyntheticAccountWireRequest) o;
        return 
            Utils.enhancedDeepEquals(this.counterpartyAddress, other.counterpartyAddress) &&
            Utils.enhancedDeepEquals(this.counterpartyName, other.counterpartyName) &&
            Utils.enhancedDeepEquals(this.counterpartyBankAddress, other.counterpartyBankAddress) &&
            Utils.enhancedDeepEquals(this.counterpartyBankName, other.counterpartyBankName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            counterpartyAddress, counterpartyName, counterpartyBankAddress,
            counterpartyBankName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateSyntheticAccountWireRequest.class,
                "counterpartyAddress", counterpartyAddress,
                "counterpartyName", counterpartyName,
                "counterpartyBankAddress", counterpartyBankAddress,
                "counterpartyBankName", counterpartyBankName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<CreateSyntheticAccountWireCounterpartyAddressRequest> counterpartyAddress;

        private String counterpartyName;

        private JsonNullable<CreateSyntheticAccountCounterpartyBankAddressRequest> counterpartyBankAddress;

        private JsonNullable<String> counterpartyBankName;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Address of the business or individual who owns the external account.
         */
        public Builder counterpartyAddress(@Nullable CreateSyntheticAccountWireCounterpartyAddressRequest counterpartyAddress) {
            this.counterpartyAddress = JsonNullable.of(counterpartyAddress);
            return this;
        }

        /**
         * Name of the business or individual who owns the counterparty Account. Required for synthetic
         * accounts in the wire_external category. Maximum 35 characters.
         */
        public Builder counterpartyName(@Nonnull String counterpartyName) {
            this.counterpartyName = Utils.checkNotNull(counterpartyName, "counterpartyName");
            return this;
        }

        /**
         * Address of the financial institution where the external account is held.
         */
        public Builder counterpartyBankAddress(@Nullable CreateSyntheticAccountCounterpartyBankAddressRequest counterpartyBankAddress) {
            this.counterpartyBankAddress = JsonNullable.of(counterpartyBankAddress);
            return this;
        }

        /**
         * Name of the financial institution where the counterparty account is held.
         */
        public Builder counterpartyBankName(@Nullable String counterpartyBankName) {
            this.counterpartyBankName = JsonNullable.of(counterpartyBankName);
            return this;
        }

        public CreateSyntheticAccountWireRequest build() {
            return new CreateSyntheticAccountWireRequest(
                counterpartyAddress, counterpartyName, counterpartyBankAddress,
                counterpartyBankName);
        }

    }
}
