/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * CreateTransferSecCodeResponse
 * 
 * <p>Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
 * For more details, refer to our ACH guide's
 * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
 */
public class CreateTransferSecCodeResponse {

    public static final CreateTransferSecCodeResponse CCD = new CreateTransferSecCodeResponse("CCD");
    public static final CreateTransferSecCodeResponse CIE = new CreateTransferSecCodeResponse("CIE");
    public static final CreateTransferSecCodeResponse PPD = new CreateTransferSecCodeResponse("PPD");
    public static final CreateTransferSecCodeResponse TEL = new CreateTransferSecCodeResponse("TEL");
    public static final CreateTransferSecCodeResponse WEB = new CreateTransferSecCodeResponse("WEB");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, CreateTransferSecCodeResponse> values = createValuesMap();
    private static final Map<String, CreateTransferSecCodeResponseEnum> enums = createEnumsMap();

    private final String value;

    private CreateTransferSecCodeResponse(String value) {
        this.value = value;
    }

    /**
     * Returns a CreateTransferSecCodeResponse with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as CreateTransferSecCodeResponse
     */ 
    @JsonCreator
    public static CreateTransferSecCodeResponse of(String value) {
        synchronized (CreateTransferSecCodeResponse.class) {
            return values.computeIfAbsent(value, v -> new CreateTransferSecCodeResponse(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<CreateTransferSecCodeResponseEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        CreateTransferSecCodeResponse other = (CreateTransferSecCodeResponse) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "CreateTransferSecCodeResponse [value=" + value + "]";
    }

    // return an array just like an enum
    public static CreateTransferSecCodeResponse[] values() {
        synchronized (CreateTransferSecCodeResponse.class) {
            return values.values().toArray(new CreateTransferSecCodeResponse[] {});
        }
    }

    private static final Map<String, CreateTransferSecCodeResponse> createValuesMap() {
        Map<String, CreateTransferSecCodeResponse> map = new LinkedHashMap<>();
        map.put("CCD", CCD);
        map.put("CIE", CIE);
        map.put("PPD", PPD);
        map.put("TEL", TEL);
        map.put("WEB", WEB);
        return map;
    }

    private static final Map<String, CreateTransferSecCodeResponseEnum> createEnumsMap() {
        Map<String, CreateTransferSecCodeResponseEnum> map = new HashMap<>();
        map.put("CCD", CreateTransferSecCodeResponseEnum.CCD);
        map.put("CIE", CreateTransferSecCodeResponseEnum.CIE);
        map.put("PPD", CreateTransferSecCodeResponseEnum.PPD);
        map.put("TEL", CreateTransferSecCodeResponseEnum.TEL);
        map.put("WEB", CreateTransferSecCodeResponseEnum.WEB);
        return map;
    }
    
    
    public enum CreateTransferSecCodeResponseEnum {

        CCD("CCD"),
        CIE("CIE"),
        PPD("PPD"),
        TEL("TEL"),
        WEB("WEB"),;

        private final String value;

        private CreateTransferSecCodeResponseEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

