/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class DeleteCustomerKycStatusReason {

    public static final DeleteCustomerKycStatusReason APPROVED = new DeleteCustomerKycStatusReason("Approved");
    public static final DeleteCustomerKycStatusReason VALID_DOCUMENTS_PROVIDED = new DeleteCustomerKycStatusReason("Valid Documents Provided");
    public static final DeleteCustomerKycStatusReason ARCHIVED_DUE_TO_APPLICATION_INACTIVITY = new DeleteCustomerKycStatusReason("Archived due to application inactivity");
    public static final DeleteCustomerKycStatusReason FURTHER_REVIEW_REQUIRED = new DeleteCustomerKycStatusReason("Further review required");
    public static final DeleteCustomerKycStatusReason MINOR_AGE_LESS_THAN18_YEARS = new DeleteCustomerKycStatusReason("Minor (age < 18 years)");
    public static final DeleteCustomerKycStatusReason INVALID_DOCUMENTS_SUBMITTED_MULTIPLE_TIMES = new DeleteCustomerKycStatusReason("Invalid Documents submitted multiple times");
    public static final DeleteCustomerKycStatusReason MINIMUM_REQUIREMENTS_TO_OPEN_AN_ACCOUNT_WERE_NOT_MET = new DeleteCustomerKycStatusReason("Minimum requirements to open an account were not met");
    public static final DeleteCustomerKycStatusReason INVALID_DOCUMENTS = new DeleteCustomerKycStatusReason("Invalid documents");
    public static final DeleteCustomerKycStatusReason INCORRECT_DOCUMENT_PROVIDED_FOR_ID_DOCUMENT = new DeleteCustomerKycStatusReason("Incorrect document provided for ID document");
    public static final DeleteCustomerKycStatusReason EXPIRED_ID = new DeleteCustomerKycStatusReason("Expired ID");
    public static final DeleteCustomerKycStatusReason ILLEGIBLE_ID_DOCUMENT = new DeleteCustomerKycStatusReason("Illegible ID document");
    public static final DeleteCustomerKycStatusReason INCORRECT_DOCUMENT_PROVIDED_FOR_POA_DOCUMENT = new DeleteCustomerKycStatusReason("Incorrect document provided for POA document");
    public static final DeleteCustomerKycStatusReason INVALID_POA_PROVIDED = new DeleteCustomerKycStatusReason("Invalid POA provided");
    public static final DeleteCustomerKycStatusReason ILLEGIBLE_POA_DOCUMENT = new DeleteCustomerKycStatusReason("Illegible POA document");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DeleteCustomerKycStatusReason> values = createValuesMap();
    private static final Map<String, DeleteCustomerKycStatusReasonEnum> enums = createEnumsMap();

    private final String value;

    private DeleteCustomerKycStatusReason(String value) {
        this.value = value;
    }

    /**
     * Returns a DeleteCustomerKycStatusReason with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as DeleteCustomerKycStatusReason
     */ 
    @JsonCreator
    public static DeleteCustomerKycStatusReason of(String value) {
        synchronized (DeleteCustomerKycStatusReason.class) {
            return values.computeIfAbsent(value, v -> new DeleteCustomerKycStatusReason(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DeleteCustomerKycStatusReasonEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DeleteCustomerKycStatusReason other = (DeleteCustomerKycStatusReason) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DeleteCustomerKycStatusReason [value=" + value + "]";
    }

    // return an array just like an enum
    public static DeleteCustomerKycStatusReason[] values() {
        synchronized (DeleteCustomerKycStatusReason.class) {
            return values.values().toArray(new DeleteCustomerKycStatusReason[] {});
        }
    }

    private static final Map<String, DeleteCustomerKycStatusReason> createValuesMap() {
        Map<String, DeleteCustomerKycStatusReason> map = new LinkedHashMap<>();
        map.put("Approved", APPROVED);
        map.put("Valid Documents Provided", VALID_DOCUMENTS_PROVIDED);
        map.put("Archived due to application inactivity", ARCHIVED_DUE_TO_APPLICATION_INACTIVITY);
        map.put("Further review required", FURTHER_REVIEW_REQUIRED);
        map.put("Minor (age < 18 years)", MINOR_AGE_LESS_THAN18_YEARS);
        map.put("Invalid Documents submitted multiple times", INVALID_DOCUMENTS_SUBMITTED_MULTIPLE_TIMES);
        map.put("Minimum requirements to open an account were not met", MINIMUM_REQUIREMENTS_TO_OPEN_AN_ACCOUNT_WERE_NOT_MET);
        map.put("Invalid documents", INVALID_DOCUMENTS);
        map.put("Incorrect document provided for ID document", INCORRECT_DOCUMENT_PROVIDED_FOR_ID_DOCUMENT);
        map.put("Expired ID", EXPIRED_ID);
        map.put("Illegible ID document", ILLEGIBLE_ID_DOCUMENT);
        map.put("Incorrect document provided for POA document", INCORRECT_DOCUMENT_PROVIDED_FOR_POA_DOCUMENT);
        map.put("Invalid POA provided", INVALID_POA_PROVIDED);
        map.put("Illegible POA document", ILLEGIBLE_POA_DOCUMENT);
        return map;
    }

    private static final Map<String, DeleteCustomerKycStatusReasonEnum> createEnumsMap() {
        Map<String, DeleteCustomerKycStatusReasonEnum> map = new HashMap<>();
        map.put("Approved", DeleteCustomerKycStatusReasonEnum.APPROVED);
        map.put("Valid Documents Provided", DeleteCustomerKycStatusReasonEnum.VALID_DOCUMENTS_PROVIDED);
        map.put("Archived due to application inactivity", DeleteCustomerKycStatusReasonEnum.ARCHIVED_DUE_TO_APPLICATION_INACTIVITY);
        map.put("Further review required", DeleteCustomerKycStatusReasonEnum.FURTHER_REVIEW_REQUIRED);
        map.put("Minor (age < 18 years)", DeleteCustomerKycStatusReasonEnum.MINOR_AGE_LESS_THAN18_YEARS);
        map.put("Invalid Documents submitted multiple times", DeleteCustomerKycStatusReasonEnum.INVALID_DOCUMENTS_SUBMITTED_MULTIPLE_TIMES);
        map.put("Minimum requirements to open an account were not met", DeleteCustomerKycStatusReasonEnum.MINIMUM_REQUIREMENTS_TO_OPEN_AN_ACCOUNT_WERE_NOT_MET);
        map.put("Invalid documents", DeleteCustomerKycStatusReasonEnum.INVALID_DOCUMENTS);
        map.put("Incorrect document provided for ID document", DeleteCustomerKycStatusReasonEnum.INCORRECT_DOCUMENT_PROVIDED_FOR_ID_DOCUMENT);
        map.put("Expired ID", DeleteCustomerKycStatusReasonEnum.EXPIRED_ID);
        map.put("Illegible ID document", DeleteCustomerKycStatusReasonEnum.ILLEGIBLE_ID_DOCUMENT);
        map.put("Incorrect document provided for POA document", DeleteCustomerKycStatusReasonEnum.INCORRECT_DOCUMENT_PROVIDED_FOR_POA_DOCUMENT);
        map.put("Invalid POA provided", DeleteCustomerKycStatusReasonEnum.INVALID_POA_PROVIDED);
        map.put("Illegible POA document", DeleteCustomerKycStatusReasonEnum.ILLEGIBLE_POA_DOCUMENT);
        return map;
    }
    
    
    public enum DeleteCustomerKycStatusReasonEnum {

        APPROVED("Approved"),
        VALID_DOCUMENTS_PROVIDED("Valid Documents Provided"),
        ARCHIVED_DUE_TO_APPLICATION_INACTIVITY("Archived due to application inactivity"),
        FURTHER_REVIEW_REQUIRED("Further review required"),
        MINOR_AGE_LESS_THAN18_YEARS("Minor (age < 18 years)"),
        INVALID_DOCUMENTS_SUBMITTED_MULTIPLE_TIMES("Invalid Documents submitted multiple times"),
        MINIMUM_REQUIREMENTS_TO_OPEN_AN_ACCOUNT_WERE_NOT_MET("Minimum requirements to open an account were not met"),
        INVALID_DOCUMENTS("Invalid documents"),
        INCORRECT_DOCUMENT_PROVIDED_FOR_ID_DOCUMENT("Incorrect document provided for ID document"),
        EXPIRED_ID("Expired ID"),
        ILLEGIBLE_ID_DOCUMENT("Illegible ID document"),
        INCORRECT_DOCUMENT_PROVIDED_FOR_POA_DOCUMENT("Incorrect document provided for POA document"),
        INVALID_POA_PROVIDED("Invalid POA provided"),
        ILLEGIBLE_POA_DOCUMENT("Illegible POA document"),;

        private final String value;

        private DeleteCustomerKycStatusReasonEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

