/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import static com.newline53.sdk.operations.Operations.RequestlessOperation;

import com.newline53.sdk.SDKConfiguration;
import com.newline53.sdk.operations.GenerateAuthToken;
import com.newline53.sdk.utils.Headers;
import com.newline53.sdk.utils.Utils;

public class GenerateAuthTokenRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();

    public GenerateAuthTokenRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    
    public GenerateAuthTokenRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GenerateAuthTokenResponse call() {
        RequestlessOperation<GenerateAuthTokenResponse> operation
            = new GenerateAuthToken.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest());
    }
}
