/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetCustomerProductStatus
 * 
 * <p>the status of the Customer Product onboarding
 */
public class GetCustomerProductStatus {

    public static final GetCustomerProductStatus ACTIVE = new GetCustomerProductStatus("active");
    public static final GetCustomerProductStatus CREATED = new GetCustomerProductStatus("created");
    public static final GetCustomerProductStatus MANUAL_REVIEW = new GetCustomerProductStatus("manual_review");
    public static final GetCustomerProductStatus REJECTED = new GetCustomerProductStatus("rejected");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetCustomerProductStatus> values = createValuesMap();
    private static final Map<String, GetCustomerProductStatusEnum> enums = createEnumsMap();

    private final String value;

    private GetCustomerProductStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a GetCustomerProductStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetCustomerProductStatus
     */ 
    @JsonCreator
    public static GetCustomerProductStatus of(String value) {
        synchronized (GetCustomerProductStatus.class) {
            return values.computeIfAbsent(value, v -> new GetCustomerProductStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetCustomerProductStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetCustomerProductStatus other = (GetCustomerProductStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetCustomerProductStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetCustomerProductStatus[] values() {
        synchronized (GetCustomerProductStatus.class) {
            return values.values().toArray(new GetCustomerProductStatus[] {});
        }
    }

    private static final Map<String, GetCustomerProductStatus> createValuesMap() {
        Map<String, GetCustomerProductStatus> map = new LinkedHashMap<>();
        map.put("active", ACTIVE);
        map.put("created", CREATED);
        map.put("manual_review", MANUAL_REVIEW);
        map.put("rejected", REJECTED);
        return map;
    }

    private static final Map<String, GetCustomerProductStatusEnum> createEnumsMap() {
        Map<String, GetCustomerProductStatusEnum> map = new HashMap<>();
        map.put("active", GetCustomerProductStatusEnum.ACTIVE);
        map.put("created", GetCustomerProductStatusEnum.CREATED);
        map.put("manual_review", GetCustomerProductStatusEnum.MANUAL_REVIEW);
        map.put("rejected", GetCustomerProductStatusEnum.REJECTED);
        return map;
    }
    
    
    public enum GetCustomerProductStatusEnum {

        ACTIVE("active"),
        CREATED("created"),
        MANUAL_REVIEW("manual_review"),
        REJECTED("rejected"),;

        private final String value;

        private GetCustomerProductStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

