/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetCustodialLineItemsUidStatus
 * 
 * <p>Other statuses such as `pending` will be available later
 */
public class GetCustodialLineItemsUidStatus {

    public static final GetCustodialLineItemsUidStatus SETTLED = new GetCustodialLineItemsUidStatus("settled");
    public static final GetCustodialLineItemsUidStatus VOIDED = new GetCustodialLineItemsUidStatus("voided");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetCustodialLineItemsUidStatus> values = createValuesMap();
    private static final Map<String, GetCustodialLineItemsUidStatusEnum> enums = createEnumsMap();

    private final String value;

    private GetCustodialLineItemsUidStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a GetCustodialLineItemsUidStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetCustodialLineItemsUidStatus
     */ 
    @JsonCreator
    public static GetCustodialLineItemsUidStatus of(String value) {
        synchronized (GetCustodialLineItemsUidStatus.class) {
            return values.computeIfAbsent(value, v -> new GetCustodialLineItemsUidStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetCustodialLineItemsUidStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetCustodialLineItemsUidStatus other = (GetCustodialLineItemsUidStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetCustodialLineItemsUidStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetCustodialLineItemsUidStatus[] values() {
        synchronized (GetCustodialLineItemsUidStatus.class) {
            return values.values().toArray(new GetCustodialLineItemsUidStatus[] {});
        }
    }

    private static final Map<String, GetCustodialLineItemsUidStatus> createValuesMap() {
        Map<String, GetCustodialLineItemsUidStatus> map = new LinkedHashMap<>();
        map.put("settled", SETTLED);
        map.put("voided", VOIDED);
        return map;
    }

    private static final Map<String, GetCustodialLineItemsUidStatusEnum> createEnumsMap() {
        Map<String, GetCustodialLineItemsUidStatusEnum> map = new HashMap<>();
        map.put("settled", GetCustodialLineItemsUidStatusEnum.SETTLED);
        map.put("voided", GetCustodialLineItemsUidStatusEnum.VOIDED);
        return map;
    }
    
    
    public enum GetCustodialLineItemsUidStatusEnum {

        SETTLED("settled"),
        VOIDED("voided"),;

        private final String value;

        private GetCustodialLineItemsUidStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

