/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetCustodialLineItemsSort
 */
public enum GetCustodialLineItemsSort {
    CREATED_AT_ASC("created_at_asc"),
    CREATED_AT_DESC("created_at_desc"),
    DESCRIPTION_ASC("description_asc"),
    DESCRIPTION_DESC("description_desc"),
    SETTLED_INDEX_ASC("settled_index_asc"),
    SETTLED_INDEX_DESC("settled_index_desc"),
    US_DOLLAR_AMOUNT_ASC("us_dollar_amount_asc"),
    US_DOLLAR_AMOUNT_DESC("us_dollar_amount_desc");

    @JsonValue
    private final String value;

    GetCustodialLineItemsSort(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetCustodialLineItemsSort> fromValue(String value) {
        for (GetCustodialLineItemsSort o: GetCustodialLineItemsSort.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

