/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.SDKConfiguration;
import com.newline53.sdk.operations.GetCustomerProduct;
import com.newline53.sdk.utils.Headers;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.String;

public class GetCustomerProductRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetCustomerProductRequest.Builder pojoBuilder;
    private GetCustomerProductRequest request;
    private boolean _setterCalled;

    public GetCustomerProductRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetCustomerProductRequest.builder();
    }

    public GetCustomerProductRequestBuilder uid(@Nonnull String uid) {
        this.pojoBuilder.uid(uid);
        this._setterCalled = true;
        return this;
    }

    private GetCustomerProductRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetCustomerProductRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetCustomerProductResponse call() {
        RequestOperation<GetCustomerProductRequest, GetCustomerProductResponse> operation
              = new GetCustomerProduct.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
