/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * GetCombinedTransfersUidResponseBody
 * 
 * <p>A single Combined Transfer is returned
 */
public class GetCombinedTransfersUidResponseBody {
    /**
     * Timestamp of when the combined_transfer was created
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    private String createdAt;

    /**
     * A collection of errors that occured during synthetic account and/or transfer creation. Only
     * displayed if errors were detected.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errors")
    private List<GetCombinedTransfersUidError> errors;

    /**
     * Optional client-supplied uid
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("external_uid")
    private String externalUid;

    /**
     * The combined transfer's status
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private GetCombinedTransfersUidStatus status;

    /**
     * Parameters provided at time of creation. UID field will get populated once synthetic account has
     * been successfully created, unless uid value was supplied at creation time.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("synthetic_account")
    private GetCombinedTransfersUidSyntheticAccount syntheticAccount;

    /**
     * Parameters provided at time of creation. UID field will get populated once transfer has been
     * successfully initiated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transfer")
    private GetCombinedTransfersUidTransfer transfer;

    /**
     * Unique identifier for the Combined Transfer
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uid")
    private String uid;

    @JsonCreator
    public GetCombinedTransfersUidResponseBody(
            @JsonProperty("created_at") @Nullable String createdAt,
            @JsonProperty("errors") @Nullable List<GetCombinedTransfersUidError> errors,
            @JsonProperty("external_uid") @Nullable String externalUid,
            @JsonProperty("status") @Nullable GetCombinedTransfersUidStatus status,
            @JsonProperty("synthetic_account") @Nullable GetCombinedTransfersUidSyntheticAccount syntheticAccount,
            @JsonProperty("transfer") @Nullable GetCombinedTransfersUidTransfer transfer,
            @JsonProperty("uid") @Nullable String uid) {
        this.createdAt = createdAt;
        this.errors = errors;
        this.externalUid = externalUid;
        this.status = status;
        this.syntheticAccount = syntheticAccount;
        this.transfer = transfer;
        this.uid = uid;
    }
    
    public GetCombinedTransfersUidResponseBody() {
        this(null, null, null,
            null, null, null,
            null);
    }

    /**
     * Timestamp of when the combined_transfer was created
     */
    public Optional<String> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * A collection of errors that occured during synthetic account and/or transfer creation. Only
     * displayed if errors were detected.
     */
    public Optional<List<GetCombinedTransfersUidError>> errors() {
        return Optional.ofNullable(this.errors);
    }

    /**
     * Optional client-supplied uid
     */
    public Optional<String> externalUid() {
        return Optional.ofNullable(this.externalUid);
    }

    /**
     * The combined transfer's status
     */
    public Optional<GetCombinedTransfersUidStatus> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Parameters provided at time of creation. UID field will get populated once synthetic account has
     * been successfully created, unless uid value was supplied at creation time.
     */
    public Optional<GetCombinedTransfersUidSyntheticAccount> syntheticAccount() {
        return Optional.ofNullable(this.syntheticAccount);
    }

    /**
     * Parameters provided at time of creation. UID field will get populated once transfer has been
     * successfully initiated.
     */
    public Optional<GetCombinedTransfersUidTransfer> transfer() {
        return Optional.ofNullable(this.transfer);
    }

    /**
     * Unique identifier for the Combined Transfer
     */
    public Optional<String> uid() {
        return Optional.ofNullable(this.uid);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Timestamp of when the combined_transfer was created
     */
    public GetCombinedTransfersUidResponseBody withCreatedAt(@Nullable String createdAt) {
        this.createdAt = createdAt;
        return this;
    }


    /**
     * A collection of errors that occured during synthetic account and/or transfer creation. Only
     * displayed if errors were detected.
     */
    public GetCombinedTransfersUidResponseBody withErrors(@Nullable List<GetCombinedTransfersUidError> errors) {
        this.errors = errors;
        return this;
    }


    /**
     * Optional client-supplied uid
     */
    public GetCombinedTransfersUidResponseBody withExternalUid(@Nullable String externalUid) {
        this.externalUid = externalUid;
        return this;
    }


    /**
     * The combined transfer's status
     */
    public GetCombinedTransfersUidResponseBody withStatus(@Nullable GetCombinedTransfersUidStatus status) {
        this.status = status;
        return this;
    }


    /**
     * Parameters provided at time of creation. UID field will get populated once synthetic account has
     * been successfully created, unless uid value was supplied at creation time.
     */
    public GetCombinedTransfersUidResponseBody withSyntheticAccount(@Nullable GetCombinedTransfersUidSyntheticAccount syntheticAccount) {
        this.syntheticAccount = syntheticAccount;
        return this;
    }


    /**
     * Parameters provided at time of creation. UID field will get populated once transfer has been
     * successfully initiated.
     */
    public GetCombinedTransfersUidResponseBody withTransfer(@Nullable GetCombinedTransfersUidTransfer transfer) {
        this.transfer = transfer;
        return this;
    }


    /**
     * Unique identifier for the Combined Transfer
     */
    public GetCombinedTransfersUidResponseBody withUid(@Nullable String uid) {
        this.uid = uid;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetCombinedTransfersUidResponseBody other = (GetCombinedTransfersUidResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.errors, other.errors) &&
            Utils.enhancedDeepEquals(this.externalUid, other.externalUid) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.syntheticAccount, other.syntheticAccount) &&
            Utils.enhancedDeepEquals(this.transfer, other.transfer) &&
            Utils.enhancedDeepEquals(this.uid, other.uid);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            createdAt, errors, externalUid,
            status, syntheticAccount, transfer,
            uid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetCombinedTransfersUidResponseBody.class,
                "createdAt", createdAt,
                "errors", errors,
                "externalUid", externalUid,
                "status", status,
                "syntheticAccount", syntheticAccount,
                "transfer", transfer,
                "uid", uid);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String createdAt;

        private List<GetCombinedTransfersUidError> errors;

        private String externalUid;

        private GetCombinedTransfersUidStatus status;

        private GetCombinedTransfersUidSyntheticAccount syntheticAccount;

        private GetCombinedTransfersUidTransfer transfer;

        private String uid;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Timestamp of when the combined_transfer was created
         */
        public Builder createdAt(@Nullable String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * A collection of errors that occured during synthetic account and/or transfer creation. Only
         * displayed if errors were detected.
         */
        public Builder errors(@Nullable List<GetCombinedTransfersUidError> errors) {
            this.errors = errors;
            return this;
        }

        /**
         * Optional client-supplied uid
         */
        public Builder externalUid(@Nullable String externalUid) {
            this.externalUid = externalUid;
            return this;
        }

        /**
         * The combined transfer's status
         */
        public Builder status(@Nullable GetCombinedTransfersUidStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Parameters provided at time of creation. UID field will get populated once synthetic account has
         * been successfully created, unless uid value was supplied at creation time.
         */
        public Builder syntheticAccount(@Nullable GetCombinedTransfersUidSyntheticAccount syntheticAccount) {
            this.syntheticAccount = syntheticAccount;
            return this;
        }

        /**
         * Parameters provided at time of creation. UID field will get populated once transfer has been
         * successfully initiated.
         */
        public Builder transfer(@Nullable GetCombinedTransfersUidTransfer transfer) {
            this.transfer = transfer;
            return this;
        }

        /**
         * Unique identifier for the Combined Transfer
         */
        public Builder uid(@Nullable String uid) {
            this.uid = uid;
            return this;
        }

        public GetCombinedTransfersUidResponseBody build() {
            return new GetCombinedTransfersUidResponseBody(
                createdAt, errors, externalUid,
                status, syntheticAccount, transfer,
                uid);
        }

    }
}
