/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.newline53.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * GetCombinedTransfersUidSyntheticAccount
 * 
 * <p>Parameters provided at time of creation. UID field will get populated once synthetic account has
 * been successfully created, unless uid value was supplied at creation time.
 */
public class GetCombinedTransfersUidSyntheticAccount {
    @JsonCreator
    public GetCombinedTransfersUidSyntheticAccount() {
    }

    public static Builder builder() {
        return new Builder();
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        return true;
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            );
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetCombinedTransfersUidSyntheticAccount.class);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Builder() {
          // force use of static builder() method
        }

        public GetCombinedTransfersUidSyntheticAccount build() {
            return new GetCombinedTransfersUidSyntheticAccount(
                );
        }

    }
}
