/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import com.newline53.sdk.utils.LazySingletonValue;
import com.newline53.sdk.utils.SpeakeasyMetadata;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Double;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetCustodialLineItemsRequest {
    /**
     * Filter by Customer. Multiple values are allowed, e.g.
     * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=customer_uid")
    private String customerUid;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=custodial_account_uid")
    private String custodialAccountUid;

    /**
     * Filter by status. Multiple values are allowed, e.g. `status[]=pending&amp;status[]=settled`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")
    private GetCustodialLineItemsQueryParamStatus status;

    /**
     * Return any records having a us_dollar_amount at or below us_dollar_amount_max.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=us_dollar_amount_max")
    private Double usDollarAmountMax;

    /**
     * Return any records having a us_dollar_amount at or above us_dollar_amount_min.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=us_dollar_amount_min")
    private Double usDollarAmountMin;

    /**
     * Filter by Transaction Event. Multiple values are allowed, e.g.
     * `transaction_event_uid[]=MB2yqBrm3c4bUbou&amp;transaction_event_uid[]=N5tuy12zZzB9bftb`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=transaction_event_uid")
    private String transactionEventUid;

    /**
     * Filter by Transaction. Multiple values are allowed, e.g.
     * `transaction_uid[]=SMwKC1osz77DTEiu&amp;transaction_uid[]=f1UDvUVNnXTKtgxu`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=transaction_uid")
    private String transactionUid;

    /**
     * Maximum number of items to retrieve. This filter is automatically applied with the default value if
     * not given.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    private Long limit;

    /**
     * Index of the items to start retrieving from
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    private Long offset;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")
    private GetCustodialLineItemsSort sort;

    @JsonCreator
    public GetCustodialLineItemsRequest(
            @Nullable String customerUid,
            @Nullable String custodialAccountUid,
            @Nullable GetCustodialLineItemsQueryParamStatus status,
            @Nullable Double usDollarAmountMax,
            @Nullable Double usDollarAmountMin,
            @Nullable String transactionEventUid,
            @Nullable String transactionUid,
            @Nullable Long limit,
            @Nullable Long offset,
            @Nullable GetCustodialLineItemsSort sort) {
        this.customerUid = customerUid;
        this.custodialAccountUid = custodialAccountUid;
        this.status = status;
        this.usDollarAmountMax = usDollarAmountMax;
        this.usDollarAmountMin = usDollarAmountMin;
        this.transactionEventUid = transactionEventUid;
        this.transactionUid = transactionUid;
        this.limit = Optional.ofNullable(limit)
            .orElse(Builder._SINGLETON_VALUE_Limit.value());
        this.offset = Optional.ofNullable(offset)
            .orElse(Builder._SINGLETON_VALUE_Offset.value());
        this.sort = sort;
    }
    
    public GetCustodialLineItemsRequest() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null);
    }

    /**
     * Filter by Customer. Multiple values are allowed, e.g.
     * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
     */
    public Optional<String> customerUid() {
        return Optional.ofNullable(this.customerUid);
    }

    public Optional<String> custodialAccountUid() {
        return Optional.ofNullable(this.custodialAccountUid);
    }

    /**
     * Filter by status. Multiple values are allowed, e.g. `status[]=pending&amp;status[]=settled`.
     */
    public Optional<GetCustodialLineItemsQueryParamStatus> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Return any records having a us_dollar_amount at or below us_dollar_amount_max.
     */
    public Optional<Double> usDollarAmountMax() {
        return Optional.ofNullable(this.usDollarAmountMax);
    }

    /**
     * Return any records having a us_dollar_amount at or above us_dollar_amount_min.
     */
    public Optional<Double> usDollarAmountMin() {
        return Optional.ofNullable(this.usDollarAmountMin);
    }

    /**
     * Filter by Transaction Event. Multiple values are allowed, e.g.
     * `transaction_event_uid[]=MB2yqBrm3c4bUbou&amp;transaction_event_uid[]=N5tuy12zZzB9bftb`.
     */
    public Optional<String> transactionEventUid() {
        return Optional.ofNullable(this.transactionEventUid);
    }

    /**
     * Filter by Transaction. Multiple values are allowed, e.g.
     * `transaction_uid[]=SMwKC1osz77DTEiu&amp;transaction_uid[]=f1UDvUVNnXTKtgxu`.
     */
    public Optional<String> transactionUid() {
        return Optional.ofNullable(this.transactionUid);
    }

    /**
     * Maximum number of items to retrieve. This filter is automatically applied with the default value if
     * not given.
     */
    public Optional<Long> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * Index of the items to start retrieving from
     */
    public Optional<Long> offset() {
        return Optional.ofNullable(this.offset);
    }

    public Optional<GetCustodialLineItemsSort> sort() {
        return Optional.ofNullable(this.sort);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Filter by Customer. Multiple values are allowed, e.g.
     * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
     */
    public GetCustodialLineItemsRequest withCustomerUid(@Nullable String customerUid) {
        this.customerUid = customerUid;
        return this;
    }


    public GetCustodialLineItemsRequest withCustodialAccountUid(@Nullable String custodialAccountUid) {
        this.custodialAccountUid = custodialAccountUid;
        return this;
    }


    /**
     * Filter by status. Multiple values are allowed, e.g. `status[]=pending&amp;status[]=settled`.
     */
    public GetCustodialLineItemsRequest withStatus(@Nullable GetCustodialLineItemsQueryParamStatus status) {
        this.status = status;
        return this;
    }


    /**
     * Return any records having a us_dollar_amount at or below us_dollar_amount_max.
     */
    public GetCustodialLineItemsRequest withUsDollarAmountMax(@Nullable Double usDollarAmountMax) {
        this.usDollarAmountMax = usDollarAmountMax;
        return this;
    }


    /**
     * Return any records having a us_dollar_amount at or above us_dollar_amount_min.
     */
    public GetCustodialLineItemsRequest withUsDollarAmountMin(@Nullable Double usDollarAmountMin) {
        this.usDollarAmountMin = usDollarAmountMin;
        return this;
    }


    /**
     * Filter by Transaction Event. Multiple values are allowed, e.g.
     * `transaction_event_uid[]=MB2yqBrm3c4bUbou&amp;transaction_event_uid[]=N5tuy12zZzB9bftb`.
     */
    public GetCustodialLineItemsRequest withTransactionEventUid(@Nullable String transactionEventUid) {
        this.transactionEventUid = transactionEventUid;
        return this;
    }


    /**
     * Filter by Transaction. Multiple values are allowed, e.g.
     * `transaction_uid[]=SMwKC1osz77DTEiu&amp;transaction_uid[]=f1UDvUVNnXTKtgxu`.
     */
    public GetCustodialLineItemsRequest withTransactionUid(@Nullable String transactionUid) {
        this.transactionUid = transactionUid;
        return this;
    }


    /**
     * Maximum number of items to retrieve. This filter is automatically applied with the default value if
     * not given.
     */
    public GetCustodialLineItemsRequest withLimit(@Nullable Long limit) {
        this.limit = limit;
        return this;
    }


    /**
     * Index of the items to start retrieving from
     */
    public GetCustodialLineItemsRequest withOffset(@Nullable Long offset) {
        this.offset = offset;
        return this;
    }


    public GetCustodialLineItemsRequest withSort(@Nullable GetCustodialLineItemsSort sort) {
        this.sort = sort;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetCustodialLineItemsRequest other = (GetCustodialLineItemsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.customerUid, other.customerUid) &&
            Utils.enhancedDeepEquals(this.custodialAccountUid, other.custodialAccountUid) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.usDollarAmountMax, other.usDollarAmountMax) &&
            Utils.enhancedDeepEquals(this.usDollarAmountMin, other.usDollarAmountMin) &&
            Utils.enhancedDeepEquals(this.transactionEventUid, other.transactionEventUid) &&
            Utils.enhancedDeepEquals(this.transactionUid, other.transactionUid) &&
            Utils.enhancedDeepEquals(this.limit, other.limit) &&
            Utils.enhancedDeepEquals(this.offset, other.offset) &&
            Utils.enhancedDeepEquals(this.sort, other.sort);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            customerUid, custodialAccountUid, status,
            usDollarAmountMax, usDollarAmountMin, transactionEventUid,
            transactionUid, limit, offset,
            sort);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetCustodialLineItemsRequest.class,
                "customerUid", customerUid,
                "custodialAccountUid", custodialAccountUid,
                "status", status,
                "usDollarAmountMax", usDollarAmountMax,
                "usDollarAmountMin", usDollarAmountMin,
                "transactionEventUid", transactionEventUid,
                "transactionUid", transactionUid,
                "limit", limit,
                "offset", offset,
                "sort", sort);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String customerUid;

        private String custodialAccountUid;

        private GetCustodialLineItemsQueryParamStatus status;

        private Double usDollarAmountMax;

        private Double usDollarAmountMin;

        private String transactionEventUid;

        private String transactionUid;

        private Long limit;

        private Long offset;

        private GetCustodialLineItemsSort sort;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Filter by Customer. Multiple values are allowed, e.g.
         * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
         */
        public Builder customerUid(@Nullable String customerUid) {
            this.customerUid = customerUid;
            return this;
        }

        public Builder custodialAccountUid(@Nullable String custodialAccountUid) {
            this.custodialAccountUid = custodialAccountUid;
            return this;
        }

        /**
         * Filter by status. Multiple values are allowed, e.g. `status[]=pending&amp;status[]=settled`.
         */
        public Builder status(@Nullable GetCustodialLineItemsQueryParamStatus status) {
            this.status = status;
            return this;
        }

        /**
         * Return any records having a us_dollar_amount at or below us_dollar_amount_max.
         */
        public Builder usDollarAmountMax(@Nullable Double usDollarAmountMax) {
            this.usDollarAmountMax = usDollarAmountMax;
            return this;
        }

        /**
         * Return any records having a us_dollar_amount at or above us_dollar_amount_min.
         */
        public Builder usDollarAmountMin(@Nullable Double usDollarAmountMin) {
            this.usDollarAmountMin = usDollarAmountMin;
            return this;
        }

        /**
         * Filter by Transaction Event. Multiple values are allowed, e.g.
         * `transaction_event_uid[]=MB2yqBrm3c4bUbou&amp;transaction_event_uid[]=N5tuy12zZzB9bftb`.
         */
        public Builder transactionEventUid(@Nullable String transactionEventUid) {
            this.transactionEventUid = transactionEventUid;
            return this;
        }

        /**
         * Filter by Transaction. Multiple values are allowed, e.g.
         * `transaction_uid[]=SMwKC1osz77DTEiu&amp;transaction_uid[]=f1UDvUVNnXTKtgxu`.
         */
        public Builder transactionUid(@Nullable String transactionUid) {
            this.transactionUid = transactionUid;
            return this;
        }

        /**
         * Maximum number of items to retrieve. This filter is automatically applied with the default value if
         * not given.
         */
        public Builder limit(@Nullable Long limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Index of the items to start retrieving from
         */
        public Builder offset(@Nullable Long offset) {
            this.offset = offset;
            return this;
        }

        public Builder sort(@Nullable GetCustodialLineItemsSort sort) {
            this.sort = sort;
            return this;
        }

        public GetCustodialLineItemsRequest build() {
            return new GetCustodialLineItemsRequest(
                customerUid, custodialAccountUid, status,
                usDollarAmountMax, usDollarAmountMin, transactionEventUid,
                transactionUid, limit, offset,
                sort);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Limit =
                new LazySingletonValue<>(
                        "limit",
                        "100",
                        new TypeReference<Long>() {});

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Offset =
                new LazySingletonValue<>(
                        "offset",
                        "0",
                        new TypeReference<Long>() {});
    }
}
