/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetProductRequirementType
 * 
 * <p>The type of the response values for the requirement
 */
public class GetProductRequirementType {

    public static final GetProductRequirementType FIXED_LIST = new GetProductRequirementType("fixed_list");
    public static final GetProductRequirementType INTEGER_GREATER = new GetProductRequirementType("integer_greater");
    public static final GetProductRequirementType ORDERED_LIST = new GetProductRequirementType("ordered_list");
    public static final GetProductRequirementType NUMBER = new GetProductRequirementType("number");
    public static final GetProductRequirementType STRING = new GetProductRequirementType("string");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetProductRequirementType> values = createValuesMap();
    private static final Map<String, GetProductRequirementTypeEnum> enums = createEnumsMap();

    private final String value;

    private GetProductRequirementType(String value) {
        this.value = value;
    }

    /**
     * Returns a GetProductRequirementType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetProductRequirementType
     */ 
    @JsonCreator
    public static GetProductRequirementType of(String value) {
        synchronized (GetProductRequirementType.class) {
            return values.computeIfAbsent(value, v -> new GetProductRequirementType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetProductRequirementTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetProductRequirementType other = (GetProductRequirementType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetProductRequirementType [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetProductRequirementType[] values() {
        synchronized (GetProductRequirementType.class) {
            return values.values().toArray(new GetProductRequirementType[] {});
        }
    }

    private static final Map<String, GetProductRequirementType> createValuesMap() {
        Map<String, GetProductRequirementType> map = new LinkedHashMap<>();
        map.put("fixed_list", FIXED_LIST);
        map.put("integer_greater", INTEGER_GREATER);
        map.put("ordered_list", ORDERED_LIST);
        map.put("number", NUMBER);
        map.put("string", STRING);
        return map;
    }

    private static final Map<String, GetProductRequirementTypeEnum> createEnumsMap() {
        Map<String, GetProductRequirementTypeEnum> map = new HashMap<>();
        map.put("fixed_list", GetProductRequirementTypeEnum.FIXED_LIST);
        map.put("integer_greater", GetProductRequirementTypeEnum.INTEGER_GREATER);
        map.put("ordered_list", GetProductRequirementTypeEnum.ORDERED_LIST);
        map.put("number", GetProductRequirementTypeEnum.NUMBER);
        map.put("string", GetProductRequirementTypeEnum.STRING);
        return map;
    }
    
    
    public enum GetProductRequirementTypeEnum {

        FIXED_LIST("fixed_list"),
        INTEGER_GREATER("integer_greater"),
        ORDERED_LIST("ordered_list"),
        NUMBER("number"),
        STRING("string"),;

        private final String value;

        private GetProductRequirementTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

