/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GetProductRequiredField {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_type")
    private String customerType;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fields")
    private List<String> fields;

    @JsonCreator
    public GetProductRequiredField(
            @JsonProperty("customer_type") @Nullable String customerType,
            @JsonProperty("fields") @Nullable List<String> fields) {
        this.customerType = customerType;
        this.fields = fields;
    }
    
    public GetProductRequiredField() {
        this(null, null);
    }

    public Optional<String> customerType() {
        return Optional.ofNullable(this.customerType);
    }

    public Optional<List<String>> fields() {
        return Optional.ofNullable(this.fields);
    }

    public static Builder builder() {
        return new Builder();
    }


    public GetProductRequiredField withCustomerType(@Nullable String customerType) {
        this.customerType = customerType;
        return this;
    }


    public GetProductRequiredField withFields(@Nullable List<String> fields) {
        this.fields = fields;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetProductRequiredField other = (GetProductRequiredField) o;
        return 
            Utils.enhancedDeepEquals(this.customerType, other.customerType) &&
            Utils.enhancedDeepEquals(this.fields, other.fields);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            customerType, fields);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetProductRequiredField.class,
                "customerType", customerType,
                "fields", fields);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String customerType;

        private List<String> fields;

        private Builder() {
          // force use of static builder() method
        }

        public Builder customerType(@Nullable String customerType) {
            this.customerType = customerType;
            return this;
        }

        public Builder fields(@Nullable List<String> fields) {
            this.fields = fields;
            return this;
        }

        public GetProductRequiredField build() {
            return new GetProductRequiredField(
                customerType, fields);
        }

    }
}
