/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetReturnsRequestorTypeResponse
 * 
 * <p>Type of the customer requesting a return.
 */
public class GetReturnsRequestorTypeResponse {

    public static final GetReturnsRequestorTypeResponse CUSTOMER = new GetReturnsRequestorTypeResponse("customer");
    public static final GetReturnsRequestorTypeResponse SUBCLIENT = new GetReturnsRequestorTypeResponse("subclient");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetReturnsRequestorTypeResponse> values = createValuesMap();
    private static final Map<String, GetReturnsRequestorTypeResponseEnum> enums = createEnumsMap();

    private final String value;

    private GetReturnsRequestorTypeResponse(String value) {
        this.value = value;
    }

    /**
     * Returns a GetReturnsRequestorTypeResponse with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetReturnsRequestorTypeResponse
     */ 
    @JsonCreator
    public static GetReturnsRequestorTypeResponse of(String value) {
        synchronized (GetReturnsRequestorTypeResponse.class) {
            return values.computeIfAbsent(value, v -> new GetReturnsRequestorTypeResponse(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetReturnsRequestorTypeResponseEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetReturnsRequestorTypeResponse other = (GetReturnsRequestorTypeResponse) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetReturnsRequestorTypeResponse [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetReturnsRequestorTypeResponse[] values() {
        synchronized (GetReturnsRequestorTypeResponse.class) {
            return values.values().toArray(new GetReturnsRequestorTypeResponse[] {});
        }
    }

    private static final Map<String, GetReturnsRequestorTypeResponse> createValuesMap() {
        Map<String, GetReturnsRequestorTypeResponse> map = new LinkedHashMap<>();
        map.put("customer", CUSTOMER);
        map.put("subclient", SUBCLIENT);
        return map;
    }

    private static final Map<String, GetReturnsRequestorTypeResponseEnum> createEnumsMap() {
        Map<String, GetReturnsRequestorTypeResponseEnum> map = new HashMap<>();
        map.put("customer", GetReturnsRequestorTypeResponseEnum.CUSTOMER);
        map.put("subclient", GetReturnsRequestorTypeResponseEnum.SUBCLIENT);
        return map;
    }
    
    
    public enum GetReturnsRequestorTypeResponseEnum {

        CUSTOMER("customer"),
        SUBCLIENT("subclient"),;

        private final String value;

        private GetReturnsRequestorTypeResponseEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

