/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.SDKConfiguration;
import com.newline53.sdk.operations.GetReturns;
import com.newline53.sdk.utils.Headers;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.String;

public class GetReturnsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetReturnsRequest.Builder pojoBuilder;
    private GetReturnsRequest request;
    private boolean _setterCalled;

    public GetReturnsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetReturnsRequest.builder();
    }

    public GetReturnsRequestBuilder customerUid(@Nullable String customerUid) {
        this.pojoBuilder.customerUid(customerUid);
        this._setterCalled = true;
        return this;
    }

    public GetReturnsRequestBuilder requestorType(@Nullable QueryParamRequestorType requestorType) {
        this.pojoBuilder.requestorType(requestorType);
        this._setterCalled = true;
        return this;
    }

    private GetReturnsRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetReturnsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetReturnsResponse call() {
        RequestOperation<GetReturnsRequest, GetReturnsResponse> operation
              = new GetReturns.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
