/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetReturnsStatus
 * 
 * <p>A value indicating the overall status of the Return.
 */
public class GetReturnsStatus {

    public static final GetReturnsStatus CANCELED = new GetReturnsStatus("canceled");
    public static final GetReturnsStatus QUEUED = new GetReturnsStatus("queued");
    public static final GetReturnsStatus PENDING = new GetReturnsStatus("pending");
    public static final GetReturnsStatus SETTLED = new GetReturnsStatus("settled");
    public static final GetReturnsStatus FAILED = new GetReturnsStatus("failed");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetReturnsStatus> values = createValuesMap();
    private static final Map<String, GetReturnsStatusEnum> enums = createEnumsMap();

    private final String value;

    private GetReturnsStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a GetReturnsStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetReturnsStatus
     */ 
    @JsonCreator
    public static GetReturnsStatus of(String value) {
        synchronized (GetReturnsStatus.class) {
            return values.computeIfAbsent(value, v -> new GetReturnsStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetReturnsStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetReturnsStatus other = (GetReturnsStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetReturnsStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetReturnsStatus[] values() {
        synchronized (GetReturnsStatus.class) {
            return values.values().toArray(new GetReturnsStatus[] {});
        }
    }

    private static final Map<String, GetReturnsStatus> createValuesMap() {
        Map<String, GetReturnsStatus> map = new LinkedHashMap<>();
        map.put("canceled", CANCELED);
        map.put("queued", QUEUED);
        map.put("pending", PENDING);
        map.put("settled", SETTLED);
        map.put("failed", FAILED);
        return map;
    }

    private static final Map<String, GetReturnsStatusEnum> createEnumsMap() {
        Map<String, GetReturnsStatusEnum> map = new HashMap<>();
        map.put("canceled", GetReturnsStatusEnum.CANCELED);
        map.put("queued", GetReturnsStatusEnum.QUEUED);
        map.put("pending", GetReturnsStatusEnum.PENDING);
        map.put("settled", GetReturnsStatusEnum.SETTLED);
        map.put("failed", GetReturnsStatusEnum.FAILED);
        return map;
    }
    
    
    public enum GetReturnsStatusEnum {

        CANCELED("canceled"),
        QUEUED("queued"),
        PENDING("pending"),
        SETTLED("settled"),
        FAILED("failed"),;

        private final String value;

        private GetReturnsStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

