/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * GetSyntheticAccountAch
 * 
 * <p>Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external`
 * category.
 */
public class GetSyntheticAccountAch {
    /**
     * The type of ACH account
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_type")
    private GetSyntheticAccountAccountType accountType;

    /**
     * Name of the business or individual who owns the external account. Conditional maximum character
     * length: for all newline supported SEC codes other than CIE, the counterparty_name can be 22
     * characters. For CIE SEC codes, the counterparty_name can be up to 15 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_name")
    private String counterpartyName;

    @JsonCreator
    public GetSyntheticAccountAch(
            @JsonProperty("account_type") @Nullable GetSyntheticAccountAccountType accountType,
            @JsonProperty("counterparty_name") @Nullable String counterpartyName) {
        this.accountType = accountType;
        this.counterpartyName = counterpartyName;
    }
    
    public GetSyntheticAccountAch() {
        this(null, null);
    }

    /**
     * The type of ACH account
     */
    public Optional<GetSyntheticAccountAccountType> accountType() {
        return Optional.ofNullable(this.accountType);
    }

    /**
     * Name of the business or individual who owns the external account. Conditional maximum character
     * length: for all newline supported SEC codes other than CIE, the counterparty_name can be 22
     * characters. For CIE SEC codes, the counterparty_name can be up to 15 characters.
     */
    public Optional<String> counterpartyName() {
        return Optional.ofNullable(this.counterpartyName);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The type of ACH account
     */
    public GetSyntheticAccountAch withAccountType(@Nullable GetSyntheticAccountAccountType accountType) {
        this.accountType = accountType;
        return this;
    }


    /**
     * Name of the business or individual who owns the external account. Conditional maximum character
     * length: for all newline supported SEC codes other than CIE, the counterparty_name can be 22
     * characters. For CIE SEC codes, the counterparty_name can be up to 15 characters.
     */
    public GetSyntheticAccountAch withCounterpartyName(@Nullable String counterpartyName) {
        this.counterpartyName = counterpartyName;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSyntheticAccountAch other = (GetSyntheticAccountAch) o;
        return 
            Utils.enhancedDeepEquals(this.accountType, other.accountType) &&
            Utils.enhancedDeepEquals(this.counterpartyName, other.counterpartyName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountType, counterpartyName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetSyntheticAccountAch.class,
                "accountType", accountType,
                "counterpartyName", counterpartyName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private GetSyntheticAccountAccountType accountType;

        private String counterpartyName;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The type of ACH account
         */
        public Builder accountType(@Nullable GetSyntheticAccountAccountType accountType) {
            this.accountType = accountType;
            return this;
        }

        /**
         * Name of the business or individual who owns the external account. Conditional maximum character
         * length: for all newline supported SEC codes other than CIE, the counterparty_name can be 22
         * characters. For CIE SEC codes, the counterparty_name can be up to 15 characters.
         */
        public Builder counterpartyName(@Nullable String counterpartyName) {
            this.counterpartyName = counterpartyName;
            return this;
        }

        public GetSyntheticAccountAch build() {
            return new GetSyntheticAccountAch(
                accountType, counterpartyName);
        }

    }
}
