/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetTransferSecCode
 * 
 * <p>Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
 * For more details, refer to our ACH guide's
 * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
 */
public class GetTransferSecCode {

    public static final GetTransferSecCode CCD = new GetTransferSecCode("CCD");
    public static final GetTransferSecCode CIE = new GetTransferSecCode("CIE");
    public static final GetTransferSecCode PPD = new GetTransferSecCode("PPD");
    public static final GetTransferSecCode TEL = new GetTransferSecCode("TEL");
    public static final GetTransferSecCode WEB = new GetTransferSecCode("WEB");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetTransferSecCode> values = createValuesMap();
    private static final Map<String, GetTransferSecCodeEnum> enums = createEnumsMap();

    private final String value;

    private GetTransferSecCode(String value) {
        this.value = value;
    }

    /**
     * Returns a GetTransferSecCode with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetTransferSecCode
     */ 
    @JsonCreator
    public static GetTransferSecCode of(String value) {
        synchronized (GetTransferSecCode.class) {
            return values.computeIfAbsent(value, v -> new GetTransferSecCode(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetTransferSecCodeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetTransferSecCode other = (GetTransferSecCode) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetTransferSecCode [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetTransferSecCode[] values() {
        synchronized (GetTransferSecCode.class) {
            return values.values().toArray(new GetTransferSecCode[] {});
        }
    }

    private static final Map<String, GetTransferSecCode> createValuesMap() {
        Map<String, GetTransferSecCode> map = new LinkedHashMap<>();
        map.put("CCD", CCD);
        map.put("CIE", CIE);
        map.put("PPD", PPD);
        map.put("TEL", TEL);
        map.put("WEB", WEB);
        return map;
    }

    private static final Map<String, GetTransferSecCodeEnum> createEnumsMap() {
        Map<String, GetTransferSecCodeEnum> map = new HashMap<>();
        map.put("CCD", GetTransferSecCodeEnum.CCD);
        map.put("CIE", GetTransferSecCodeEnum.CIE);
        map.put("PPD", GetTransferSecCodeEnum.PPD);
        map.put("TEL", GetTransferSecCodeEnum.TEL);
        map.put("WEB", GetTransferSecCodeEnum.WEB);
        return map;
    }
    
    
    public enum GetTransferSecCodeEnum {

        CCD("CCD"),
        CIE("CIE"),
        PPD("PPD"),
        TEL("TEL"),
        WEB("WEB"),;

        private final String value;

        private GetTransferSecCodeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

