/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * GetTransactionsAch
 * 
 * <p>ACH-specific information. Only present if the Transaction is an ACH. The optional `iat` object
 * within `ach` contains details for International ACH Transactions.
 * 
 * <p>It is only included if `iat_ach_display_enabled` is set to `true` for the program and the
 * transaction contains IAT data.
 */
public class GetTransactionsAch {
    /**
     * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
     * apostrophe, comma, period, dash allowed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originator_name")
    private String originatorName;

    /**
     * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
     * 
     * <p>Optional for the majority of cases. Required if the general liability account is configured with
     * multiple IDs. Whether optional or required, it will be validated if supplied.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_id")
    private String companyId;

    /**
     * An optional field to add customized information such as a customer code or internal reference
     * number. 1 to 10 characters. Alphanumeric.
     * 
     * <p>Also allows '.', ',', or '-'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_discretionary_data")
    private String companyDiscretionaryData;

    /**
     * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
     * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
     * Transaction Type of the resulting transaction record is of type: 'ach'.
     * 
     * <p>If no value is provided, the default value will be 'false'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prenote")
    private Boolean prenote;

    /**
     * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
     * For more details, refer to our ACH guide's
     * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sec_code")
    private GetTransactionsSecCode secCode;

    /**
     * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
     * default value populated in the NACHA file is for a single entry.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_type")
    private GetTransactionsPaymentType paymentType;

    /**
     * Description value that will appear in the bank statement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entry_description")
    private String entryDescription;

    /**
     * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
     * SAMEDAY
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_processing")
    private GetTransactionsServiceProcessing serviceProcessing;

    /**
     * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
     * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
     * the originating financial institution does not match the Newline format, then the raw value will be
     * returned.
     * 
     * <p>The Newline date format is YYYY-MM-DD
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("effective_entry_date")
    private String effectiveEntryDate;

    /**
     * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
     * characters depending on SEC code, alphanumeric.
     * 
     * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
     * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
     * can be up to 22 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id_number")
    private String idNumber;

    /**
     * ACH return code, pulled from the Return File
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ach_return_code")
    private String achReturnCode;

    /**
     * ACH return reason, pulled from the Return File
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ach_return_reason")
    private String achReturnReason;

    /**
     * Notification of Change (NOC) code, returned from the RDFI (Receiving Depository Financial
     * Institution).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("noc_code")
    private String nocCode;

    /**
     * Notification of Change (NOC) description, returned from the RDFI (Receiving Depository Financial
     * Institution).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("noc_reason")
    private String nocReason;

    /**
     * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transfer_trace_id")
    private String transferTraceId;

    /**
     * Routing Number of individual or business originating the ACH transfer.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originator_routing_number")
    private String originatorRoutingNumber;

    /**
     * Counterparty name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_name")
    private String counterpartyName;

    /**
     * International ACH Transaction (IAT) details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("iat")
    private GetTransactionsIat iat;

    @JsonCreator
    public GetTransactionsAch(
            @JsonProperty("originator_name") @Nullable String originatorName,
            @JsonProperty("company_id") @Nullable String companyId,
            @JsonProperty("company_discretionary_data") @Nullable String companyDiscretionaryData,
            @JsonProperty("prenote") @Nullable Boolean prenote,
            @JsonProperty("sec_code") @Nullable GetTransactionsSecCode secCode,
            @JsonProperty("payment_type") @Nullable GetTransactionsPaymentType paymentType,
            @JsonProperty("entry_description") @Nullable String entryDescription,
            @JsonProperty("service_processing") @Nullable GetTransactionsServiceProcessing serviceProcessing,
            @JsonProperty("effective_entry_date") @Nullable String effectiveEntryDate,
            @JsonProperty("id_number") @Nullable String idNumber,
            @JsonProperty("ach_return_code") @Nullable String achReturnCode,
            @JsonProperty("ach_return_reason") @Nullable String achReturnReason,
            @JsonProperty("noc_code") @Nullable String nocCode,
            @JsonProperty("noc_reason") @Nullable String nocReason,
            @JsonProperty("transfer_trace_id") @Nullable String transferTraceId,
            @JsonProperty("originator_routing_number") @Nullable String originatorRoutingNumber,
            @JsonProperty("counterparty_name") @Nullable String counterpartyName,
            @JsonProperty("iat") @Nullable GetTransactionsIat iat) {
        this.originatorName = originatorName;
        this.companyId = companyId;
        this.companyDiscretionaryData = companyDiscretionaryData;
        this.prenote = prenote;
        this.secCode = secCode;
        this.paymentType = paymentType;
        this.entryDescription = entryDescription;
        this.serviceProcessing = serviceProcessing;
        this.effectiveEntryDate = effectiveEntryDate;
        this.idNumber = idNumber;
        this.achReturnCode = achReturnCode;
        this.achReturnReason = achReturnReason;
        this.nocCode = nocCode;
        this.nocReason = nocReason;
        this.transferTraceId = transferTraceId;
        this.originatorRoutingNumber = originatorRoutingNumber;
        this.counterpartyName = counterpartyName;
        this.iat = iat;
    }
    
    public GetTransactionsAch() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null);
    }

    /**
     * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
     * apostrophe, comma, period, dash allowed.
     */
    public Optional<String> originatorName() {
        return Optional.ofNullable(this.originatorName);
    }

    /**
     * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
     * 
     * <p>Optional for the majority of cases. Required if the general liability account is configured with
     * multiple IDs. Whether optional or required, it will be validated if supplied.
     */
    public Optional<String> companyId() {
        return Optional.ofNullable(this.companyId);
    }

    /**
     * An optional field to add customized information such as a customer code or internal reference
     * number. 1 to 10 characters. Alphanumeric.
     * 
     * <p>Also allows '.', ',', or '-'.
     */
    public Optional<String> companyDiscretionaryData() {
        return Optional.ofNullable(this.companyDiscretionaryData);
    }

    /**
     * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
     * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
     * Transaction Type of the resulting transaction record is of type: 'ach'.
     * 
     * <p>If no value is provided, the default value will be 'false'.
     */
    public Optional<Boolean> prenote() {
        return Optional.ofNullable(this.prenote);
    }

    /**
     * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
     * For more details, refer to our ACH guide's
     * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
     */
    public Optional<GetTransactionsSecCode> secCode() {
        return Optional.ofNullable(this.secCode);
    }

    /**
     * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
     * default value populated in the NACHA file is for a single entry.
     */
    public Optional<GetTransactionsPaymentType> paymentType() {
        return Optional.ofNullable(this.paymentType);
    }

    /**
     * Description value that will appear in the bank statement.
     */
    public Optional<String> entryDescription() {
        return Optional.ofNullable(this.entryDescription);
    }

    /**
     * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
     * SAMEDAY
     */
    public Optional<GetTransactionsServiceProcessing> serviceProcessing() {
        return Optional.ofNullable(this.serviceProcessing);
    }

    /**
     * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
     * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
     * the originating financial institution does not match the Newline format, then the raw value will be
     * returned.
     * 
     * <p>The Newline date format is YYYY-MM-DD
     */
    public Optional<String> effectiveEntryDate() {
        return Optional.ofNullable(this.effectiveEntryDate);
    }

    /**
     * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
     * characters depending on SEC code, alphanumeric.
     * 
     * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
     * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
     * can be up to 22 characters.
     */
    public Optional<String> idNumber() {
        return Optional.ofNullable(this.idNumber);
    }

    /**
     * ACH return code, pulled from the Return File
     */
    public Optional<String> achReturnCode() {
        return Optional.ofNullable(this.achReturnCode);
    }

    /**
     * ACH return reason, pulled from the Return File
     */
    public Optional<String> achReturnReason() {
        return Optional.ofNullable(this.achReturnReason);
    }

    /**
     * Notification of Change (NOC) code, returned from the RDFI (Receiving Depository Financial
     * Institution).
     */
    public Optional<String> nocCode() {
        return Optional.ofNullable(this.nocCode);
    }

    /**
     * Notification of Change (NOC) description, returned from the RDFI (Receiving Depository Financial
     * Institution).
     */
    public Optional<String> nocReason() {
        return Optional.ofNullable(this.nocReason);
    }

    /**
     * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
     */
    public Optional<String> transferTraceId() {
        return Optional.ofNullable(this.transferTraceId);
    }

    /**
     * Routing Number of individual or business originating the ACH transfer.
     */
    public Optional<String> originatorRoutingNumber() {
        return Optional.ofNullable(this.originatorRoutingNumber);
    }

    /**
     * Counterparty name.
     */
    public Optional<String> counterpartyName() {
        return Optional.ofNullable(this.counterpartyName);
    }

    /**
     * International ACH Transaction (IAT) details.
     */
    public Optional<GetTransactionsIat> iat() {
        return Optional.ofNullable(this.iat);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
     * apostrophe, comma, period, dash allowed.
     */
    public GetTransactionsAch withOriginatorName(@Nullable String originatorName) {
        this.originatorName = originatorName;
        return this;
    }


    /**
     * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
     * 
     * <p>Optional for the majority of cases. Required if the general liability account is configured with
     * multiple IDs. Whether optional or required, it will be validated if supplied.
     */
    public GetTransactionsAch withCompanyId(@Nullable String companyId) {
        this.companyId = companyId;
        return this;
    }


    /**
     * An optional field to add customized information such as a customer code or internal reference
     * number. 1 to 10 characters. Alphanumeric.
     * 
     * <p>Also allows '.', ',', or '-'.
     */
    public GetTransactionsAch withCompanyDiscretionaryData(@Nullable String companyDiscretionaryData) {
        this.companyDiscretionaryData = companyDiscretionaryData;
        return this;
    }


    /**
     * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
     * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
     * Transaction Type of the resulting transaction record is of type: 'ach'.
     * 
     * <p>If no value is provided, the default value will be 'false'.
     */
    public GetTransactionsAch withPrenote(@Nullable Boolean prenote) {
        this.prenote = prenote;
        return this;
    }


    /**
     * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
     * For more details, refer to our ACH guide's
     * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
     */
    public GetTransactionsAch withSecCode(@Nullable GetTransactionsSecCode secCode) {
        this.secCode = secCode;
        return this;
    }


    /**
     * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
     * default value populated in the NACHA file is for a single entry.
     */
    public GetTransactionsAch withPaymentType(@Nullable GetTransactionsPaymentType paymentType) {
        this.paymentType = paymentType;
        return this;
    }


    /**
     * Description value that will appear in the bank statement.
     */
    public GetTransactionsAch withEntryDescription(@Nullable String entryDescription) {
        this.entryDescription = entryDescription;
        return this;
    }


    /**
     * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
     * SAMEDAY
     */
    public GetTransactionsAch withServiceProcessing(@Nullable GetTransactionsServiceProcessing serviceProcessing) {
        this.serviceProcessing = serviceProcessing;
        return this;
    }


    /**
     * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
     * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
     * the originating financial institution does not match the Newline format, then the raw value will be
     * returned.
     * 
     * <p>The Newline date format is YYYY-MM-DD
     */
    public GetTransactionsAch withEffectiveEntryDate(@Nullable String effectiveEntryDate) {
        this.effectiveEntryDate = effectiveEntryDate;
        return this;
    }


    /**
     * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
     * characters depending on SEC code, alphanumeric.
     * 
     * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
     * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
     * can be up to 22 characters.
     */
    public GetTransactionsAch withIdNumber(@Nullable String idNumber) {
        this.idNumber = idNumber;
        return this;
    }


    /**
     * ACH return code, pulled from the Return File
     */
    public GetTransactionsAch withAchReturnCode(@Nullable String achReturnCode) {
        this.achReturnCode = achReturnCode;
        return this;
    }


    /**
     * ACH return reason, pulled from the Return File
     */
    public GetTransactionsAch withAchReturnReason(@Nullable String achReturnReason) {
        this.achReturnReason = achReturnReason;
        return this;
    }


    /**
     * Notification of Change (NOC) code, returned from the RDFI (Receiving Depository Financial
     * Institution).
     */
    public GetTransactionsAch withNocCode(@Nullable String nocCode) {
        this.nocCode = nocCode;
        return this;
    }


    /**
     * Notification of Change (NOC) description, returned from the RDFI (Receiving Depository Financial
     * Institution).
     */
    public GetTransactionsAch withNocReason(@Nullable String nocReason) {
        this.nocReason = nocReason;
        return this;
    }


    /**
     * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
     */
    public GetTransactionsAch withTransferTraceId(@Nullable String transferTraceId) {
        this.transferTraceId = transferTraceId;
        return this;
    }


    /**
     * Routing Number of individual or business originating the ACH transfer.
     */
    public GetTransactionsAch withOriginatorRoutingNumber(@Nullable String originatorRoutingNumber) {
        this.originatorRoutingNumber = originatorRoutingNumber;
        return this;
    }


    /**
     * Counterparty name.
     */
    public GetTransactionsAch withCounterpartyName(@Nullable String counterpartyName) {
        this.counterpartyName = counterpartyName;
        return this;
    }


    /**
     * International ACH Transaction (IAT) details.
     */
    public GetTransactionsAch withIat(@Nullable GetTransactionsIat iat) {
        this.iat = iat;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransactionsAch other = (GetTransactionsAch) o;
        return 
            Utils.enhancedDeepEquals(this.originatorName, other.originatorName) &&
            Utils.enhancedDeepEquals(this.companyId, other.companyId) &&
            Utils.enhancedDeepEquals(this.companyDiscretionaryData, other.companyDiscretionaryData) &&
            Utils.enhancedDeepEquals(this.prenote, other.prenote) &&
            Utils.enhancedDeepEquals(this.secCode, other.secCode) &&
            Utils.enhancedDeepEquals(this.paymentType, other.paymentType) &&
            Utils.enhancedDeepEquals(this.entryDescription, other.entryDescription) &&
            Utils.enhancedDeepEquals(this.serviceProcessing, other.serviceProcessing) &&
            Utils.enhancedDeepEquals(this.effectiveEntryDate, other.effectiveEntryDate) &&
            Utils.enhancedDeepEquals(this.idNumber, other.idNumber) &&
            Utils.enhancedDeepEquals(this.achReturnCode, other.achReturnCode) &&
            Utils.enhancedDeepEquals(this.achReturnReason, other.achReturnReason) &&
            Utils.enhancedDeepEquals(this.nocCode, other.nocCode) &&
            Utils.enhancedDeepEquals(this.nocReason, other.nocReason) &&
            Utils.enhancedDeepEquals(this.transferTraceId, other.transferTraceId) &&
            Utils.enhancedDeepEquals(this.originatorRoutingNumber, other.originatorRoutingNumber) &&
            Utils.enhancedDeepEquals(this.counterpartyName, other.counterpartyName) &&
            Utils.enhancedDeepEquals(this.iat, other.iat);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            originatorName, companyId, companyDiscretionaryData,
            prenote, secCode, paymentType,
            entryDescription, serviceProcessing, effectiveEntryDate,
            idNumber, achReturnCode, achReturnReason,
            nocCode, nocReason, transferTraceId,
            originatorRoutingNumber, counterpartyName, iat);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTransactionsAch.class,
                "originatorName", originatorName,
                "companyId", companyId,
                "companyDiscretionaryData", companyDiscretionaryData,
                "prenote", prenote,
                "secCode", secCode,
                "paymentType", paymentType,
                "entryDescription", entryDescription,
                "serviceProcessing", serviceProcessing,
                "effectiveEntryDate", effectiveEntryDate,
                "idNumber", idNumber,
                "achReturnCode", achReturnCode,
                "achReturnReason", achReturnReason,
                "nocCode", nocCode,
                "nocReason", nocReason,
                "transferTraceId", transferTraceId,
                "originatorRoutingNumber", originatorRoutingNumber,
                "counterpartyName", counterpartyName,
                "iat", iat);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String originatorName;

        private String companyId;

        private String companyDiscretionaryData;

        private Boolean prenote;

        private GetTransactionsSecCode secCode;

        private GetTransactionsPaymentType paymentType;

        private String entryDescription;

        private GetTransactionsServiceProcessing serviceProcessing;

        private String effectiveEntryDate;

        private String idNumber;

        private String achReturnCode;

        private String achReturnReason;

        private String nocCode;

        private String nocReason;

        private String transferTraceId;

        private String originatorRoutingNumber;

        private String counterpartyName;

        private GetTransactionsIat iat;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
         * apostrophe, comma, period, dash allowed.
         */
        public Builder originatorName(@Nullable String originatorName) {
            this.originatorName = originatorName;
            return this;
        }

        /**
         * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
         * 
         * <p>Optional for the majority of cases. Required if the general liability account is configured with
         * multiple IDs. Whether optional or required, it will be validated if supplied.
         */
        public Builder companyId(@Nullable String companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * An optional field to add customized information such as a customer code or internal reference
         * number. 1 to 10 characters. Alphanumeric.
         * 
         * <p>Also allows '.', ',', or '-'.
         */
        public Builder companyDiscretionaryData(@Nullable String companyDiscretionaryData) {
            this.companyDiscretionaryData = companyDiscretionaryData;
            return this;
        }

        /**
         * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
         * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
         * Transaction Type of the resulting transaction record is of type: 'ach'.
         * 
         * <p>If no value is provided, the default value will be 'false'.
         */
        public Builder prenote(@Nullable Boolean prenote) {
            this.prenote = prenote;
            return this;
        }

        /**
         * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
         * For more details, refer to our ACH guide's
         * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
         */
        public Builder secCode(@Nullable GetTransactionsSecCode secCode) {
            this.secCode = secCode;
            return this;
        }

        /**
         * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
         * default value populated in the NACHA file is for a single entry.
         */
        public Builder paymentType(@Nullable GetTransactionsPaymentType paymentType) {
            this.paymentType = paymentType;
            return this;
        }

        /**
         * Description value that will appear in the bank statement.
         */
        public Builder entryDescription(@Nullable String entryDescription) {
            this.entryDescription = entryDescription;
            return this;
        }

        /**
         * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
         * SAMEDAY
         */
        public Builder serviceProcessing(@Nullable GetTransactionsServiceProcessing serviceProcessing) {
            this.serviceProcessing = serviceProcessing;
            return this;
        }

        /**
         * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
         * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
         * the originating financial institution does not match the Newline format, then the raw value will be
         * returned.
         * 
         * <p>The Newline date format is YYYY-MM-DD
         */
        public Builder effectiveEntryDate(@Nullable String effectiveEntryDate) {
            this.effectiveEntryDate = effectiveEntryDate;
            return this;
        }

        /**
         * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
         * characters depending on SEC code, alphanumeric.
         * 
         * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
         * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
         * can be up to 22 characters.
         */
        public Builder idNumber(@Nullable String idNumber) {
            this.idNumber = idNumber;
            return this;
        }

        /**
         * ACH return code, pulled from the Return File
         */
        public Builder achReturnCode(@Nullable String achReturnCode) {
            this.achReturnCode = achReturnCode;
            return this;
        }

        /**
         * ACH return reason, pulled from the Return File
         */
        public Builder achReturnReason(@Nullable String achReturnReason) {
            this.achReturnReason = achReturnReason;
            return this;
        }

        /**
         * Notification of Change (NOC) code, returned from the RDFI (Receiving Depository Financial
         * Institution).
         */
        public Builder nocCode(@Nullable String nocCode) {
            this.nocCode = nocCode;
            return this;
        }

        /**
         * Notification of Change (NOC) description, returned from the RDFI (Receiving Depository Financial
         * Institution).
         */
        public Builder nocReason(@Nullable String nocReason) {
            this.nocReason = nocReason;
            return this;
        }

        /**
         * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
         */
        public Builder transferTraceId(@Nullable String transferTraceId) {
            this.transferTraceId = transferTraceId;
            return this;
        }

        /**
         * Routing Number of individual or business originating the ACH transfer.
         */
        public Builder originatorRoutingNumber(@Nullable String originatorRoutingNumber) {
            this.originatorRoutingNumber = originatorRoutingNumber;
            return this;
        }

        /**
         * Counterparty name.
         */
        public Builder counterpartyName(@Nullable String counterpartyName) {
            this.counterpartyName = counterpartyName;
            return this;
        }

        /**
         * International ACH Transaction (IAT) details.
         */
        public Builder iat(@Nullable GetTransactionsIat iat) {
            this.iat = iat;
            return this;
        }

        public GetTransactionsAch build() {
            return new GetTransactionsAch(
                originatorName, companyId, companyDiscretionaryData,
                prenote, secCode, paymentType,
                entryDescription, serviceProcessing, effectiveEntryDate,
                idNumber, achReturnCode, achReturnReason,
                nocCode, nocReason, transferTraceId,
                originatorRoutingNumber, counterpartyName, iat);
        }

    }
}
