/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetTransferPaymentType
 * 
 * <p>Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
 * default value populated in the NACHA file is for a single entry.
 */
public class GetTransferPaymentType {

    public static final GetTransferPaymentType R = new GetTransferPaymentType("R");
    public static final GetTransferPaymentType S = new GetTransferPaymentType("S");
    public static final GetTransferPaymentType ST = new GetTransferPaymentType("ST");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetTransferPaymentType> values = createValuesMap();
    private static final Map<String, GetTransferPaymentTypeEnum> enums = createEnumsMap();

    private final String value;

    private GetTransferPaymentType(String value) {
        this.value = value;
    }

    /**
     * Returns a GetTransferPaymentType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetTransferPaymentType
     */ 
    @JsonCreator
    public static GetTransferPaymentType of(String value) {
        synchronized (GetTransferPaymentType.class) {
            return values.computeIfAbsent(value, v -> new GetTransferPaymentType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetTransferPaymentTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetTransferPaymentType other = (GetTransferPaymentType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetTransferPaymentType [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetTransferPaymentType[] values() {
        synchronized (GetTransferPaymentType.class) {
            return values.values().toArray(new GetTransferPaymentType[] {});
        }
    }

    private static final Map<String, GetTransferPaymentType> createValuesMap() {
        Map<String, GetTransferPaymentType> map = new LinkedHashMap<>();
        map.put("R", R);
        map.put("S", S);
        map.put("ST", ST);
        return map;
    }

    private static final Map<String, GetTransferPaymentTypeEnum> createEnumsMap() {
        Map<String, GetTransferPaymentTypeEnum> map = new HashMap<>();
        map.put("R", GetTransferPaymentTypeEnum.R);
        map.put("S", GetTransferPaymentTypeEnum.S);
        map.put("ST", GetTransferPaymentTypeEnum.ST);
        return map;
    }
    
    
    public enum GetTransferPaymentTypeEnum {

        R("R"),
        S("S"),
        ST("ST"),;

        private final String value;

        private GetTransferPaymentTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

