/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetTransactionEventsUidNetAsset
 * 
 * <p>Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed
 * the same (`neutral`) as a result of this Transaction Event. This value is determined by `type`.
 */
public class GetTransactionEventsUidNetAsset {

    public static final GetTransactionEventsUidNetAsset POSITIVE = new GetTransactionEventsUidNetAsset("positive");
    public static final GetTransactionEventsUidNetAsset NEGATIVE = new GetTransactionEventsUidNetAsset("negative");
    public static final GetTransactionEventsUidNetAsset NEUTRAL = new GetTransactionEventsUidNetAsset("neutral");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetTransactionEventsUidNetAsset> values = createValuesMap();
    private static final Map<String, GetTransactionEventsUidNetAssetEnum> enums = createEnumsMap();

    private final String value;

    private GetTransactionEventsUidNetAsset(String value) {
        this.value = value;
    }

    /**
     * Returns a GetTransactionEventsUidNetAsset with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetTransactionEventsUidNetAsset
     */ 
    @JsonCreator
    public static GetTransactionEventsUidNetAsset of(String value) {
        synchronized (GetTransactionEventsUidNetAsset.class) {
            return values.computeIfAbsent(value, v -> new GetTransactionEventsUidNetAsset(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetTransactionEventsUidNetAssetEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetTransactionEventsUidNetAsset other = (GetTransactionEventsUidNetAsset) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetTransactionEventsUidNetAsset [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetTransactionEventsUidNetAsset[] values() {
        synchronized (GetTransactionEventsUidNetAsset.class) {
            return values.values().toArray(new GetTransactionEventsUidNetAsset[] {});
        }
    }

    private static final Map<String, GetTransactionEventsUidNetAsset> createValuesMap() {
        Map<String, GetTransactionEventsUidNetAsset> map = new LinkedHashMap<>();
        map.put("positive", POSITIVE);
        map.put("negative", NEGATIVE);
        map.put("neutral", NEUTRAL);
        return map;
    }

    private static final Map<String, GetTransactionEventsUidNetAssetEnum> createEnumsMap() {
        Map<String, GetTransactionEventsUidNetAssetEnum> map = new HashMap<>();
        map.put("positive", GetTransactionEventsUidNetAssetEnum.POSITIVE);
        map.put("negative", GetTransactionEventsUidNetAssetEnum.NEGATIVE);
        map.put("neutral", GetTransactionEventsUidNetAssetEnum.NEUTRAL);
        return map;
    }
    
    
    public enum GetTransactionEventsUidNetAssetEnum {

        POSITIVE("positive"),
        NEGATIVE("negative"),
        NEUTRAL("neutral"),;

        private final String value;

        private GetTransactionEventsUidNetAssetEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

