/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetTransferStatus
 * 
 * <p>A value indicating the overall status of the Transfer.
 */
public class GetTransferStatus {

    public static final GetTransferStatus CANCELED = new GetTransferStatus("canceled");
    public static final GetTransferStatus QUEUED = new GetTransferStatus("queued");
    public static final GetTransferStatus PENDING = new GetTransferStatus("pending");
    public static final GetTransferStatus SETTLED = new GetTransferStatus("settled");
    public static final GetTransferStatus FAILED = new GetTransferStatus("failed");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetTransferStatus> values = createValuesMap();
    private static final Map<String, GetTransferStatusEnum> enums = createEnumsMap();

    private final String value;

    private GetTransferStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a GetTransferStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetTransferStatus
     */ 
    @JsonCreator
    public static GetTransferStatus of(String value) {
        synchronized (GetTransferStatus.class) {
            return values.computeIfAbsent(value, v -> new GetTransferStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetTransferStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetTransferStatus other = (GetTransferStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetTransferStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetTransferStatus[] values() {
        synchronized (GetTransferStatus.class) {
            return values.values().toArray(new GetTransferStatus[] {});
        }
    }

    private static final Map<String, GetTransferStatus> createValuesMap() {
        Map<String, GetTransferStatus> map = new LinkedHashMap<>();
        map.put("canceled", CANCELED);
        map.put("queued", QUEUED);
        map.put("pending", PENDING);
        map.put("settled", SETTLED);
        map.put("failed", FAILED);
        return map;
    }

    private static final Map<String, GetTransferStatusEnum> createEnumsMap() {
        Map<String, GetTransferStatusEnum> map = new HashMap<>();
        map.put("canceled", GetTransferStatusEnum.CANCELED);
        map.put("queued", GetTransferStatusEnum.QUEUED);
        map.put("pending", GetTransferStatusEnum.PENDING);
        map.put("settled", GetTransferStatusEnum.SETTLED);
        map.put("failed", GetTransferStatusEnum.FAILED);
        return map;
    }
    
    
    public enum GetTransferStatusEnum {

        CANCELED("canceled"),
        QUEUED("queued"),
        PENDING("pending"),
        SETTLED("settled"),
        FAILED("failed"),;

        private final String value;

        private GetTransferStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

