/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * GetTransferInstantPayment
 * 
 * <p>Instant payment information. Only present if the Transfer is an instant payment.
 */
public class GetTransferInstantPayment {
    /**
     * A message transmitted to the recipient bank. Can contain letters and numbers as well as '-', '_',
     * and spaces.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("memo")
    private JsonNullable<String> memo;

    @JsonCreator
    public GetTransferInstantPayment(
            @JsonProperty("memo") @Nullable JsonNullable<String> memo) {
        this.memo = Optional.ofNullable(memo)
            .orElse(JsonNullable.undefined());
    }
    
    public GetTransferInstantPayment() {
        this(null);
    }

    /**
     * A message transmitted to the recipient bank. Can contain letters and numbers as well as '-', '_',
     * and spaces.
     */
    public JsonNullable<String> memo() {
        return this.memo;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A message transmitted to the recipient bank. Can contain letters and numbers as well as '-', '_',
     * and spaces.
     */
    public GetTransferInstantPayment withMemo(@Nullable String memo) {
        this.memo = JsonNullable.of(memo);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransferInstantPayment other = (GetTransferInstantPayment) o;
        return 
            Utils.enhancedDeepEquals(this.memo, other.memo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            memo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTransferInstantPayment.class,
                "memo", memo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<String> memo;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A message transmitted to the recipient bank. Can contain letters and numbers as well as '-', '_',
         * and spaces.
         */
        public Builder memo(@Nullable String memo) {
            this.memo = JsonNullable.of(memo);
            return this;
        }

        public GetTransferInstantPayment build() {
            return new GetTransferInstantPayment(
                memo);
        }

    }
}
