/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetTransactionsAuthorizationStatus
 * 
 * <p>A value indicating the current state of authorization for this transaction.
 */
public class GetTransactionsAuthorizationStatus {

    public static final GetTransactionsAuthorizationStatus AUTO_APPROVED = new GetTransactionsAuthorizationStatus("auto_approved");
    public static final GetTransactionsAuthorizationStatus AUTO_DENIED = new GetTransactionsAuthorizationStatus("auto_denied");
    public static final GetTransactionsAuthorizationStatus CLIENT_APPROVAL_PENDING = new GetTransactionsAuthorizationStatus("client_approval_pending");
    public static final GetTransactionsAuthorizationStatus CLIENT_APPROVED = new GetTransactionsAuthorizationStatus("client_approved");
    public static final GetTransactionsAuthorizationStatus CLIENT_DENIED = new GetTransactionsAuthorizationStatus("client_denied");
    public static final GetTransactionsAuthorizationStatus CLIENT_UNANSWERED_AUTO_APPROVED = new GetTransactionsAuthorizationStatus("client_unanswered_auto_approved");
    public static final GetTransactionsAuthorizationStatus CLIENT_UNANSWERED_AUTO_DENIED = new GetTransactionsAuthorizationStatus("client_unanswered_auto_denied");
    public static final GetTransactionsAuthorizationStatus CREATED = new GetTransactionsAuthorizationStatus("created");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetTransactionsAuthorizationStatus> values = createValuesMap();
    private static final Map<String, GetTransactionsAuthorizationStatusEnum> enums = createEnumsMap();

    private final String value;

    private GetTransactionsAuthorizationStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a GetTransactionsAuthorizationStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetTransactionsAuthorizationStatus
     */ 
    @JsonCreator
    public static GetTransactionsAuthorizationStatus of(String value) {
        synchronized (GetTransactionsAuthorizationStatus.class) {
            return values.computeIfAbsent(value, v -> new GetTransactionsAuthorizationStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetTransactionsAuthorizationStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetTransactionsAuthorizationStatus other = (GetTransactionsAuthorizationStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetTransactionsAuthorizationStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetTransactionsAuthorizationStatus[] values() {
        synchronized (GetTransactionsAuthorizationStatus.class) {
            return values.values().toArray(new GetTransactionsAuthorizationStatus[] {});
        }
    }

    private static final Map<String, GetTransactionsAuthorizationStatus> createValuesMap() {
        Map<String, GetTransactionsAuthorizationStatus> map = new LinkedHashMap<>();
        map.put("auto_approved", AUTO_APPROVED);
        map.put("auto_denied", AUTO_DENIED);
        map.put("client_approval_pending", CLIENT_APPROVAL_PENDING);
        map.put("client_approved", CLIENT_APPROVED);
        map.put("client_denied", CLIENT_DENIED);
        map.put("client_unanswered_auto_approved", CLIENT_UNANSWERED_AUTO_APPROVED);
        map.put("client_unanswered_auto_denied", CLIENT_UNANSWERED_AUTO_DENIED);
        map.put("created", CREATED);
        return map;
    }

    private static final Map<String, GetTransactionsAuthorizationStatusEnum> createEnumsMap() {
        Map<String, GetTransactionsAuthorizationStatusEnum> map = new HashMap<>();
        map.put("auto_approved", GetTransactionsAuthorizationStatusEnum.AUTO_APPROVED);
        map.put("auto_denied", GetTransactionsAuthorizationStatusEnum.AUTO_DENIED);
        map.put("client_approval_pending", GetTransactionsAuthorizationStatusEnum.CLIENT_APPROVAL_PENDING);
        map.put("client_approved", GetTransactionsAuthorizationStatusEnum.CLIENT_APPROVED);
        map.put("client_denied", GetTransactionsAuthorizationStatusEnum.CLIENT_DENIED);
        map.put("client_unanswered_auto_approved", GetTransactionsAuthorizationStatusEnum.CLIENT_UNANSWERED_AUTO_APPROVED);
        map.put("client_unanswered_auto_denied", GetTransactionsAuthorizationStatusEnum.CLIENT_UNANSWERED_AUTO_DENIED);
        map.put("created", GetTransactionsAuthorizationStatusEnum.CREATED);
        return map;
    }
    
    
    public enum GetTransactionsAuthorizationStatusEnum {

        AUTO_APPROVED("auto_approved"),
        AUTO_DENIED("auto_denied"),
        CLIENT_APPROVAL_PENDING("client_approval_pending"),
        CLIENT_APPROVED("client_approved"),
        CLIENT_DENIED("client_denied"),
        CLIENT_UNANSWERED_AUTO_APPROVED("client_unanswered_auto_approved"),
        CLIENT_UNANSWERED_AUTO_DENIED("client_unanswered_auto_denied"),
        CREATED("created"),;

        private final String value;

        private GetTransactionsAuthorizationStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

