/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * GetTransactionsInstantPayment
 * 
 * <p>Instant payment information. Only present if the Transaction is an instant payment.
 */
public class GetTransactionsInstantPayment {
    /**
     * For newline initiated instant payments, a unique newline trace ID assigned to the transaction. For
     * externally initiated instant payments, a unique transaction ID assigned by the network facilitating
     * the instant payment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("network_transaction_id")
    private String networkTransactionId;

    /**
     * The network on which the instant payment was executed
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("network")
    private String network;

    /**
     * A code indicating failure reason. It will only appear if transaction status is `failed`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("failure_code")
    private String failureCode;

    /**
     * A description of why the transaction failed. It will only appear if transaction status is `failed`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("failure_reason")
    private String failureReason;

    /**
     * Name of the business or individual who owns the counterparty Account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_name")
    private String counterpartyName;

    /**
     * Name of the financial institution where the counterparty account is held.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_bank_name")
    private String counterpartyBankName;

    /**
     * The routing number associated with the counterparty bank account.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_bank_routing_number")
    private String counterpartyBankRoutingNumber;

    /**
     * Last four digits of counterparty account number
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_account_number_last_four")
    private String counterpartyAccountNumberLastFour;

    /**
     * An originator-defined value. For RTP transactions, this will be the End-to-End ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_id")
    private String paymentId;

    /**
     * This field is currently always null.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("original_end_to_end_id")
    private JsonNullable<String> originalEndToEndId;

    /**
     * Name of the initiating counterparty. Deprecated in favor of `initiating_party_name`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transmitter_name")
    private String transmitterName;

    /**
     * Name of the initiating counterparty.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("initiating_party_name")
    private String initiatingPartyName;

    /**
     * Name and address of the Transmitter.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("instant_payment_transmitter")
    private GetTransactionsInstantPaymentTransmitter instantPaymentTransmitter;

    /**
     * Address of the financial institution where the external account is held.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("counterparty_bank_address")
    private JsonNullable<GetTransactionsInstantPaymentCounterpartyBankAddress> counterpartyBankAddress;

    @JsonCreator
    public GetTransactionsInstantPayment(
            @JsonProperty("network_transaction_id") @Nullable String networkTransactionId,
            @JsonProperty("network") @Nullable String network,
            @JsonProperty("failure_code") @Nullable String failureCode,
            @JsonProperty("failure_reason") @Nullable String failureReason,
            @JsonProperty("counterparty_name") @Nullable String counterpartyName,
            @JsonProperty("counterparty_bank_name") @Nullable String counterpartyBankName,
            @JsonProperty("counterparty_bank_routing_number") @Nullable String counterpartyBankRoutingNumber,
            @JsonProperty("counterparty_account_number_last_four") @Nullable String counterpartyAccountNumberLastFour,
            @JsonProperty("payment_id") @Nullable String paymentId,
            @JsonProperty("original_end_to_end_id") @Nullable JsonNullable<String> originalEndToEndId,
            @JsonProperty("transmitter_name") @Nullable String transmitterName,
            @JsonProperty("initiating_party_name") @Nullable String initiatingPartyName,
            @JsonProperty("instant_payment_transmitter") @Nullable GetTransactionsInstantPaymentTransmitter instantPaymentTransmitter,
            @JsonProperty("counterparty_bank_address") @Nullable JsonNullable<GetTransactionsInstantPaymentCounterpartyBankAddress> counterpartyBankAddress) {
        this.networkTransactionId = networkTransactionId;
        this.network = network;
        this.failureCode = failureCode;
        this.failureReason = failureReason;
        this.counterpartyName = counterpartyName;
        this.counterpartyBankName = counterpartyBankName;
        this.counterpartyBankRoutingNumber = counterpartyBankRoutingNumber;
        this.counterpartyAccountNumberLastFour = counterpartyAccountNumberLastFour;
        this.paymentId = paymentId;
        this.originalEndToEndId = Optional.ofNullable(originalEndToEndId)
            .orElse(JsonNullable.undefined());
        this.transmitterName = transmitterName;
        this.initiatingPartyName = initiatingPartyName;
        this.instantPaymentTransmitter = instantPaymentTransmitter;
        this.counterpartyBankAddress = Optional.ofNullable(counterpartyBankAddress)
            .orElse(JsonNullable.undefined());
    }
    
    public GetTransactionsInstantPayment() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null);
    }

    /**
     * For newline initiated instant payments, a unique newline trace ID assigned to the transaction. For
     * externally initiated instant payments, a unique transaction ID assigned by the network facilitating
     * the instant payment.
     */
    public Optional<String> networkTransactionId() {
        return Optional.ofNullable(this.networkTransactionId);
    }

    /**
     * The network on which the instant payment was executed
     */
    public Optional<String> network() {
        return Optional.ofNullable(this.network);
    }

    /**
     * A code indicating failure reason. It will only appear if transaction status is `failed`
     */
    public Optional<String> failureCode() {
        return Optional.ofNullable(this.failureCode);
    }

    /**
     * A description of why the transaction failed. It will only appear if transaction status is `failed`
     */
    public Optional<String> failureReason() {
        return Optional.ofNullable(this.failureReason);
    }

    /**
     * Name of the business or individual who owns the counterparty Account.
     */
    public Optional<String> counterpartyName() {
        return Optional.ofNullable(this.counterpartyName);
    }

    /**
     * Name of the financial institution where the counterparty account is held.
     */
    public Optional<String> counterpartyBankName() {
        return Optional.ofNullable(this.counterpartyBankName);
    }

    /**
     * The routing number associated with the counterparty bank account.
     */
    public Optional<String> counterpartyBankRoutingNumber() {
        return Optional.ofNullable(this.counterpartyBankRoutingNumber);
    }

    /**
     * Last four digits of counterparty account number
     */
    public Optional<String> counterpartyAccountNumberLastFour() {
        return Optional.ofNullable(this.counterpartyAccountNumberLastFour);
    }

    /**
     * An originator-defined value. For RTP transactions, this will be the End-to-End ID.
     */
    public Optional<String> paymentId() {
        return Optional.ofNullable(this.paymentId);
    }

    /**
     * This field is currently always null.
     */
    public JsonNullable<String> originalEndToEndId() {
        return this.originalEndToEndId;
    }

    /**
     * Name of the initiating counterparty. Deprecated in favor of `initiating_party_name`.
     */
    public Optional<String> transmitterName() {
        return Optional.ofNullable(this.transmitterName);
    }

    /**
     * Name of the initiating counterparty.
     */
    public Optional<String> initiatingPartyName() {
        return Optional.ofNullable(this.initiatingPartyName);
    }

    /**
     * Name and address of the Transmitter.
     */
    public Optional<GetTransactionsInstantPaymentTransmitter> instantPaymentTransmitter() {
        return Optional.ofNullable(this.instantPaymentTransmitter);
    }

    /**
     * Address of the financial institution where the external account is held.
     */
    public JsonNullable<GetTransactionsInstantPaymentCounterpartyBankAddress> counterpartyBankAddress() {
        return this.counterpartyBankAddress;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * For newline initiated instant payments, a unique newline trace ID assigned to the transaction. For
     * externally initiated instant payments, a unique transaction ID assigned by the network facilitating
     * the instant payment.
     */
    public GetTransactionsInstantPayment withNetworkTransactionId(@Nullable String networkTransactionId) {
        this.networkTransactionId = networkTransactionId;
        return this;
    }


    /**
     * The network on which the instant payment was executed
     */
    public GetTransactionsInstantPayment withNetwork(@Nullable String network) {
        this.network = network;
        return this;
    }


    /**
     * A code indicating failure reason. It will only appear if transaction status is `failed`
     */
    public GetTransactionsInstantPayment withFailureCode(@Nullable String failureCode) {
        this.failureCode = failureCode;
        return this;
    }


    /**
     * A description of why the transaction failed. It will only appear if transaction status is `failed`
     */
    public GetTransactionsInstantPayment withFailureReason(@Nullable String failureReason) {
        this.failureReason = failureReason;
        return this;
    }


    /**
     * Name of the business or individual who owns the counterparty Account.
     */
    public GetTransactionsInstantPayment withCounterpartyName(@Nullable String counterpartyName) {
        this.counterpartyName = counterpartyName;
        return this;
    }


    /**
     * Name of the financial institution where the counterparty account is held.
     */
    public GetTransactionsInstantPayment withCounterpartyBankName(@Nullable String counterpartyBankName) {
        this.counterpartyBankName = counterpartyBankName;
        return this;
    }


    /**
     * The routing number associated with the counterparty bank account.
     */
    public GetTransactionsInstantPayment withCounterpartyBankRoutingNumber(@Nullable String counterpartyBankRoutingNumber) {
        this.counterpartyBankRoutingNumber = counterpartyBankRoutingNumber;
        return this;
    }


    /**
     * Last four digits of counterparty account number
     */
    public GetTransactionsInstantPayment withCounterpartyAccountNumberLastFour(@Nullable String counterpartyAccountNumberLastFour) {
        this.counterpartyAccountNumberLastFour = counterpartyAccountNumberLastFour;
        return this;
    }


    /**
     * An originator-defined value. For RTP transactions, this will be the End-to-End ID.
     */
    public GetTransactionsInstantPayment withPaymentId(@Nullable String paymentId) {
        this.paymentId = paymentId;
        return this;
    }


    /**
     * This field is currently always null.
     */
    public GetTransactionsInstantPayment withOriginalEndToEndId(@Nullable String originalEndToEndId) {
        this.originalEndToEndId = JsonNullable.of(originalEndToEndId);
        return this;
    }


    /**
     * Name of the initiating counterparty. Deprecated in favor of `initiating_party_name`.
     */
    public GetTransactionsInstantPayment withTransmitterName(@Nullable String transmitterName) {
        this.transmitterName = transmitterName;
        return this;
    }


    /**
     * Name of the initiating counterparty.
     */
    public GetTransactionsInstantPayment withInitiatingPartyName(@Nullable String initiatingPartyName) {
        this.initiatingPartyName = initiatingPartyName;
        return this;
    }


    /**
     * Name and address of the Transmitter.
     */
    public GetTransactionsInstantPayment withInstantPaymentTransmitter(@Nullable GetTransactionsInstantPaymentTransmitter instantPaymentTransmitter) {
        this.instantPaymentTransmitter = instantPaymentTransmitter;
        return this;
    }


    /**
     * Address of the financial institution where the external account is held.
     */
    public GetTransactionsInstantPayment withCounterpartyBankAddress(@Nullable GetTransactionsInstantPaymentCounterpartyBankAddress counterpartyBankAddress) {
        this.counterpartyBankAddress = JsonNullable.of(counterpartyBankAddress);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransactionsInstantPayment other = (GetTransactionsInstantPayment) o;
        return 
            Utils.enhancedDeepEquals(this.networkTransactionId, other.networkTransactionId) &&
            Utils.enhancedDeepEquals(this.network, other.network) &&
            Utils.enhancedDeepEquals(this.failureCode, other.failureCode) &&
            Utils.enhancedDeepEquals(this.failureReason, other.failureReason) &&
            Utils.enhancedDeepEquals(this.counterpartyName, other.counterpartyName) &&
            Utils.enhancedDeepEquals(this.counterpartyBankName, other.counterpartyBankName) &&
            Utils.enhancedDeepEquals(this.counterpartyBankRoutingNumber, other.counterpartyBankRoutingNumber) &&
            Utils.enhancedDeepEquals(this.counterpartyAccountNumberLastFour, other.counterpartyAccountNumberLastFour) &&
            Utils.enhancedDeepEquals(this.paymentId, other.paymentId) &&
            Utils.enhancedDeepEquals(this.originalEndToEndId, other.originalEndToEndId) &&
            Utils.enhancedDeepEquals(this.transmitterName, other.transmitterName) &&
            Utils.enhancedDeepEquals(this.initiatingPartyName, other.initiatingPartyName) &&
            Utils.enhancedDeepEquals(this.instantPaymentTransmitter, other.instantPaymentTransmitter) &&
            Utils.enhancedDeepEquals(this.counterpartyBankAddress, other.counterpartyBankAddress);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            networkTransactionId, network, failureCode,
            failureReason, counterpartyName, counterpartyBankName,
            counterpartyBankRoutingNumber, counterpartyAccountNumberLastFour, paymentId,
            originalEndToEndId, transmitterName, initiatingPartyName,
            instantPaymentTransmitter, counterpartyBankAddress);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTransactionsInstantPayment.class,
                "networkTransactionId", networkTransactionId,
                "network", network,
                "failureCode", failureCode,
                "failureReason", failureReason,
                "counterpartyName", counterpartyName,
                "counterpartyBankName", counterpartyBankName,
                "counterpartyBankRoutingNumber", counterpartyBankRoutingNumber,
                "counterpartyAccountNumberLastFour", counterpartyAccountNumberLastFour,
                "paymentId", paymentId,
                "originalEndToEndId", originalEndToEndId,
                "transmitterName", transmitterName,
                "initiatingPartyName", initiatingPartyName,
                "instantPaymentTransmitter", instantPaymentTransmitter,
                "counterpartyBankAddress", counterpartyBankAddress);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String networkTransactionId;

        private String network;

        private String failureCode;

        private String failureReason;

        private String counterpartyName;

        private String counterpartyBankName;

        private String counterpartyBankRoutingNumber;

        private String counterpartyAccountNumberLastFour;

        private String paymentId;

        private JsonNullable<String> originalEndToEndId;

        private String transmitterName;

        private String initiatingPartyName;

        private GetTransactionsInstantPaymentTransmitter instantPaymentTransmitter;

        private JsonNullable<GetTransactionsInstantPaymentCounterpartyBankAddress> counterpartyBankAddress;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * For newline initiated instant payments, a unique newline trace ID assigned to the transaction. For
         * externally initiated instant payments, a unique transaction ID assigned by the network facilitating
         * the instant payment.
         */
        public Builder networkTransactionId(@Nullable String networkTransactionId) {
            this.networkTransactionId = networkTransactionId;
            return this;
        }

        /**
         * The network on which the instant payment was executed
         */
        public Builder network(@Nullable String network) {
            this.network = network;
            return this;
        }

        /**
         * A code indicating failure reason. It will only appear if transaction status is `failed`
         */
        public Builder failureCode(@Nullable String failureCode) {
            this.failureCode = failureCode;
            return this;
        }

        /**
         * A description of why the transaction failed. It will only appear if transaction status is `failed`
         */
        public Builder failureReason(@Nullable String failureReason) {
            this.failureReason = failureReason;
            return this;
        }

        /**
         * Name of the business or individual who owns the counterparty Account.
         */
        public Builder counterpartyName(@Nullable String counterpartyName) {
            this.counterpartyName = counterpartyName;
            return this;
        }

        /**
         * Name of the financial institution where the counterparty account is held.
         */
        public Builder counterpartyBankName(@Nullable String counterpartyBankName) {
            this.counterpartyBankName = counterpartyBankName;
            return this;
        }

        /**
         * The routing number associated with the counterparty bank account.
         */
        public Builder counterpartyBankRoutingNumber(@Nullable String counterpartyBankRoutingNumber) {
            this.counterpartyBankRoutingNumber = counterpartyBankRoutingNumber;
            return this;
        }

        /**
         * Last four digits of counterparty account number
         */
        public Builder counterpartyAccountNumberLastFour(@Nullable String counterpartyAccountNumberLastFour) {
            this.counterpartyAccountNumberLastFour = counterpartyAccountNumberLastFour;
            return this;
        }

        /**
         * An originator-defined value. For RTP transactions, this will be the End-to-End ID.
         */
        public Builder paymentId(@Nullable String paymentId) {
            this.paymentId = paymentId;
            return this;
        }

        /**
         * This field is currently always null.
         */
        public Builder originalEndToEndId(@Nullable String originalEndToEndId) {
            this.originalEndToEndId = JsonNullable.of(originalEndToEndId);
            return this;
        }

        /**
         * Name of the initiating counterparty. Deprecated in favor of `initiating_party_name`.
         */
        public Builder transmitterName(@Nullable String transmitterName) {
            this.transmitterName = transmitterName;
            return this;
        }

        /**
         * Name of the initiating counterparty.
         */
        public Builder initiatingPartyName(@Nullable String initiatingPartyName) {
            this.initiatingPartyName = initiatingPartyName;
            return this;
        }

        /**
         * Name and address of the Transmitter.
         */
        public Builder instantPaymentTransmitter(@Nullable GetTransactionsInstantPaymentTransmitter instantPaymentTransmitter) {
            this.instantPaymentTransmitter = instantPaymentTransmitter;
            return this;
        }

        /**
         * Address of the financial institution where the external account is held.
         */
        public Builder counterpartyBankAddress(@Nullable GetTransactionsInstantPaymentCounterpartyBankAddress counterpartyBankAddress) {
            this.counterpartyBankAddress = JsonNullable.of(counterpartyBankAddress);
            return this;
        }

        public GetTransactionsInstantPayment build() {
            return new GetTransactionsInstantPayment(
                networkTransactionId, network, failureCode,
                failureReason, counterpartyName, counterpartyBankName,
                counterpartyBankRoutingNumber, counterpartyAccountNumberLastFour, paymentId,
                originalEndToEndId, transmitterName, initiatingPartyName,
                instantPaymentTransmitter, counterpartyBankAddress);
        }

    }
}
