/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * GetTransferAch
 * 
 * <p>ACH information. Only present if the Transfer is an ACH.
 */
public class GetTransferAch {
    /**
     * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
     * apostrophe, comma, period, dash allowed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("originator_name")
    private String originatorName;

    /**
     * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
     * 
     * <p>Optional for the majority of cases. Required if the general liability account is configured with
     * multiple IDs. Whether optional or required, it will be validated if supplied.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_id")
    private String companyId;

    /**
     * An optional field to add customized information such as a customer code or internal reference
     * number. 1 to 10 characters. Alphanumeric.
     * 
     * <p>Also allows '.', ',', or '-'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_discretionary_data")
    private String companyDiscretionaryData;

    /**
     * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
     * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
     * Transaction Type of the resulting transaction record is of type: 'ach'.
     * 
     * <p>If no value is provided, the default value will be 'false'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prenote")
    private Boolean prenote;

    /**
     * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
     * For more details, refer to our ACH guide's
     * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sec_code")
    private GetTransferSecCode secCode;

    /**
     * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
     * default value populated in the NACHA file is for a single entry.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_type")
    private GetTransferPaymentType paymentType;

    /**
     * Description value that will appear in the bank statement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entry_description")
    private String entryDescription;

    /**
     * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
     * SAMEDAY
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_processing")
    private GetTransferServiceProcessing serviceProcessing;

    /**
     * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
     * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
     * the originating financial institution does not match the Newline format, then the raw value will be
     * returned.
     * 
     * <p>The Newline date format is YYYY-MM-DD
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("effective_entry_date")
    private String effectiveEntryDate;

    /**
     * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
     * characters depending on SEC code, alphanumeric.
     * 
     * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
     * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
     * can be up to 22 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id_number")
    private String idNumber;

    /**
     * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transfer_trace_id")
    private String transferTraceId;

    /**
     * Optional additional payment-related information, such as invoice numbers, originator/receiver
     * information, payment instructions, etc. Up to 80 characters. Optional for all newline supported SEC
     * codes other than TEL.
     * 
     * <p>Newline will reject the Transfer if an Addenda value is provided with SEC code TEL.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("addenda")
    private String addenda;

    @JsonCreator
    public GetTransferAch(
            @JsonProperty("originator_name") @Nullable String originatorName,
            @JsonProperty("company_id") @Nullable String companyId,
            @JsonProperty("company_discretionary_data") @Nullable String companyDiscretionaryData,
            @JsonProperty("prenote") @Nullable Boolean prenote,
            @JsonProperty("sec_code") @Nullable GetTransferSecCode secCode,
            @JsonProperty("payment_type") @Nullable GetTransferPaymentType paymentType,
            @JsonProperty("entry_description") @Nullable String entryDescription,
            @JsonProperty("service_processing") @Nullable GetTransferServiceProcessing serviceProcessing,
            @JsonProperty("effective_entry_date") @Nullable String effectiveEntryDate,
            @JsonProperty("id_number") @Nullable String idNumber,
            @JsonProperty("transfer_trace_id") @Nullable String transferTraceId,
            @JsonProperty("addenda") @Nullable String addenda) {
        this.originatorName = originatorName;
        this.companyId = companyId;
        this.companyDiscretionaryData = companyDiscretionaryData;
        this.prenote = prenote;
        this.secCode = secCode;
        this.paymentType = paymentType;
        this.entryDescription = entryDescription;
        this.serviceProcessing = serviceProcessing;
        this.effectiveEntryDate = effectiveEntryDate;
        this.idNumber = idNumber;
        this.transferTraceId = transferTraceId;
        this.addenda = addenda;
    }
    
    public GetTransferAch() {
        this(null, null, null,
            null, null, null,
            null, null, null,
            null, null, null);
    }

    /**
     * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
     * apostrophe, comma, period, dash allowed.
     */
    public Optional<String> originatorName() {
        return Optional.ofNullable(this.originatorName);
    }

    /**
     * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
     * 
     * <p>Optional for the majority of cases. Required if the general liability account is configured with
     * multiple IDs. Whether optional or required, it will be validated if supplied.
     */
    public Optional<String> companyId() {
        return Optional.ofNullable(this.companyId);
    }

    /**
     * An optional field to add customized information such as a customer code or internal reference
     * number. 1 to 10 characters. Alphanumeric.
     * 
     * <p>Also allows '.', ',', or '-'.
     */
    public Optional<String> companyDiscretionaryData() {
        return Optional.ofNullable(this.companyDiscretionaryData);
    }

    /**
     * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
     * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
     * Transaction Type of the resulting transaction record is of type: 'ach'.
     * 
     * <p>If no value is provided, the default value will be 'false'.
     */
    public Optional<Boolean> prenote() {
        return Optional.ofNullable(this.prenote);
    }

    /**
     * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
     * For more details, refer to our ACH guide's
     * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
     */
    public Optional<GetTransferSecCode> secCode() {
        return Optional.ofNullable(this.secCode);
    }

    /**
     * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
     * default value populated in the NACHA file is for a single entry.
     */
    public Optional<GetTransferPaymentType> paymentType() {
        return Optional.ofNullable(this.paymentType);
    }

    /**
     * Description value that will appear in the bank statement.
     */
    public Optional<String> entryDescription() {
        return Optional.ofNullable(this.entryDescription);
    }

    /**
     * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
     * SAMEDAY
     */
    public Optional<GetTransferServiceProcessing> serviceProcessing() {
        return Optional.ofNullable(this.serviceProcessing);
    }

    /**
     * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
     * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
     * the originating financial institution does not match the Newline format, then the raw value will be
     * returned.
     * 
     * <p>The Newline date format is YYYY-MM-DD
     */
    public Optional<String> effectiveEntryDate() {
        return Optional.ofNullable(this.effectiveEntryDate);
    }

    /**
     * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
     * characters depending on SEC code, alphanumeric.
     * 
     * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
     * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
     * can be up to 22 characters.
     */
    public Optional<String> idNumber() {
        return Optional.ofNullable(this.idNumber);
    }

    /**
     * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
     */
    public Optional<String> transferTraceId() {
        return Optional.ofNullable(this.transferTraceId);
    }

    /**
     * Optional additional payment-related information, such as invoice numbers, originator/receiver
     * information, payment instructions, etc. Up to 80 characters. Optional for all newline supported SEC
     * codes other than TEL.
     * 
     * <p>Newline will reject the Transfer if an Addenda value is provided with SEC code TEL.
     */
    public Optional<String> addenda() {
        return Optional.ofNullable(this.addenda);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
     * apostrophe, comma, period, dash allowed.
     */
    public GetTransferAch withOriginatorName(@Nullable String originatorName) {
        this.originatorName = originatorName;
        return this;
    }


    /**
     * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
     * 
     * <p>Optional for the majority of cases. Required if the general liability account is configured with
     * multiple IDs. Whether optional or required, it will be validated if supplied.
     */
    public GetTransferAch withCompanyId(@Nullable String companyId) {
        this.companyId = companyId;
        return this;
    }


    /**
     * An optional field to add customized information such as a customer code or internal reference
     * number. 1 to 10 characters. Alphanumeric.
     * 
     * <p>Also allows '.', ',', or '-'.
     */
    public GetTransferAch withCompanyDiscretionaryData(@Nullable String companyDiscretionaryData) {
        this.companyDiscretionaryData = companyDiscretionaryData;
        return this;
    }


    /**
     * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
     * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
     * Transaction Type of the resulting transaction record is of type: 'ach'.
     * 
     * <p>If no value is provided, the default value will be 'false'.
     */
    public GetTransferAch withPrenote(@Nullable Boolean prenote) {
        this.prenote = prenote;
        return this;
    }


    /**
     * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
     * For more details, refer to our ACH guide's
     * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
     */
    public GetTransferAch withSecCode(@Nullable GetTransferSecCode secCode) {
        this.secCode = secCode;
        return this;
    }


    /**
     * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
     * default value populated in the NACHA file is for a single entry.
     */
    public GetTransferAch withPaymentType(@Nullable GetTransferPaymentType paymentType) {
        this.paymentType = paymentType;
        return this;
    }


    /**
     * Description value that will appear in the bank statement.
     */
    public GetTransferAch withEntryDescription(@Nullable String entryDescription) {
        this.entryDescription = entryDescription;
        return this;
    }


    /**
     * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
     * SAMEDAY
     */
    public GetTransferAch withServiceProcessing(@Nullable GetTransferServiceProcessing serviceProcessing) {
        this.serviceProcessing = serviceProcessing;
        return this;
    }


    /**
     * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
     * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
     * the originating financial institution does not match the Newline format, then the raw value will be
     * returned.
     * 
     * <p>The Newline date format is YYYY-MM-DD
     */
    public GetTransferAch withEffectiveEntryDate(@Nullable String effectiveEntryDate) {
        this.effectiveEntryDate = effectiveEntryDate;
        return this;
    }


    /**
     * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
     * characters depending on SEC code, alphanumeric.
     * 
     * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
     * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
     * can be up to 22 characters.
     */
    public GetTransferAch withIdNumber(@Nullable String idNumber) {
        this.idNumber = idNumber;
        return this;
    }


    /**
     * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
     */
    public GetTransferAch withTransferTraceId(@Nullable String transferTraceId) {
        this.transferTraceId = transferTraceId;
        return this;
    }


    /**
     * Optional additional payment-related information, such as invoice numbers, originator/receiver
     * information, payment instructions, etc. Up to 80 characters. Optional for all newline supported SEC
     * codes other than TEL.
     * 
     * <p>Newline will reject the Transfer if an Addenda value is provided with SEC code TEL.
     */
    public GetTransferAch withAddenda(@Nullable String addenda) {
        this.addenda = addenda;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransferAch other = (GetTransferAch) o;
        return 
            Utils.enhancedDeepEquals(this.originatorName, other.originatorName) &&
            Utils.enhancedDeepEquals(this.companyId, other.companyId) &&
            Utils.enhancedDeepEquals(this.companyDiscretionaryData, other.companyDiscretionaryData) &&
            Utils.enhancedDeepEquals(this.prenote, other.prenote) &&
            Utils.enhancedDeepEquals(this.secCode, other.secCode) &&
            Utils.enhancedDeepEquals(this.paymentType, other.paymentType) &&
            Utils.enhancedDeepEquals(this.entryDescription, other.entryDescription) &&
            Utils.enhancedDeepEquals(this.serviceProcessing, other.serviceProcessing) &&
            Utils.enhancedDeepEquals(this.effectiveEntryDate, other.effectiveEntryDate) &&
            Utils.enhancedDeepEquals(this.idNumber, other.idNumber) &&
            Utils.enhancedDeepEquals(this.transferTraceId, other.transferTraceId) &&
            Utils.enhancedDeepEquals(this.addenda, other.addenda);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            originatorName, companyId, companyDiscretionaryData,
            prenote, secCode, paymentType,
            entryDescription, serviceProcessing, effectiveEntryDate,
            idNumber, transferTraceId, addenda);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTransferAch.class,
                "originatorName", originatorName,
                "companyId", companyId,
                "companyDiscretionaryData", companyDiscretionaryData,
                "prenote", prenote,
                "secCode", secCode,
                "paymentType", paymentType,
                "entryDescription", entryDescription,
                "serviceProcessing", serviceProcessing,
                "effectiveEntryDate", effectiveEntryDate,
                "idNumber", idNumber,
                "transferTraceId", transferTraceId,
                "addenda", addenda);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String originatorName;

        private String companyId;

        private String companyDiscretionaryData;

        private Boolean prenote;

        private GetTransferSecCode secCode;

        private GetTransferPaymentType paymentType;

        private String entryDescription;

        private GetTransferServiceProcessing serviceProcessing;

        private String effectiveEntryDate;

        private String idNumber;

        private String transferTraceId;

        private String addenda;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Individual or business originating the ACH transfer. 1 to 16 characters; letters, numbers,
         * apostrophe, comma, period, dash allowed.
         */
        public Builder originatorName(@Nullable String originatorName) {
            this.originatorName = originatorName;
            return this;
        }

        /**
         * ACH Company ID. 1 to 10 characters. Letters, numbers, apostrophe, comma, period, dash allowed.
         * 
         * <p>Optional for the majority of cases. Required if the general liability account is configured with
         * multiple IDs. Whether optional or required, it will be validated if supplied.
         */
        public Builder companyId(@Nullable String companyId) {
            this.companyId = companyId;
            return this;
        }

        /**
         * An optional field to add customized information such as a customer code or internal reference
         * number. 1 to 10 characters. Alphanumeric.
         * 
         * <p>Also allows '.', ',', or '-'.
         */
        public Builder companyDiscretionaryData(@Nullable String companyDiscretionaryData) {
            this.companyDiscretionaryData = companyDiscretionaryData;
            return this;
        }

        /**
         * If prenote is 'true', the amount of the transfer must be $0.00. Newline will infer credit_prenote or
         * debit_prenote based on the source and destination accounts. If prenote is 'true', then the resulting
         * Transaction Type of the resulting transaction record is of type: 'ach'.
         * 
         * <p>If no value is provided, the default value will be 'false'.
         */
        public Builder prenote(@Nullable Boolean prenote) {
            this.prenote = prenote;
            return this;
        }

        /**
         * Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
         * For more details, refer to our ACH guide's
         * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
         */
        public Builder secCode(@Nullable GetTransferSecCode secCode) {
            this.secCode = secCode;
            return this;
        }

        /**
         * Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the
         * default value populated in the NACHA file is for a single entry.
         */
        public Builder paymentType(@Nullable GetTransferPaymentType paymentType) {
            this.paymentType = paymentType;
            return this;
        }

        /**
         * Description value that will appear in the bank statement.
         */
        public Builder entryDescription(@Nullable String entryDescription) {
            this.entryDescription = entryDescription;
            return this;
        }

        /**
         * Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or
         * SAMEDAY
         */
        public Builder serviceProcessing(@Nullable GetTransferServiceProcessing serviceProcessing) {
            this.serviceProcessing = serviceProcessing;
            return this;
        }

        /**
         * The effective date when the transaction is scheduled to be processed. Date values provided cannot be
         * in the past or provided in the future beyond 30 days. For received returns, if the date provided by
         * the originating financial institution does not match the Newline format, then the raw value will be
         * returned.
         * 
         * <p>The Newline date format is YYYY-MM-DD
         */
        public Builder effectiveEntryDate(@Nullable String effectiveEntryDate) {
            this.effectiveEntryDate = effectiveEntryDate;
            return this;
        }

        /**
         * Unique identifier supplied by the originator of a transaction (e.g. invoice number). 1 to 22
         * characters depending on SEC code, alphanumeric.
         * 
         * <p>If the SEC value is anything other than CIE, then this is an optional field and can be up to 15
         * characters. If SEC value CIE is provided, then the ID number is mandatory, and the character length
         * can be up to 22 characters.
         */
        public Builder idNumber(@Nullable String idNumber) {
            this.idNumber = idNumber;
            return this;
        }

        /**
         * Trace ID to identify the transaction across Newline and Fifth Third Bank applications.
         */
        public Builder transferTraceId(@Nullable String transferTraceId) {
            this.transferTraceId = transferTraceId;
            return this;
        }

        /**
         * Optional additional payment-related information, such as invoice numbers, originator/receiver
         * information, payment instructions, etc. Up to 80 characters. Optional for all newline supported SEC
         * codes other than TEL.
         * 
         * <p>Newline will reject the Transfer if an Addenda value is provided with SEC code TEL.
         */
        public Builder addenda(@Nullable String addenda) {
            this.addenda = addenda;
            return this;
        }

        public GetTransferAch build() {
            return new GetTransferAch(
                originatorName, companyId, companyDiscretionaryData,
                prenote, secCode, paymentType,
                entryDescription, serviceProcessing, effectiveEntryDate,
                idNumber, transferTraceId, addenda);
        }

    }
}
