/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * GetTransactionsUidPurposeOfPayment
 * 
 * <p>An optional code supplied when an instant payment Transfer is initiated, indicating the kind of
 * transaction being sent. If supplied, it must be one of the approved codes listed below, otherwise
 * the Transfer is rejected. Omit the field or send an empty string to leave it unset; when unset it is
 * returned as an empty string.
 * 
 * <p>Only applies to Newline initiated instant payments; it is not populated for received instant
 * payments.
 */
public class GetTransactionsUidPurposeOfPayment {

    public static final GetTransactionsUidPurposeOfPayment NOWS = new GetTransactionsUidPurposeOfPayment("NOWS");
    public static final GetTransactionsUidPurposeOfPayment GDDS = new GetTransactionsUidPurposeOfPayment("GDDS");
    public static final GetTransactionsUidPurposeOfPayment SCVE = new GetTransactionsUidPurposeOfPayment("SCVE");
    public static final GetTransactionsUidPurposeOfPayment INSC = new GetTransactionsUidPurposeOfPayment("INSC");
    public static final GetTransactionsUidPurposeOfPayment INSM = new GetTransactionsUidPurposeOfPayment("INSM");
    public static final GetTransactionsUidPurposeOfPayment INVS = new GetTransactionsUidPurposeOfPayment("INVS");
    public static final GetTransactionsUidPurposeOfPayment PAYR = new GetTransactionsUidPurposeOfPayment("PAYR");
    public static final GetTransactionsUidPurposeOfPayment UBIL = new GetTransactionsUidPurposeOfPayment("UBIL");
    public static final GetTransactionsUidPurposeOfPayment PDEP = new GetTransactionsUidPurposeOfPayment("PDEP");
    public static final GetTransactionsUidPurposeOfPayment ACCT = new GetTransactionsUidPurposeOfPayment("ACCT");
    public static final GetTransactionsUidPurposeOfPayment CBLK = new GetTransactionsUidPurposeOfPayment("CBLK");
    public static final GetTransactionsUidPurposeOfPayment MP2_P = new GetTransactionsUidPurposeOfPayment("MP2P");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, GetTransactionsUidPurposeOfPayment> values = createValuesMap();
    private static final Map<String, GetTransactionsUidPurposeOfPaymentEnum> enums = createEnumsMap();

    private final String value;

    private GetTransactionsUidPurposeOfPayment(String value) {
        this.value = value;
    }

    /**
     * Returns a GetTransactionsUidPurposeOfPayment with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetTransactionsUidPurposeOfPayment
     */ 
    @JsonCreator
    public static GetTransactionsUidPurposeOfPayment of(String value) {
        synchronized (GetTransactionsUidPurposeOfPayment.class) {
            return values.computeIfAbsent(value, v -> new GetTransactionsUidPurposeOfPayment(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<GetTransactionsUidPurposeOfPaymentEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetTransactionsUidPurposeOfPayment other = (GetTransactionsUidPurposeOfPayment) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetTransactionsUidPurposeOfPayment [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetTransactionsUidPurposeOfPayment[] values() {
        synchronized (GetTransactionsUidPurposeOfPayment.class) {
            return values.values().toArray(new GetTransactionsUidPurposeOfPayment[] {});
        }
    }

    private static final Map<String, GetTransactionsUidPurposeOfPayment> createValuesMap() {
        Map<String, GetTransactionsUidPurposeOfPayment> map = new LinkedHashMap<>();
        map.put("NOWS", NOWS);
        map.put("GDDS", GDDS);
        map.put("SCVE", SCVE);
        map.put("INSC", INSC);
        map.put("INSM", INSM);
        map.put("INVS", INVS);
        map.put("PAYR", PAYR);
        map.put("UBIL", UBIL);
        map.put("PDEP", PDEP);
        map.put("ACCT", ACCT);
        map.put("CBLK", CBLK);
        map.put("MP2P", MP2_P);
        return map;
    }

    private static final Map<String, GetTransactionsUidPurposeOfPaymentEnum> createEnumsMap() {
        Map<String, GetTransactionsUidPurposeOfPaymentEnum> map = new HashMap<>();
        map.put("NOWS", GetTransactionsUidPurposeOfPaymentEnum.NOWS);
        map.put("GDDS", GetTransactionsUidPurposeOfPaymentEnum.GDDS);
        map.put("SCVE", GetTransactionsUidPurposeOfPaymentEnum.SCVE);
        map.put("INSC", GetTransactionsUidPurposeOfPaymentEnum.INSC);
        map.put("INSM", GetTransactionsUidPurposeOfPaymentEnum.INSM);
        map.put("INVS", GetTransactionsUidPurposeOfPaymentEnum.INVS);
        map.put("PAYR", GetTransactionsUidPurposeOfPaymentEnum.PAYR);
        map.put("UBIL", GetTransactionsUidPurposeOfPaymentEnum.UBIL);
        map.put("PDEP", GetTransactionsUidPurposeOfPaymentEnum.PDEP);
        map.put("ACCT", GetTransactionsUidPurposeOfPaymentEnum.ACCT);
        map.put("CBLK", GetTransactionsUidPurposeOfPaymentEnum.CBLK);
        map.put("MP2P", GetTransactionsUidPurposeOfPaymentEnum.MP2_P);
        return map;
    }
    
    
    public enum GetTransactionsUidPurposeOfPaymentEnum {

        NOWS("NOWS"),
        GDDS("GDDS"),
        SCVE("SCVE"),
        INSC("INSC"),
        INSM("INSM"),
        INVS("INVS"),
        PAYR("PAYR"),
        UBIL("UBIL"),
        PDEP("PDEP"),
        ACCT("ACCT"),
        CBLK("CBLK"),
        MP2_P("MP2P"),;

        private final String value;

        private GetTransactionsUidPurposeOfPaymentEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

