/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetTransactionsUidForeignCorrespondentBank {
    /**
     * The name of the Foreign Correspondent Bank when provided
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * A 2-digit code that identifies the type of ID in the "id_number" field when provided.
     * The Newline API supports the following values:
     * 
     * <p>- `"01"` - National Clearing System Number
     * - `"02"` - BIC Code
     * - `"03"` - IBAN
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id_number_qualifier")
    private String idNumberQualifier;

    /**
     * The bank identification number of the Foreign Correspondent Bank when provided
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id_number")
    private String idNumber;

    /**
     * A two-character alphabetic country code to identify the country in which the branch of the Foreign
     * Correspondent Bank is located when provided.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("branch_country_code")
    private String branchCountryCode;

    @JsonCreator
    public GetTransactionsUidForeignCorrespondentBank(
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("id_number_qualifier") @Nullable String idNumberQualifier,
            @JsonProperty("id_number") @Nullable String idNumber,
            @JsonProperty("branch_country_code") @Nullable String branchCountryCode) {
        this.name = name;
        this.idNumberQualifier = idNumberQualifier;
        this.idNumber = idNumber;
        this.branchCountryCode = branchCountryCode;
    }
    
    public GetTransactionsUidForeignCorrespondentBank() {
        this(null, null, null,
            null);
    }

    /**
     * The name of the Foreign Correspondent Bank when provided
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * A 2-digit code that identifies the type of ID in the "id_number" field when provided.
     * The Newline API supports the following values:
     * 
     * <p>- `"01"` - National Clearing System Number
     * - `"02"` - BIC Code
     * - `"03"` - IBAN
     */
    public Optional<String> idNumberQualifier() {
        return Optional.ofNullable(this.idNumberQualifier);
    }

    /**
     * The bank identification number of the Foreign Correspondent Bank when provided
     */
    public Optional<String> idNumber() {
        return Optional.ofNullable(this.idNumber);
    }

    /**
     * A two-character alphabetic country code to identify the country in which the branch of the Foreign
     * Correspondent Bank is located when provided.
     */
    public Optional<String> branchCountryCode() {
        return Optional.ofNullable(this.branchCountryCode);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the Foreign Correspondent Bank when provided
     */
    public GetTransactionsUidForeignCorrespondentBank withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * A 2-digit code that identifies the type of ID in the "id_number" field when provided.
     * The Newline API supports the following values:
     * 
     * <p>- `"01"` - National Clearing System Number
     * - `"02"` - BIC Code
     * - `"03"` - IBAN
     */
    public GetTransactionsUidForeignCorrespondentBank withIdNumberQualifier(@Nullable String idNumberQualifier) {
        this.idNumberQualifier = idNumberQualifier;
        return this;
    }


    /**
     * The bank identification number of the Foreign Correspondent Bank when provided
     */
    public GetTransactionsUidForeignCorrespondentBank withIdNumber(@Nullable String idNumber) {
        this.idNumber = idNumber;
        return this;
    }


    /**
     * A two-character alphabetic country code to identify the country in which the branch of the Foreign
     * Correspondent Bank is located when provided.
     */
    public GetTransactionsUidForeignCorrespondentBank withBranchCountryCode(@Nullable String branchCountryCode) {
        this.branchCountryCode = branchCountryCode;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransactionsUidForeignCorrespondentBank other = (GetTransactionsUidForeignCorrespondentBank) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.idNumberQualifier, other.idNumberQualifier) &&
            Utils.enhancedDeepEquals(this.idNumber, other.idNumber) &&
            Utils.enhancedDeepEquals(this.branchCountryCode, other.branchCountryCode);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, idNumberQualifier, idNumber,
            branchCountryCode);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTransactionsUidForeignCorrespondentBank.class,
                "name", name,
                "idNumberQualifier", idNumberQualifier,
                "idNumber", idNumber,
                "branchCountryCode", branchCountryCode);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String idNumberQualifier;

        private String idNumber;

        private String branchCountryCode;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the Foreign Correspondent Bank when provided
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * A 2-digit code that identifies the type of ID in the "id_number" field when provided.
         * The Newline API supports the following values:
         * 
         * <p>- `"01"` - National Clearing System Number
         * - `"02"` - BIC Code
         * - `"03"` - IBAN
         */
        public Builder idNumberQualifier(@Nullable String idNumberQualifier) {
            this.idNumberQualifier = idNumberQualifier;
            return this;
        }

        /**
         * The bank identification number of the Foreign Correspondent Bank when provided
         */
        public Builder idNumber(@Nullable String idNumber) {
            this.idNumber = idNumber;
            return this;
        }

        /**
         * A two-character alphabetic country code to identify the country in which the branch of the Foreign
         * Correspondent Bank is located when provided.
         */
        public Builder branchCountryCode(@Nullable String branchCountryCode) {
            this.branchCountryCode = branchCountryCode;
            return this;
        }

        public GetTransactionsUidForeignCorrespondentBank build() {
            return new GetTransactionsUidForeignCorrespondentBank(
                name, idNumberQualifier, idNumber,
                branchCountryCode);
        }

    }
}
