/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.SDKConfiguration;
import com.newline53.sdk.operations.GetVirtualReferenceNumbers;
import com.newline53.sdk.utils.Headers;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.String;

public class GetVirtualReferenceNumbersRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetVirtualReferenceNumbersRequest.Builder pojoBuilder;
    private GetVirtualReferenceNumbersRequest request;
    private boolean _setterCalled;

    public GetVirtualReferenceNumbersRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetVirtualReferenceNumbersRequest.builder();
    }

    public GetVirtualReferenceNumbersRequestBuilder instantPaymentRailRegistrationStatus(@Nullable QueryParamInstantPaymentRailRegistrationStatus instantPaymentRailRegistrationStatus) {
        this.pojoBuilder.instantPaymentRailRegistrationStatus(instantPaymentRailRegistrationStatus);
        this._setterCalled = true;
        return this;
    }

    public GetVirtualReferenceNumbersRequestBuilder status(@Nullable GetVirtualReferenceNumbersQueryParamStatus status) {
        this.pojoBuilder.status(status);
        this._setterCalled = true;
        return this;
    }

    public GetVirtualReferenceNumbersRequestBuilder syntheticAccountUid(@Nullable String syntheticAccountUid) {
        this.pojoBuilder.syntheticAccountUid(syntheticAccountUid);
        this._setterCalled = true;
        return this;
    }

    public GetVirtualReferenceNumbersRequestBuilder virtualReferenceNumber(@Nullable String virtualReferenceNumber) {
        this.pojoBuilder.virtualReferenceNumber(virtualReferenceNumber);
        this._setterCalled = true;
        return this;
    }

    private GetVirtualReferenceNumbersRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetVirtualReferenceNumbersRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetVirtualReferenceNumbersResponse call() {
        RequestOperation<GetVirtualReferenceNumbersRequest, GetVirtualReferenceNumbersResponse> operation
              = new GetVirtualReferenceNumbers.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
