/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class ListTransfersCurrentCancellationStatus {

    public static final ListTransfersCurrentCancellationStatus PENDING_CANCELLATION = new ListTransfersCurrentCancellationStatus("pending_cancellation");
    public static final ListTransfersCurrentCancellationStatus SUCCESSFUL_CANCELLATION = new ListTransfersCurrentCancellationStatus("successful_cancellation");
    public static final ListTransfersCurrentCancellationStatus FAILED_CANCELLATION = new ListTransfersCurrentCancellationStatus("failed_cancellation");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ListTransfersCurrentCancellationStatus> values = createValuesMap();
    private static final Map<String, ListTransfersCurrentCancellationStatusEnum> enums = createEnumsMap();

    private final String value;

    private ListTransfersCurrentCancellationStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a ListTransfersCurrentCancellationStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ListTransfersCurrentCancellationStatus
     */ 
    @JsonCreator
    public static ListTransfersCurrentCancellationStatus of(String value) {
        synchronized (ListTransfersCurrentCancellationStatus.class) {
            return values.computeIfAbsent(value, v -> new ListTransfersCurrentCancellationStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ListTransfersCurrentCancellationStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ListTransfersCurrentCancellationStatus other = (ListTransfersCurrentCancellationStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ListTransfersCurrentCancellationStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static ListTransfersCurrentCancellationStatus[] values() {
        synchronized (ListTransfersCurrentCancellationStatus.class) {
            return values.values().toArray(new ListTransfersCurrentCancellationStatus[] {});
        }
    }

    private static final Map<String, ListTransfersCurrentCancellationStatus> createValuesMap() {
        Map<String, ListTransfersCurrentCancellationStatus> map = new LinkedHashMap<>();
        map.put("pending_cancellation", PENDING_CANCELLATION);
        map.put("successful_cancellation", SUCCESSFUL_CANCELLATION);
        map.put("failed_cancellation", FAILED_CANCELLATION);
        return map;
    }

    private static final Map<String, ListTransfersCurrentCancellationStatusEnum> createEnumsMap() {
        Map<String, ListTransfersCurrentCancellationStatusEnum> map = new HashMap<>();
        map.put("pending_cancellation", ListTransfersCurrentCancellationStatusEnum.PENDING_CANCELLATION);
        map.put("successful_cancellation", ListTransfersCurrentCancellationStatusEnum.SUCCESSFUL_CANCELLATION);
        map.put("failed_cancellation", ListTransfersCurrentCancellationStatusEnum.FAILED_CANCELLATION);
        return map;
    }
    
    
    public enum ListTransfersCurrentCancellationStatusEnum {

        PENDING_CANCELLATION("pending_cancellation"),
        SUCCESSFUL_CANCELLATION("successful_cancellation"),
        FAILED_CANCELLATION("failed_cancellation"),;

        private final String value;

        private ListTransfersCurrentCancellationStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

