/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import com.newline53.sdk.utils.LazySingletonValue;
import com.newline53.sdk.utils.SpeakeasyMetadata;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class ListCustodialAccountsRequest {
    /**
     * Filter by Customer. Multiple values are allowed, e.g.
     * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=customer_uid")
    private String customerUid;

    /**
     * A unique, immutable id provided by the Client. Multiple values are allowed e.g.
     * `external_uid[]=uKxmLxUEiSj5h4M3&amp;external_uid[]=y9reyPMNEWuuYSC1`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=external_uid")
    private String externalUid;

    /**
     * Maximum number of items to retrieve. This filter is automatically applied with the default value if
     * not given.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    private Long limit;

    /**
     * Index of the items to start retrieving from
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    private Long offset;

    /**
     * Filter by liability or asset
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=liability")
    private Boolean liability;

    /**
     * Filter by type. Multiple values are allowed, e.g. `type[]=dda&amp;type[]=dda_cash_external`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")
    private ListCustodialAccountsQueryParamType type;

    @JsonCreator
    public ListCustodialAccountsRequest(
            @Nullable String customerUid,
            @Nullable String externalUid,
            @Nullable Long limit,
            @Nullable Long offset,
            @Nullable Boolean liability,
            @Nullable ListCustodialAccountsQueryParamType type) {
        this.customerUid = customerUid;
        this.externalUid = externalUid;
        this.limit = Optional.ofNullable(limit)
            .orElse(Builder._SINGLETON_VALUE_Limit.value());
        this.offset = Optional.ofNullable(offset)
            .orElse(Builder._SINGLETON_VALUE_Offset.value());
        this.liability = liability;
        this.type = type;
    }
    
    public ListCustodialAccountsRequest() {
        this(null, null, null,
            null, null, null);
    }

    /**
     * Filter by Customer. Multiple values are allowed, e.g.
     * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
     */
    public Optional<String> customerUid() {
        return Optional.ofNullable(this.customerUid);
    }

    /**
     * A unique, immutable id provided by the Client. Multiple values are allowed e.g.
     * `external_uid[]=uKxmLxUEiSj5h4M3&amp;external_uid[]=y9reyPMNEWuuYSC1`.
     */
    public Optional<String> externalUid() {
        return Optional.ofNullable(this.externalUid);
    }

    /**
     * Maximum number of items to retrieve. This filter is automatically applied with the default value if
     * not given.
     */
    public Optional<Long> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * Index of the items to start retrieving from
     */
    public Optional<Long> offset() {
        return Optional.ofNullable(this.offset);
    }

    /**
     * Filter by liability or asset
     */
    public Optional<Boolean> liability() {
        return Optional.ofNullable(this.liability);
    }

    /**
     * Filter by type. Multiple values are allowed, e.g. `type[]=dda&amp;type[]=dda_cash_external`.
     */
    public Optional<ListCustodialAccountsQueryParamType> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Filter by Customer. Multiple values are allowed, e.g.
     * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
     */
    public ListCustodialAccountsRequest withCustomerUid(@Nullable String customerUid) {
        this.customerUid = customerUid;
        return this;
    }


    /**
     * A unique, immutable id provided by the Client. Multiple values are allowed e.g.
     * `external_uid[]=uKxmLxUEiSj5h4M3&amp;external_uid[]=y9reyPMNEWuuYSC1`.
     */
    public ListCustodialAccountsRequest withExternalUid(@Nullable String externalUid) {
        this.externalUid = externalUid;
        return this;
    }


    /**
     * Maximum number of items to retrieve. This filter is automatically applied with the default value if
     * not given.
     */
    public ListCustodialAccountsRequest withLimit(@Nullable Long limit) {
        this.limit = limit;
        return this;
    }


    /**
     * Index of the items to start retrieving from
     */
    public ListCustodialAccountsRequest withOffset(@Nullable Long offset) {
        this.offset = offset;
        return this;
    }


    /**
     * Filter by liability or asset
     */
    public ListCustodialAccountsRequest withLiability(@Nullable Boolean liability) {
        this.liability = liability;
        return this;
    }


    /**
     * Filter by type. Multiple values are allowed, e.g. `type[]=dda&amp;type[]=dda_cash_external`.
     */
    public ListCustodialAccountsRequest withType(@Nullable ListCustodialAccountsQueryParamType type) {
        this.type = type;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListCustodialAccountsRequest other = (ListCustodialAccountsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.customerUid, other.customerUid) &&
            Utils.enhancedDeepEquals(this.externalUid, other.externalUid) &&
            Utils.enhancedDeepEquals(this.limit, other.limit) &&
            Utils.enhancedDeepEquals(this.offset, other.offset) &&
            Utils.enhancedDeepEquals(this.liability, other.liability) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            customerUid, externalUid, limit,
            offset, liability, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListCustodialAccountsRequest.class,
                "customerUid", customerUid,
                "externalUid", externalUid,
                "limit", limit,
                "offset", offset,
                "liability", liability,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String customerUid;

        private String externalUid;

        private Long limit;

        private Long offset;

        private Boolean liability;

        private ListCustodialAccountsQueryParamType type;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Filter by Customer. Multiple values are allowed, e.g.
         * `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
         */
        public Builder customerUid(@Nullable String customerUid) {
            this.customerUid = customerUid;
            return this;
        }

        /**
         * A unique, immutable id provided by the Client. Multiple values are allowed e.g.
         * `external_uid[]=uKxmLxUEiSj5h4M3&amp;external_uid[]=y9reyPMNEWuuYSC1`.
         */
        public Builder externalUid(@Nullable String externalUid) {
            this.externalUid = externalUid;
            return this;
        }

        /**
         * Maximum number of items to retrieve. This filter is automatically applied with the default value if
         * not given.
         */
        public Builder limit(@Nullable Long limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Index of the items to start retrieving from
         */
        public Builder offset(@Nullable Long offset) {
            this.offset = offset;
            return this;
        }

        /**
         * Filter by liability or asset
         */
        public Builder liability(@Nullable Boolean liability) {
            this.liability = liability;
            return this;
        }

        /**
         * Filter by type. Multiple values are allowed, e.g. `type[]=dda&amp;type[]=dda_cash_external`.
         */
        public Builder type(@Nullable ListCustodialAccountsQueryParamType type) {
            this.type = type;
            return this;
        }

        public ListCustodialAccountsRequest build() {
            return new ListCustodialAccountsRequest(
                customerUid, externalUid, limit,
                offset, liability, type);
        }


        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Limit =
                new LazySingletonValue<>(
                        "limit",
                        "100",
                        new TypeReference<Long>() {});

        private static final LazySingletonValue<Long> _SINGLETON_VALUE_Offset =
                new LazySingletonValue<>(
                        "offset",
                        "0",
                        new TypeReference<Long>() {});
    }
}
