/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.SDKConfiguration;
import com.newline53.sdk.operations.ListCustodialAccounts;
import com.newline53.sdk.utils.Headers;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nonnull;

public class ListCustodialAccountsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ListCustodialAccountsRequest request;

    public ListCustodialAccountsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListCustodialAccountsRequestBuilder request(@Nonnull ListCustodialAccountsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private ListCustodialAccountsRequest _buildRequest() {
        return this.request;
    }
    
    public ListCustodialAccountsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ListCustodialAccountsResponse call() {
        RequestOperation<ListCustodialAccountsRequest, ListCustodialAccountsResponse> operation
              = new ListCustodialAccounts.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
