/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * ListCustomerProductsResponseBody
 * 
 * <p>A list of Customer Products is returned
 */
public class ListCustomerProductsResponseBody {
    /**
     * Total count of items available to retrieve
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("total_count")
    private Long totalCount;

    /**
     * Number of items retrieved
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("count")
    private Long count;

    /**
     * Maximum number of items to retrieve
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("limit")
    private Long limit;

    /**
     * Index of the first item to retrieve
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offset")
    private Long offset;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private List<ListCustomerProductsData> data;

    @JsonCreator
    public ListCustomerProductsResponseBody(
            @JsonProperty("total_count") @Nullable Long totalCount,
            @JsonProperty("count") @Nullable Long count,
            @JsonProperty("limit") @Nullable Long limit,
            @JsonProperty("offset") @Nullable Long offset,
            @JsonProperty("data") @Nullable List<ListCustomerProductsData> data) {
        this.totalCount = totalCount;
        this.count = count;
        this.limit = limit;
        this.offset = offset;
        this.data = data;
    }
    
    public ListCustomerProductsResponseBody() {
        this(null, null, null,
            null, null);
    }

    /**
     * Total count of items available to retrieve
     */
    public Optional<Long> totalCount() {
        return Optional.ofNullable(this.totalCount);
    }

    /**
     * Number of items retrieved
     */
    public Optional<Long> count() {
        return Optional.ofNullable(this.count);
    }

    /**
     * Maximum number of items to retrieve
     */
    public Optional<Long> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * Index of the first item to retrieve
     */
    public Optional<Long> offset() {
        return Optional.ofNullable(this.offset);
    }

    public Optional<List<ListCustomerProductsData>> data() {
        return Optional.ofNullable(this.data);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Total count of items available to retrieve
     */
    public ListCustomerProductsResponseBody withTotalCount(@Nullable Long totalCount) {
        this.totalCount = totalCount;
        return this;
    }


    /**
     * Number of items retrieved
     */
    public ListCustomerProductsResponseBody withCount(@Nullable Long count) {
        this.count = count;
        return this;
    }


    /**
     * Maximum number of items to retrieve
     */
    public ListCustomerProductsResponseBody withLimit(@Nullable Long limit) {
        this.limit = limit;
        return this;
    }


    /**
     * Index of the first item to retrieve
     */
    public ListCustomerProductsResponseBody withOffset(@Nullable Long offset) {
        this.offset = offset;
        return this;
    }


    public ListCustomerProductsResponseBody withData(@Nullable List<ListCustomerProductsData> data) {
        this.data = data;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListCustomerProductsResponseBody other = (ListCustomerProductsResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.totalCount, other.totalCount) &&
            Utils.enhancedDeepEquals(this.count, other.count) &&
            Utils.enhancedDeepEquals(this.limit, other.limit) &&
            Utils.enhancedDeepEquals(this.offset, other.offset) &&
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            totalCount, count, limit,
            offset, data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListCustomerProductsResponseBody.class,
                "totalCount", totalCount,
                "count", count,
                "limit", limit,
                "offset", offset,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Long totalCount;

        private Long count;

        private Long limit;

        private Long offset;

        private List<ListCustomerProductsData> data;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Total count of items available to retrieve
         */
        public Builder totalCount(@Nullable Long totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /**
         * Number of items retrieved
         */
        public Builder count(@Nullable Long count) {
            this.count = count;
            return this;
        }

        /**
         * Maximum number of items to retrieve
         */
        public Builder limit(@Nullable Long limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Index of the first item to retrieve
         */
        public Builder offset(@Nullable Long offset) {
            this.offset = offset;
            return this;
        }

        public Builder data(@Nullable List<ListCustomerProductsData> data) {
            this.data = data;
            return this;
        }

        public ListCustomerProductsResponseBody build() {
            return new ListCustomerProductsResponseBody(
                totalCount, count, limit,
                offset, data);
        }

    }
}
