/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PostVirtualReferenceNumbersLockReason
 * 
 * <p>Provided reason for locking the VRN.
 */
public class PostVirtualReferenceNumbersLockReason {

    public static final PostVirtualReferenceNumbersLockReason ADMIN = new PostVirtualReferenceNumbersLockReason("admin");
    public static final PostVirtualReferenceNumbersLockReason CUSTOMER_REQUEST = new PostVirtualReferenceNumbersLockReason("customer_request");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PostVirtualReferenceNumbersLockReason> values = createValuesMap();
    private static final Map<String, PostVirtualReferenceNumbersLockReasonEnum> enums = createEnumsMap();

    private final String value;

    private PostVirtualReferenceNumbersLockReason(String value) {
        this.value = value;
    }

    /**
     * Returns a PostVirtualReferenceNumbersLockReason with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PostVirtualReferenceNumbersLockReason
     */ 
    @JsonCreator
    public static PostVirtualReferenceNumbersLockReason of(String value) {
        synchronized (PostVirtualReferenceNumbersLockReason.class) {
            return values.computeIfAbsent(value, v -> new PostVirtualReferenceNumbersLockReason(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PostVirtualReferenceNumbersLockReasonEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PostVirtualReferenceNumbersLockReason other = (PostVirtualReferenceNumbersLockReason) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PostVirtualReferenceNumbersLockReason [value=" + value + "]";
    }

    // return an array just like an enum
    public static PostVirtualReferenceNumbersLockReason[] values() {
        synchronized (PostVirtualReferenceNumbersLockReason.class) {
            return values.values().toArray(new PostVirtualReferenceNumbersLockReason[] {});
        }
    }

    private static final Map<String, PostVirtualReferenceNumbersLockReason> createValuesMap() {
        Map<String, PostVirtualReferenceNumbersLockReason> map = new LinkedHashMap<>();
        map.put("admin", ADMIN);
        map.put("customer_request", CUSTOMER_REQUEST);
        return map;
    }

    private static final Map<String, PostVirtualReferenceNumbersLockReasonEnum> createEnumsMap() {
        Map<String, PostVirtualReferenceNumbersLockReasonEnum> map = new HashMap<>();
        map.put("admin", PostVirtualReferenceNumbersLockReasonEnum.ADMIN);
        map.put("customer_request", PostVirtualReferenceNumbersLockReasonEnum.CUSTOMER_REQUEST);
        return map;
    }
    
    
    public enum PostVirtualReferenceNumbersLockReasonEnum {

        ADMIN("admin"),
        CUSTOMER_REQUEST("customer_request"),;

        private final String value;

        private PostVirtualReferenceNumbersLockReasonEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

