/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class PostReturnsAchRequest {
    /**
     * The reason an ACH payment is being returned. Required if returning an RDFI transaction. Optional if
     * reversing an ODFI transaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ach_return_code")
    private AchReturnCodeRequest achReturnCode;

    /**
     * Freeform text (up to 44 characters) to attach a memo to return.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("addenda_info")
    private String addendaInfo;

    @JsonCreator
    public PostReturnsAchRequest(
            @JsonProperty("ach_return_code") @Nullable AchReturnCodeRequest achReturnCode,
            @JsonProperty("addenda_info") @Nullable String addendaInfo) {
        this.achReturnCode = achReturnCode;
        this.addendaInfo = addendaInfo;
    }
    
    public PostReturnsAchRequest() {
        this(null, null);
    }

    /**
     * The reason an ACH payment is being returned. Required if returning an RDFI transaction. Optional if
     * reversing an ODFI transaction.
     */
    public Optional<AchReturnCodeRequest> achReturnCode() {
        return Optional.ofNullable(this.achReturnCode);
    }

    /**
     * Freeform text (up to 44 characters) to attach a memo to return.
     */
    public Optional<String> addendaInfo() {
        return Optional.ofNullable(this.addendaInfo);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The reason an ACH payment is being returned. Required if returning an RDFI transaction. Optional if
     * reversing an ODFI transaction.
     */
    public PostReturnsAchRequest withAchReturnCode(@Nullable AchReturnCodeRequest achReturnCode) {
        this.achReturnCode = achReturnCode;
        return this;
    }


    /**
     * Freeform text (up to 44 characters) to attach a memo to return.
     */
    public PostReturnsAchRequest withAddendaInfo(@Nullable String addendaInfo) {
        this.addendaInfo = addendaInfo;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PostReturnsAchRequest other = (PostReturnsAchRequest) o;
        return 
            Utils.enhancedDeepEquals(this.achReturnCode, other.achReturnCode) &&
            Utils.enhancedDeepEquals(this.addendaInfo, other.addendaInfo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            achReturnCode, addendaInfo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PostReturnsAchRequest.class,
                "achReturnCode", achReturnCode,
                "addendaInfo", addendaInfo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AchReturnCodeRequest achReturnCode;

        private String addendaInfo;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The reason an ACH payment is being returned. Required if returning an RDFI transaction. Optional if
         * reversing an ODFI transaction.
         */
        public Builder achReturnCode(@Nullable AchReturnCodeRequest achReturnCode) {
            this.achReturnCode = achReturnCode;
            return this;
        }

        /**
         * Freeform text (up to 44 characters) to attach a memo to return.
         */
        public Builder addendaInfo(@Nullable String addendaInfo) {
            this.addendaInfo = addendaInfo;
            return this;
        }

        public PostReturnsAchRequest build() {
            return new PostReturnsAchRequest(
                achReturnCode, addendaInfo);
        }

    }
}
