/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PostCombinedTransfersStatus
 * 
 * <p>The combined transfer's status
 */
public class PostCombinedTransfersStatus {

    public static final PostCombinedTransfersStatus QUEUED = new PostCombinedTransfersStatus("queued");
    public static final PostCombinedTransfersStatus PENDING = new PostCombinedTransfersStatus("pending");
    public static final PostCombinedTransfersStatus FAILED = new PostCombinedTransfersStatus("failed");
    public static final PostCombinedTransfersStatus COMPLETED = new PostCombinedTransfersStatus("completed");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PostCombinedTransfersStatus> values = createValuesMap();
    private static final Map<String, PostCombinedTransfersStatusEnum> enums = createEnumsMap();

    private final String value;

    private PostCombinedTransfersStatus(String value) {
        this.value = value;
    }

    /**
     * Returns a PostCombinedTransfersStatus with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PostCombinedTransfersStatus
     */ 
    @JsonCreator
    public static PostCombinedTransfersStatus of(String value) {
        synchronized (PostCombinedTransfersStatus.class) {
            return values.computeIfAbsent(value, v -> new PostCombinedTransfersStatus(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PostCombinedTransfersStatusEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PostCombinedTransfersStatus other = (PostCombinedTransfersStatus) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PostCombinedTransfersStatus [value=" + value + "]";
    }

    // return an array just like an enum
    public static PostCombinedTransfersStatus[] values() {
        synchronized (PostCombinedTransfersStatus.class) {
            return values.values().toArray(new PostCombinedTransfersStatus[] {});
        }
    }

    private static final Map<String, PostCombinedTransfersStatus> createValuesMap() {
        Map<String, PostCombinedTransfersStatus> map = new LinkedHashMap<>();
        map.put("queued", QUEUED);
        map.put("pending", PENDING);
        map.put("failed", FAILED);
        map.put("completed", COMPLETED);
        return map;
    }

    private static final Map<String, PostCombinedTransfersStatusEnum> createEnumsMap() {
        Map<String, PostCombinedTransfersStatusEnum> map = new HashMap<>();
        map.put("queued", PostCombinedTransfersStatusEnum.QUEUED);
        map.put("pending", PostCombinedTransfersStatusEnum.PENDING);
        map.put("failed", PostCombinedTransfersStatusEnum.FAILED);
        map.put("completed", PostCombinedTransfersStatusEnum.COMPLETED);
        return map;
    }
    
    
    public enum PostCombinedTransfersStatusEnum {

        QUEUED("queued"),
        PENDING("pending"),
        FAILED("failed"),
        COMPLETED("completed"),;

        private final String value;

        private PostCombinedTransfersStatusEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

