/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PutTransfersUidCancelSecCode
 * 
 * <p>Standard Entry Class (SEC) code. Newline supports the following SEC codes: CCD, CIE, PPD, TEL, WEB.
 * For more details, refer to our ACH guide's
 * [section](https://developers.newline53.com/docs/ach#standard-entry-class-sec-codes) on SEC code use.
 */
public class PutTransfersUidCancelSecCode {

    public static final PutTransfersUidCancelSecCode CCD = new PutTransfersUidCancelSecCode("CCD");
    public static final PutTransfersUidCancelSecCode CIE = new PutTransfersUidCancelSecCode("CIE");
    public static final PutTransfersUidCancelSecCode PPD = new PutTransfersUidCancelSecCode("PPD");
    public static final PutTransfersUidCancelSecCode TEL = new PutTransfersUidCancelSecCode("TEL");
    public static final PutTransfersUidCancelSecCode WEB = new PutTransfersUidCancelSecCode("WEB");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PutTransfersUidCancelSecCode> values = createValuesMap();
    private static final Map<String, PutTransfersUidCancelSecCodeEnum> enums = createEnumsMap();

    private final String value;

    private PutTransfersUidCancelSecCode(String value) {
        this.value = value;
    }

    /**
     * Returns a PutTransfersUidCancelSecCode with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PutTransfersUidCancelSecCode
     */ 
    @JsonCreator
    public static PutTransfersUidCancelSecCode of(String value) {
        synchronized (PutTransfersUidCancelSecCode.class) {
            return values.computeIfAbsent(value, v -> new PutTransfersUidCancelSecCode(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PutTransfersUidCancelSecCodeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PutTransfersUidCancelSecCode other = (PutTransfersUidCancelSecCode) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PutTransfersUidCancelSecCode [value=" + value + "]";
    }

    // return an array just like an enum
    public static PutTransfersUidCancelSecCode[] values() {
        synchronized (PutTransfersUidCancelSecCode.class) {
            return values.values().toArray(new PutTransfersUidCancelSecCode[] {});
        }
    }

    private static final Map<String, PutTransfersUidCancelSecCode> createValuesMap() {
        Map<String, PutTransfersUidCancelSecCode> map = new LinkedHashMap<>();
        map.put("CCD", CCD);
        map.put("CIE", CIE);
        map.put("PPD", PPD);
        map.put("TEL", TEL);
        map.put("WEB", WEB);
        return map;
    }

    private static final Map<String, PutTransfersUidCancelSecCodeEnum> createEnumsMap() {
        Map<String, PutTransfersUidCancelSecCodeEnum> map = new HashMap<>();
        map.put("CCD", PutTransfersUidCancelSecCodeEnum.CCD);
        map.put("CIE", PutTransfersUidCancelSecCodeEnum.CIE);
        map.put("PPD", PutTransfersUidCancelSecCodeEnum.PPD);
        map.put("TEL", PutTransfersUidCancelSecCodeEnum.TEL);
        map.put("WEB", PutTransfersUidCancelSecCodeEnum.WEB);
        return map;
    }
    
    
    public enum PutTransfersUidCancelSecCodeEnum {

        CCD("CCD"),
        CIE("CIE"),
        PPD("PPD"),
        TEL("TEL"),
        WEB("WEB"),;

        private final String value;

        private PutTransfersUidCancelSecCodeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

