/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * PutVirtualReferenceNumbersUidLockType
 * 
 * <p>The type of VRN.
 */
public class PutVirtualReferenceNumbersUidLockType {

    public static final PutVirtualReferenceNumbersUidLockType BUSINESS = new PutVirtualReferenceNumbersUidLockType("business");
    public static final PutVirtualReferenceNumbersUidLockType CONSUMER = new PutVirtualReferenceNumbersUidLockType("consumer");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PutVirtualReferenceNumbersUidLockType> values = createValuesMap();
    private static final Map<String, PutVirtualReferenceNumbersUidLockTypeEnum> enums = createEnumsMap();

    private final String value;

    private PutVirtualReferenceNumbersUidLockType(String value) {
        this.value = value;
    }

    /**
     * Returns a PutVirtualReferenceNumbersUidLockType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PutVirtualReferenceNumbersUidLockType
     */ 
    @JsonCreator
    public static PutVirtualReferenceNumbersUidLockType of(String value) {
        synchronized (PutVirtualReferenceNumbersUidLockType.class) {
            return values.computeIfAbsent(value, v -> new PutVirtualReferenceNumbersUidLockType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<PutVirtualReferenceNumbersUidLockTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PutVirtualReferenceNumbersUidLockType other = (PutVirtualReferenceNumbersUidLockType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PutVirtualReferenceNumbersUidLockType [value=" + value + "]";
    }

    // return an array just like an enum
    public static PutVirtualReferenceNumbersUidLockType[] values() {
        synchronized (PutVirtualReferenceNumbersUidLockType.class) {
            return values.values().toArray(new PutVirtualReferenceNumbersUidLockType[] {});
        }
    }

    private static final Map<String, PutVirtualReferenceNumbersUidLockType> createValuesMap() {
        Map<String, PutVirtualReferenceNumbersUidLockType> map = new LinkedHashMap<>();
        map.put("business", BUSINESS);
        map.put("consumer", CONSUMER);
        return map;
    }

    private static final Map<String, PutVirtualReferenceNumbersUidLockTypeEnum> createEnumsMap() {
        Map<String, PutVirtualReferenceNumbersUidLockTypeEnum> map = new HashMap<>();
        map.put("business", PutVirtualReferenceNumbersUidLockTypeEnum.BUSINESS);
        map.put("consumer", PutVirtualReferenceNumbersUidLockTypeEnum.CONSUMER);
        return map;
    }
    
    
    public enum PutVirtualReferenceNumbersUidLockTypeEnum {

        BUSINESS("business"),
        CONSUMER("consumer"),;

        private final String value;

        private PutVirtualReferenceNumbersUidLockTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

