/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * QueryParamInstantPaymentRailRegistrationStatus
 * 
 * <p>Registration status with Newline and Fifth Third, for RTP network acceptance.
 */
public enum QueryParamInstantPaymentRailRegistrationStatus {
    FAILED("failed"),
    PENDING("pending"),
    REGISTERED("registered"),
    UNREGISTERED("unregistered");

    @JsonValue
    private final String value;

    QueryParamInstantPaymentRailRegistrationStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<QueryParamInstantPaymentRailRegistrationStatus> fromValue(String value) {
        for (QueryParamInstantPaymentRailRegistrationStatus o: QueryParamInstantPaymentRailRegistrationStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

