/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * QueryParamSyntheticAccountCategory
 * 
 * <p>Filter by Synthetic Account Category
 */
public enum QueryParamSyntheticAccountCategory {
    GENERAL("general"),
    ACH_EXTERNAL("ach_external"),
    WIRE_EXTERNAL("wire_external"),
    INSTANT_PAYMENT_EXTERNAL("instant_payment_external");

    @JsonValue
    private final String value;

    QueryParamSyntheticAccountCategory(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<QueryParamSyntheticAccountCategory> fromValue(String value) {
        for (QueryParamSyntheticAccountCategory o: QueryParamSyntheticAccountCategory.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

