/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * QueryParamKycStatus
 * 
 * <p>Filter by KYC status. Multiple values are allowed e.g.
 * `kyc_status[]=approved&amp;kyc_status[]=under_review`.
 */
public enum QueryParamKycStatus {
    APPROVED("approved"),
    DENIED("denied"),
    DOCUMENTS_PROVIDED("documents_provided"),
    DOCUMENTS_REJECTED("documents_rejected"),
    MANUAL_REVIEW("manual_review"),
    PENDING_ID_DOCUMENTS("pending_id_documents"),
    PENDING_POA_DOCUMENTS("pending_poa_documents"),
    PENDING_IDANDPOA_DOCUMENTS("pending_idandpoa_documents"),
    RETAKE_IMAGES("retake_images"),
    PRE_VERIFIED("pre_verified");

    @JsonValue
    private final String value;

    QueryParamKycStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<QueryParamKycStatus> fromValue(String value) {
        for (QueryParamKycStatus o: QueryParamKycStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

