/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * QueryParamCustomerType
 * 
 * <p>Only return Customers with a customer type matching exactly what is submitted. Multiple values are
 * allowed e.g. `customer_type[]=primary&amp;customer_type[]=secondary`.
 */
public enum QueryParamCustomerType {
    PRIMARY("primary"),
    SECONDARY("secondary"),
    SOLE_PROPRIETOR("sole_proprietor");

    @JsonValue
    private final String value;

    QueryParamCustomerType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<QueryParamCustomerType> fromValue(String value) {
        for (QueryParamCustomerType o: QueryParamCustomerType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

