/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * SyntheticAccountStructuredAddress
 * 
 * <p>Structured wire address using ISO-style parsed fields. Accepted when your program's wire address
 * configuration is set to `structured` or `both`. Required fields: `city` and `country`.
 */
public class SyntheticAccountStructuredAddress {
    /**
     * Full street line (alternative to `building_number` + `street_name`). Optional 33 characters. Cannot
     * contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line1")
    private JsonNullable<String> line1;

    /**
     * Optional continuation, unit, or suite. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line2")
    private JsonNullable<String> line2;

    /**
     * Parsed building or house number. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("building_number")
    private JsonNullable<String> buildingNumber;

    /**
     * Parsed street name. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("street_name")
    private JsonNullable<String> streetName;

    /**
     * Required. 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    @JsonProperty("city")
    private String city;

    /**
     * State or province. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("state")
    private JsonNullable<String> state;

    /**
     * US ZIP code (5-digit) or ZIP+4.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postal_code")
    private JsonNullable<String> postalCode;


    @JsonProperty("country")
    private String country;

    @JsonCreator
    public SyntheticAccountStructuredAddress(
            @JsonProperty("line1") @Nullable JsonNullable<String> line1,
            @JsonProperty("line2") @Nullable JsonNullable<String> line2,
            @JsonProperty("building_number") @Nullable JsonNullable<String> buildingNumber,
            @JsonProperty("street_name") @Nullable JsonNullable<String> streetName,
            @JsonProperty("city") @Nonnull String city,
            @JsonProperty("state") @Nullable JsonNullable<String> state,
            @JsonProperty("postal_code") @Nullable JsonNullable<String> postalCode,
            @JsonProperty("country") @Nonnull String country) {
        this.line1 = Optional.ofNullable(line1)
            .orElse(JsonNullable.undefined());
        this.line2 = Optional.ofNullable(line2)
            .orElse(JsonNullable.undefined());
        this.buildingNumber = Optional.ofNullable(buildingNumber)
            .orElse(JsonNullable.undefined());
        this.streetName = Optional.ofNullable(streetName)
            .orElse(JsonNullable.undefined());
        this.city = Optional.ofNullable(city)
            .orElseThrow(() -> new IllegalArgumentException("city cannot be null"));
        this.state = Optional.ofNullable(state)
            .orElse(JsonNullable.undefined());
        this.postalCode = Optional.ofNullable(postalCode)
            .orElse(JsonNullable.undefined());
        this.country = Optional.ofNullable(country)
            .orElseThrow(() -> new IllegalArgumentException("country cannot be null"));
    }
    
    public SyntheticAccountStructuredAddress(
            @Nonnull String city,
            @Nonnull String country) {
        this(null, null, null,
            null, city, null,
            null, country);
    }

    /**
     * Full street line (alternative to `building_number` + `street_name`). Optional 33 characters. Cannot
     * contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public JsonNullable<String> line1() {
        return this.line1;
    }

    /**
     * Optional continuation, unit, or suite. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public JsonNullable<String> line2() {
        return this.line2;
    }

    /**
     * Parsed building or house number. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public JsonNullable<String> buildingNumber() {
        return this.buildingNumber;
    }

    /**
     * Parsed street name. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public JsonNullable<String> streetName() {
        return this.streetName;
    }

    /**
     * Required. 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public String city() {
        return this.city;
    }

    /**
     * State or province. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public JsonNullable<String> state() {
        return this.state;
    }

    /**
     * US ZIP code (5-digit) or ZIP+4.
     */
    public JsonNullable<String> postalCode() {
        return this.postalCode;
    }

    public String country() {
        return this.country;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Full street line (alternative to `building_number` + `street_name`). Optional 33 characters. Cannot
     * contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public SyntheticAccountStructuredAddress withLine1(@Nullable String line1) {
        this.line1 = JsonNullable.of(line1);
        return this;
    }


    /**
     * Optional continuation, unit, or suite. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public SyntheticAccountStructuredAddress withLine2(@Nullable String line2) {
        this.line2 = JsonNullable.of(line2);
        return this;
    }


    /**
     * Parsed building or house number. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public SyntheticAccountStructuredAddress withBuildingNumber(@Nullable String buildingNumber) {
        this.buildingNumber = JsonNullable.of(buildingNumber);
        return this;
    }


    /**
     * Parsed street name. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public SyntheticAccountStructuredAddress withStreetName(@Nullable String streetName) {
        this.streetName = JsonNullable.of(streetName);
        return this;
    }


    /**
     * Required. 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public SyntheticAccountStructuredAddress withCity(@Nonnull String city) {
        this.city = Utils.checkNotNull(city, "city");
        return this;
    }


    /**
     * State or province. Optional 33 characters. Cannot contain \# @ $!
     * 
     * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
     */
    public SyntheticAccountStructuredAddress withState(@Nullable String state) {
        this.state = JsonNullable.of(state);
        return this;
    }


    /**
     * US ZIP code (5-digit) or ZIP+4.
     */
    public SyntheticAccountStructuredAddress withPostalCode(@Nullable String postalCode) {
        this.postalCode = JsonNullable.of(postalCode);
        return this;
    }


    public SyntheticAccountStructuredAddress withCountry(@Nonnull String country) {
        this.country = Utils.checkNotNull(country, "country");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SyntheticAccountStructuredAddress other = (SyntheticAccountStructuredAddress) o;
        return 
            Utils.enhancedDeepEquals(this.line1, other.line1) &&
            Utils.enhancedDeepEquals(this.line2, other.line2) &&
            Utils.enhancedDeepEquals(this.buildingNumber, other.buildingNumber) &&
            Utils.enhancedDeepEquals(this.streetName, other.streetName) &&
            Utils.enhancedDeepEquals(this.city, other.city) &&
            Utils.enhancedDeepEquals(this.state, other.state) &&
            Utils.enhancedDeepEquals(this.postalCode, other.postalCode) &&
            Utils.enhancedDeepEquals(this.country, other.country);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            line1, line2, buildingNumber,
            streetName, city, state,
            postalCode, country);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SyntheticAccountStructuredAddress.class,
                "line1", line1,
                "line2", line2,
                "buildingNumber", buildingNumber,
                "streetName", streetName,
                "city", city,
                "state", state,
                "postalCode", postalCode,
                "country", country);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<String> line1;

        private JsonNullable<String> line2;

        private JsonNullable<String> buildingNumber;

        private JsonNullable<String> streetName;

        private String city;

        private JsonNullable<String> state;

        private JsonNullable<String> postalCode;

        private String country;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Full street line (alternative to `building_number` + `street_name`). Optional 33 characters. Cannot
         * contain \# @ $!
         * 
         * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
         */
        public Builder line1(@Nullable String line1) {
            this.line1 = JsonNullable.of(line1);
            return this;
        }

        /**
         * Optional continuation, unit, or suite. Optional 33 characters. Cannot contain \# @ $!
         * 
         * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
         */
        public Builder line2(@Nullable String line2) {
            this.line2 = JsonNullable.of(line2);
            return this;
        }

        /**
         * Parsed building or house number. Optional 33 characters. Cannot contain \# @ $!
         * 
         * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
         */
        public Builder buildingNumber(@Nullable String buildingNumber) {
            this.buildingNumber = JsonNullable.of(buildingNumber);
            return this;
        }

        /**
         * Parsed street name. Optional 33 characters. Cannot contain \# @ $!
         * 
         * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
         */
        public Builder streetName(@Nullable String streetName) {
            this.streetName = JsonNullable.of(streetName);
            return this;
        }

        /**
         * Required. 33 characters. Cannot contain \# @ $!
         * 
         * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
         */
        public Builder city(@Nonnull String city) {
            this.city = Utils.checkNotNull(city, "city");
            return this;
        }

        /**
         * State or province. Optional 33 characters. Cannot contain \# @ $!
         * 
         * <p>" % &amp; * ; &lt; &gt; { } [ ] _ ^ \ ~
         */
        public Builder state(@Nullable String state) {
            this.state = JsonNullable.of(state);
            return this;
        }

        /**
         * US ZIP code (5-digit) or ZIP+4.
         */
        public Builder postalCode(@Nullable String postalCode) {
            this.postalCode = JsonNullable.of(postalCode);
            return this;
        }

        public Builder country(@Nonnull String country) {
            this.country = Utils.checkNotNull(country, "country");
            return this;
        }

        public SyntheticAccountStructuredAddress build() {
            return new SyntheticAccountStructuredAddress(
                line1, line2, buildingNumber,
                streetName, city, state,
                postalCode, country);
        }

    }
}
