/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * TransferInstantPayment
 * 
 * <p>Instant payment information. Only present if the Transfer is an instant payment.
 */
public class TransferInstantPayment {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("instant_payment_transmitter")
    private PostCombinedTransfersInstantPaymentTransmitter instantPaymentTransmitter;

    /**
     * A message transmitted to the recipient bank. Supports letters, numbers, and special characters:.
     * !@#$%^&amp;*',/:;&lt;=&gt;?~`|[]{})(+=_- (max 140 characters).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("memo")
    private JsonNullable<String> memo;

    @JsonCreator
    public TransferInstantPayment(
            @JsonProperty("instant_payment_transmitter") @Nullable PostCombinedTransfersInstantPaymentTransmitter instantPaymentTransmitter,
            @JsonProperty("memo") @Nullable JsonNullable<String> memo) {
        this.instantPaymentTransmitter = instantPaymentTransmitter;
        this.memo = Optional.ofNullable(memo)
            .orElse(JsonNullable.undefined());
    }
    
    public TransferInstantPayment() {
        this(null, null);
    }

    public Optional<PostCombinedTransfersInstantPaymentTransmitter> instantPaymentTransmitter() {
        return Optional.ofNullable(this.instantPaymentTransmitter);
    }

    /**
     * A message transmitted to the recipient bank. Supports letters, numbers, and special characters:.
     * !@#$%^&amp;*',/:;&lt;=&gt;?~`|[]{})(+=_- (max 140 characters).
     */
    public JsonNullable<String> memo() {
        return this.memo;
    }

    public static Builder builder() {
        return new Builder();
    }


    public TransferInstantPayment withInstantPaymentTransmitter(@Nullable PostCombinedTransfersInstantPaymentTransmitter instantPaymentTransmitter) {
        this.instantPaymentTransmitter = instantPaymentTransmitter;
        return this;
    }


    /**
     * A message transmitted to the recipient bank. Supports letters, numbers, and special characters:.
     * !@#$%^&amp;*',/:;&lt;=&gt;?~`|[]{})(+=_- (max 140 characters).
     */
    public TransferInstantPayment withMemo(@Nullable String memo) {
        this.memo = JsonNullable.of(memo);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransferInstantPayment other = (TransferInstantPayment) o;
        return 
            Utils.enhancedDeepEquals(this.instantPaymentTransmitter, other.instantPaymentTransmitter) &&
            Utils.enhancedDeepEquals(this.memo, other.memo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            instantPaymentTransmitter, memo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TransferInstantPayment.class,
                "instantPaymentTransmitter", instantPaymentTransmitter,
                "memo", memo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PostCombinedTransfersInstantPaymentTransmitter instantPaymentTransmitter;

        private JsonNullable<String> memo;

        private Builder() {
          // force use of static builder() method
        }

        public Builder instantPaymentTransmitter(@Nullable PostCombinedTransfersInstantPaymentTransmitter instantPaymentTransmitter) {
            this.instantPaymentTransmitter = instantPaymentTransmitter;
            return this;
        }

        /**
         * A message transmitted to the recipient bank. Supports letters, numbers, and special characters:.
         * !@#$%^&amp;*',/:;&lt;=&gt;?~`|[]{})(+=_- (max 140 characters).
         */
        public Builder memo(@Nullable String memo) {
            this.memo = JsonNullable.of(memo);
            return this;
        }

        public TransferInstantPayment build() {
            return new TransferInstantPayment(
                instantPaymentTransmitter, memo);
        }

    }
}
