/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.newline53.sdk.models.operations.DeleteSyntheticAccountError;
import com.newline53.sdk.utils.Blob;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Deprecated;
import java.lang.Exception;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.lang.Throwable;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

@SuppressWarnings("serial")
public class DeleteSyntheticAccountUnprocessableEntityException extends NewlineException {

    @Nullable
    private final Data data;

    @Nullable
    private final Throwable deserializationException;

    public DeleteSyntheticAccountUnprocessableEntityException(
                int code,
                byte[] body,
                HttpResponse<?> rawResponse,
                @Nullable Data data,
                @Nullable Throwable deserializationException) {
        super("API error occurred", code, body, rawResponse, null);
        this.data = data;
        this.deserializationException = deserializationException;
    }

    /**
    * Parse a response into an instance of DeleteSyntheticAccountUnprocessableEntityException. If deserialization of the response body fails,
    * the resulting DeleteSyntheticAccountUnprocessableEntityException instance will have a null data() value and a non-null deserializationException().
    */
    public static DeleteSyntheticAccountUnprocessableEntityException from(HttpResponse<InputStream> response) {
        try {
            byte[] bytes = Utils.extractByteArrayFromBody(response);
            Data data = Utils.mapper().readValue(bytes, Data.class);
            return new DeleteSyntheticAccountUnprocessableEntityException(response.statusCode(), bytes, response, data, null);
        } catch (Exception e) {
            return new DeleteSyntheticAccountUnprocessableEntityException(response.statusCode(), null, response, null, e);
        }
    }

    /**
    * Parse a response into an instance of DeleteSyntheticAccountUnprocessableEntityException asynchronously. If deserialization of the response body fails,
    * the resulting DeleteSyntheticAccountUnprocessableEntityException instance will have a null data() value and a non-null deserializationException().
    */
    public static CompletableFuture<DeleteSyntheticAccountUnprocessableEntityException> fromAsync(HttpResponse<Blob> response) {
        return response.body()
                .toByteArray()
                .handle((bytes, err) -> {
                    // if a body read error occurs, we want to transform the exception
                    if (err != null) {
                        throw new AsyncAPIException(
                                "Error reading response body: " + err.getMessage(),
                                response.statusCode(),
                                null,
                                response,
                                err);
                    }

                    try {
                        return new DeleteSyntheticAccountUnprocessableEntityException(
                                response.statusCode(),
                                bytes,
                                response,
                                Utils.mapper().readValue(
                                        bytes,
                                        new TypeReference<Data>() {
                                        }),
                                null);
                    } catch (Exception e) {
                        return new DeleteSyntheticAccountUnprocessableEntityException(
                                response.statusCode(),
                                bytes,
                                response,
                                null,
                                e);
                    }
                });
    }

    @Deprecated
    public Optional<List<DeleteSyntheticAccountError>> errors() {
        return data().flatMap(Data::errors);
    }

    /**
     * HTTP Status Code
     */
    @Deprecated
    public Optional<Long> status() {
        return data().flatMap(Data::status);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(data);
    }

    /**
     * Returns the exception if an error occurs while deserializing the response body.
     */
    public Optional<Throwable> deserializationException() {
        return Optional.ofNullable(deserializationException);
    }
    /**
     * Data
     * 
     * <p>A Synthetic Account is not archived
     */
    public static class Data {

        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("errors")
        private List<DeleteSyntheticAccountError> errors;

        /**
         * HTTP Status Code
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("status")
        private Long status;

        @JsonCreator
        public Data(
                @JsonProperty("errors") @Nullable List<DeleteSyntheticAccountError> errors,
                @JsonProperty("status") @Nullable Long status) {
            this.errors = errors;
            this.status = status;
        }
        
        public Data() {
            this(null, null);
        }

        public Optional<List<DeleteSyntheticAccountError>> errors() {
            return Optional.ofNullable(this.errors);
        }

        /**
         * HTTP Status Code
         */
        public Optional<Long> status() {
            return Optional.ofNullable(this.status);
        }

        public static Builder builder() {
            return new Builder();
        }


        public Data withErrors(@Nullable List<DeleteSyntheticAccountError> errors) {
            this.errors = errors;
            return this;
        }


        /**
         * HTTP Status Code
         */
        public Data withStatus(@Nullable Long status) {
            this.status = status;
            return this;
        }


        @Override
        public boolean equals(java.lang.Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Data other = (Data) o;
            return 
                Utils.enhancedDeepEquals(this.errors, other.errors) &&
                Utils.enhancedDeepEquals(this.status, other.status);
        }
        
        @Override
        public int hashCode() {
            return Utils.enhancedHash(
                errors, status);
        }
        
        @Override
        public String toString() {
            return Utils.toString(Data.class,
                    "errors", errors,
                    "status", status);
        }

        @SuppressWarnings("UnusedReturnValue")
        public final static class Builder {

            private List<DeleteSyntheticAccountError> errors;

            private Long status;

            private Builder() {
              // force use of static builder() method
            }

            public Builder errors(@Nullable List<DeleteSyntheticAccountError> errors) {
                this.errors = errors;
                return this;
            }

            /**
             * HTTP Status Code
             */
            public Builder status(@Nullable Long status) {
                this.status = status;
                return this;
            }

            public Data build() {
                return new Data(
                    errors, status);
            }

        }
    }

}

