/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static com.newline53.sdk.operations.Operations.AsyncRequestOperation;

import com.newline53.sdk.models.operations.GetProductRequest;
import com.newline53.sdk.models.operations.ListProductsRequest;
import com.newline53.sdk.models.operations.async.GetProductRequestBuilder;
import com.newline53.sdk.models.operations.async.GetProductResponse;
import com.newline53.sdk.models.operations.async.ListProductsRequestBuilder;
import com.newline53.sdk.models.operations.async.ListProductsResponse;
import com.newline53.sdk.operations.GetProduct;
import com.newline53.sdk.operations.ListProducts;
import com.newline53.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

/**
 * Products represent financial services available in your program. Discover onboarding requirements,
 * prerequisites, and detailed product configurations.
 * 
 * <p>**Endpoints:**
 * 
 * <p>- GET [List Products: GET /products](https://developers.newline53.com/reference/get_products)
 * 
 * <p>- GET [Get a single Product: GET
 * /products/{uid}](https://developers.newline53.com/reference/get_products-uid)
 * 
 * <p>The Products endpoint represents the financial products available to your Customers. It exposes the
 * accounts, compliance, and Customer Profile Requirements necessary for your Customer to access the
 * Product. For some programs, a customer must onboard one product before another product is made
 * available.
 * 
 * <p>Newline will work with clients to define the required Product onboarding sequence as part of your
 * Program.
 * 
 * <p>Use the Products endpoint to view the Products available to your Program and the prerequisite
 * information or actions that must be taken for a Customer to access the Product.
 * 
 * <p>For more information about Newline's products and their utilization, please refer to the [Products
 * Programs](https://developers.newline53.com/docs/product-programs) guides.
 */
public class AsyncProducts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Products syncSDK;

    AsyncProducts(Products syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Products toSync() {
        return syncSDK;
    }


    /**
     * List Products
     * 
     * <p>Products filtered by the given parameters.
     * 
     * @return The async call builder
     */
    public ListProductsRequestBuilder list() {
        return new ListProductsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Products
     * 
     * <p>Products filtered by the given parameters.
     * 
     * @return {@code CompletableFuture<ListProductsResponse>} - The async response
     */
    public CompletableFuture<ListProductsResponse> listDirect() {
        return list(null);
    }

    /**
     * List Products
     * 
     * <p>Products filtered by the given parameters.
     * 
     * @param programUid Only return Products belonging to the submitted Program
     * @return {@code CompletableFuture<ListProductsResponse>} - The async response
     */
    public CompletableFuture<ListProductsResponse> list(@Nullable String programUid) {
        ListProductsRequest request = new ListProductsRequest(programUid);
        AsyncRequestOperation<ListProductsRequest, ListProductsResponse> operation
              = new ListProducts.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get a single Product
     * 
     * <p>Retrieve overall status about a Product as well as its configuration, availability, and any
     * associated metadata.
     * 
     * @return The async call builder
     */
    public GetProductRequestBuilder get() {
        return new GetProductRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Product
     * 
     * <p>Retrieve overall status about a Product as well as its configuration, availability, and any
     * associated metadata.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return {@code CompletableFuture<GetProductResponse>} - The async response
     */
    public CompletableFuture<GetProductResponse> get(@Nonnull String uid) {
        GetProductRequest request = new GetProductRequest(uid);
        AsyncRequestOperation<GetProductRequest, GetProductResponse> operation
              = new GetProduct.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
