/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static com.newline53.sdk.operations.Operations.AsyncRequestOperation;

import com.newline53.sdk.models.operations.GetCustomerProductRequest;
import com.newline53.sdk.models.operations.ListCustomerProductsRequest;
import com.newline53.sdk.models.operations.OnboardCustomerProductRequest;
import com.newline53.sdk.models.operations.async.GetCustomerProductRequestBuilder;
import com.newline53.sdk.models.operations.async.GetCustomerProductResponse;
import com.newline53.sdk.models.operations.async.ListCustomerProductsRequestBuilder;
import com.newline53.sdk.models.operations.async.ListCustomerProductsResponse;
import com.newline53.sdk.models.operations.async.OnboardCustomerProductRequestBuilder;
import com.newline53.sdk.models.operations.async.OnboardCustomerProductResponse;
import com.newline53.sdk.operations.GetCustomerProduct;
import com.newline53.sdk.operations.ListCustomerProducts;
import com.newline53.sdk.operations.OnboardCustomerProduct;
import com.newline53.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;


public class AsyncCustomerProducts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final CustomerProducts syncSDK;

    AsyncCustomerProducts(CustomerProducts syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public CustomerProducts toSync() {
        return syncSDK;
    }


    /**
     * List Customer Products
     * 
     * <p>List Customers and the Products they have onboarded onto, filtered by the given parameters.
     * 
     * @return The async call builder
     */
    public ListCustomerProductsRequestBuilder list() {
        return new ListCustomerProductsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Customer Products
     * 
     * <p>List Customers and the Products they have onboarded onto, filtered by the given parameters.
     * 
     * @return {@code CompletableFuture<ListCustomerProductsResponse>} - The async response
     */
    public CompletableFuture<ListCustomerProductsResponse> listDirect() {
        return list(null, null, null);
    }

    /**
     * List Customer Products
     * 
     * <p>List Customers and the Products they have onboarded onto, filtered by the given parameters.
     * 
     * @param programUid Only return Customer Products belonging to the submitted Program
     * @param productUid Only return Customer Products belonging to the submitted Product
     * @param customerUid Filter by Customer. Multiple values are allowed, e.g. `customer_uid[]=uKxmLxUEiSj5h4M3&customer_uid[]=y9reyPMNEWuuYSC1`.
     *         
     * @return {@code CompletableFuture<ListCustomerProductsResponse>} - The async response
     */
    public CompletableFuture<ListCustomerProductsResponse> list(
            @Nullable String programUid, @Nullable String productUid,
            @Nullable String customerUid) {
        ListCustomerProductsRequest request = new ListCustomerProductsRequest(programUid, productUid, customerUid);
        AsyncRequestOperation<ListCustomerProductsRequest, ListCustomerProductsResponse> operation
              = new ListCustomerProducts.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Onboard Customer onto a Product
     * 
     * <p>Submit a request to onboard a Customer onto a new product. Ensure all required Customer details have
     * been provided with [Adjust Customer
     * Data](https://developers.newline53.com/reference/put_customers-uid) before making this request. An
     * error will be returned if details are missing or invalid.
     * 
     * <p>The request to onboard a Customer serves as explicit confirmation from you that the Customer is
     * ready for account opening. This event initiates the KYC/AML verification process and account opening
     * in your Program. This is a billable event and is isolated intentionally for you to confirm that the
     * Customer record is complete.
     * 
     * <p>Customer Onboarding is the event that locks the customer PII and profile responses from further
     * edits.
     * 
     * <p>Customer Onboarding is designed to work as follows:
     * 
     * <p>- The Customer provides complete PII as defined by the Customers endpoint
     * - The Customer provides complete Customer Profile information as defined by the Product endpoint
     * - You submit a request to Customer Products with the specified Product this Customer is onboarding
     * onto
     * - Newline performs a validation on the PII provided and the Customer Profile data to confirm all are
     * valid
     * 
     * <p>If the Customer passes these validations and meets the duration requirements described below, the
     * Customer record is submitted to the KYC process
     * 
     * @return The async call builder
     */
    public OnboardCustomerProductRequestBuilder onboard() {
        return new OnboardCustomerProductRequestBuilder(sdkConfiguration);
    }

    /**
     * Onboard Customer onto a Product
     * 
     * <p>Submit a request to onboard a Customer onto a new product. Ensure all required Customer details have
     * been provided with [Adjust Customer
     * Data](https://developers.newline53.com/reference/put_customers-uid) before making this request. An
     * error will be returned if details are missing or invalid.
     * 
     * <p>The request to onboard a Customer serves as explicit confirmation from you that the Customer is
     * ready for account opening. This event initiates the KYC/AML verification process and account opening
     * in your Program. This is a billable event and is isolated intentionally for you to confirm that the
     * Customer record is complete.
     * 
     * <p>Customer Onboarding is the event that locks the customer PII and profile responses from further
     * edits.
     * 
     * <p>Customer Onboarding is designed to work as follows:
     * 
     * <p>- The Customer provides complete PII as defined by the Customers endpoint
     * - The Customer provides complete Customer Profile information as defined by the Product endpoint
     * - You submit a request to Customer Products with the specified Product this Customer is onboarding
     * onto
     * - Newline performs a validation on the PII provided and the Customer Profile data to confirm all are
     * valid
     * 
     * <p>If the Customer passes these validations and meets the duration requirements described below, the
     * Customer record is submitted to the KYC process
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<OnboardCustomerProductResponse>} - The async response
     */
    public CompletableFuture<OnboardCustomerProductResponse> onboard(@Nonnull OnboardCustomerProductRequest request) {
        AsyncRequestOperation<OnboardCustomerProductRequest, OnboardCustomerProductResponse> operation
              = new OnboardCustomerProduct.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get a single Customer Product
     * 
     * <p>Retrieves a single Customer Product resource along with its associated Customer and Product
     * 
     * @return The async call builder
     */
    public GetCustomerProductRequestBuilder get() {
        return new GetCustomerProductRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Customer Product
     * 
     * <p>Retrieves a single Customer Product resource along with its associated Customer and Product
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return {@code CompletableFuture<GetCustomerProductResponse>} - The async response
     */
    public CompletableFuture<GetCustomerProductResponse> get(@Nonnull String uid) {
        GetCustomerProductRequest request = new GetCustomerProductRequest(uid);
        AsyncRequestOperation<GetCustomerProductRequest, GetCustomerProductResponse> operation
              = new GetCustomerProduct.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
