/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.models.operations.CreateCustomerRequest;
import com.newline53.sdk.models.operations.CreateCustomerRequestBuilder;
import com.newline53.sdk.models.operations.CreateCustomerResponse;
import com.newline53.sdk.models.operations.DeleteCustomerRequest;
import com.newline53.sdk.models.operations.DeleteCustomerRequestBody;
import com.newline53.sdk.models.operations.DeleteCustomerRequestBuilder;
import com.newline53.sdk.models.operations.DeleteCustomerResponse;
import com.newline53.sdk.models.operations.GetCustomerRequest;
import com.newline53.sdk.models.operations.GetCustomerRequestBuilder;
import com.newline53.sdk.models.operations.GetCustomerResponse;
import com.newline53.sdk.models.operations.ListCustomersRequest;
import com.newline53.sdk.models.operations.ListCustomersRequestBuilder;
import com.newline53.sdk.models.operations.ListCustomersResponse;
import com.newline53.sdk.models.operations.UpdateCustomerRequest;
import com.newline53.sdk.models.operations.UpdateCustomerRequestBody;
import com.newline53.sdk.models.operations.UpdateCustomerRequestBuilder;
import com.newline53.sdk.models.operations.UpdateCustomerResponse;
import com.newline53.sdk.operations.CreateCustomer;
import com.newline53.sdk.operations.DeleteCustomer;
import com.newline53.sdk.operations.GetCustomer;
import com.newline53.sdk.operations.ListCustomers;
import com.newline53.sdk.operations.UpdateCustomer;
import com.newline53.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import java.lang.String;

/**
 * The Customers section provides details on managing end-user accounts. Learn how to create, update,
 * and archive customer records and onboard them to financial products while meeting KYC/AML
 * requirements.
 * 
 * <p>**Endpoints:**
 * 
 * <p>- GET [List Customers: GET /customers](https://developers.newline53.com/reference/get_customers)
 * 
 * <p>- POST [Create a new Customer: POST
 * /customers](https://developers.newline53.com/reference/post_customers)
 * 
 * <p>- GET [Get a single Customer: GET
 * /customers/{uid}](https://developers.newline53.com/reference/get_customers-uid)
 * 
 * <p>- PUT [Adjust Customer Data: PUT
 * /customers/{uid}](https://developers.newline53.com/reference/put_customers-uid)
 * 
 * <p>- DELETE [Archive a Customer: DELETE
 * /customers/{uid}](https://developers.newline53.com/reference/delete_customers-uid)
 * 
 * <p>A Customer on the Newline Platform is the end user of your application. Customers are unique to each
 * Program, and managing all accounts and identifying information is handled on a Program-by-Program
 * basis.
 * The ability to create new Customers is also a preset condition of your Program at Newline. Please
 * see the below sections for more details.
 * 
 * <p>## Newline preset-Customers
 * 
 * <p>In cases where the Client also serves as the Customer (i.e., the Client is both the end-user and the
 * managing entity over any financial products), Newline will create Customers upon Program onboarding.
 * Clients will also be precluded from creating new Customers.
 * 
 * <p>## Client-initiated Customers
 * 
 * <p>**Customer Onboarding Process for Clients**
 * When managing customer onboarding, follow the outlined steps and key considerations below.
 * 
 * <p>### Steps for Onboarding Customers:
 * 
 * <p>1. Initial Submission:
 * 
 * <p>1. Submit the external_uid and email using the Customers Endpoint.
 * 
 * <p>2. Provide Personally Identifiable Information (PII):
 * 
 * <p>1. After the initial submission, supply the remaining PII for the customer.
 * 
 * <p>2. Ensure that all required PII fields are complete. Requests with complete or missing fields will
 * be accepted.
 * 
 * <p>3. Edit PII (Optional):
 * 
 * <p>1. PII can be updated until a valid request is sent to onboard the customer to a product using the
 * Customer Product Endpoint.
 * 
 * <p>4. Submit Profile Responses:
 * 
 * <p>1. Provide profile responses to meet the product's profile requirements.
 * 
 * <p>2. Profile Requirements can include data such as:
 * 
 * <p>1. Risk tolerance
 * 
 * <p>2. Income level
 * 
 * <p>3. Other product-specific information
 * 
 * <p>5. Verify Profile Requirements:
 * 
 * <p>1. Use the Product Endpoint to access the Profile Requirements and ensure the customer satisfies all
 * prerequisites for onboarding.
 * 
 * <p>6. Initiate Onboarding Request:
 * 
 * <p>1. Submit a valid onboarding request for the customer using the Customer Products Endpoint.
 * 
 * <p>## Additional Considerations:
 * 
 * <p>KYC/AML Verification:
 * 
 * <p>- To join a program, customers must pass Know Your Customer (KYC) and Anti-Money Laundering (AML)
 * identity verification as required by Fifth Third Bank.
 * 
 * <p>- KYC_status on the customer record will indicate the current state of the KYC/AML workflow.
 * 
 * <p>Once a valid onboarding request is received, Newline initiates KYC/AML verification using the
 * customer's PII.
 * **Verification statuses include:**
 * 
 * <p>- Approved
 * 
 * <p>- Manual Review
 * 
 * <p>- Documents Required
 * 
 * <p>- Denied
 * 
 * <p>Newline will work with clients to define these states.
 * 
 * <p>## Program-Specific Records:
 * 
 * <p>- A new customer record must be created for each program, even if an identical customer exists in
 * another program.
 * 
 * <p>- Customer records are not accessible outside of their associated program.
 * 
 * <p>## Customer Management Functions:
 * 
 * <p>The Customers Endpoint can also be used to perform management actions such as:
 * 
 * <p>- Freezing or unfreezing a customer
 * 
 * <p>- Archiving a customer
 */
public class Customers {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncCustomers asyncSDK;

    Customers(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncCustomers(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncCustomers toAsync() {
        return asyncSDK;
    }

    /**
     * Get a list of Customers
     * 
     * <p>Retrieves a list of Customers filtered by the given parameters. Filter parameters are not case
     * sensitive, but will only return exact matches.
     * 
     * <p>Multiple filter parameters can be provided at once, but a result will not be returned unless there
     * are exact matches for all submitted parameters. As an example: submitting
     * `first_name=Olive&amp;last_name=Oyl` would match exactly "Olive Oyl" but NOT "Olive Boyl" or "Oliver
     * Oyl".
     * 
     * <p>The list endpoint will not include sensitive Customer data such as address or DOB. This can only be
     * retrieved by viewing a specific Customer record. By default we do not display Customers in the
     * `initiated` status, as Customers in this status have not completed onboarding.
     * 
     * <p>To cause Customers with this status to be included in the list you must provide the
     * `include_initiated=true` parameter.
     * 
     * @return The call builder
     */
    public ListCustomersRequestBuilder list() {
        return new ListCustomersRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of Customers
     * 
     * <p>Retrieves a list of Customers filtered by the given parameters. Filter parameters are not case
     * sensitive, but will only return exact matches.
     * 
     * <p>Multiple filter parameters can be provided at once, but a result will not be returned unless there
     * are exact matches for all submitted parameters. As an example: submitting
     * `first_name=Olive&amp;last_name=Oyl` would match exactly "Olive Oyl" but NOT "Olive Boyl" or "Oliver
     * Oyl".
     * 
     * <p>The list endpoint will not include sensitive Customer data such as address or DOB. This can only be
     * retrieved by viewing a specific Customer record. By default we do not display Customers in the
     * `initiated` status, as Customers in this status have not completed onboarding.
     * 
     * <p>To cause Customers with this status to be included in the list you must provide the
     * `include_initiated=true` parameter.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListCustomersResponse list(@Nonnull ListCustomersRequest request) {
        RequestOperation<ListCustomersRequest, ListCustomersResponse> operation
              = new ListCustomers.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a new Customer
     * 
     * <p>This endpoint is used to initialize a new Customer. All request body data is optional unless
     * otherwise specified. For customer types other than `primary`, `customer_type` must be specified.
     * 
     * <p>The `customer_type` cannot be changed after the customer is created. Customer details accepted by
     * [Adjust Customer Data](https://developers.newline53.com/reference/put_customers-uid) can be sent in
     * this request if desired. See Adjust Customer Data for an example with all customer details provided.
     * 
     * @return The call builder
     */
    public CreateCustomerRequestBuilder create() {
        return new CreateCustomerRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a new Customer
     * 
     * <p>This endpoint is used to initialize a new Customer. All request body data is optional unless
     * otherwise specified. For customer types other than `primary`, `customer_type` must be specified.
     * 
     * <p>The `customer_type` cannot be changed after the customer is created. Customer details accepted by
     * [Adjust Customer Data](https://developers.newline53.com/reference/put_customers-uid) can be sent in
     * this request if desired. See Adjust Customer Data for an example with all customer details provided.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateCustomerResponse create(@Nonnull CreateCustomerRequest request) {
        RequestOperation<CreateCustomerRequest, CreateCustomerResponse> operation
              = new CreateCustomer.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a single Customer
     * 
     * <p>Retrieve overall status about a Customer as well as their total Asset Balances across all accounts.
     * 
     * @return The call builder
     */
    public GetCustomerRequestBuilder get() {
        return new GetCustomerRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Customer
     * 
     * <p>Retrieve overall status about a Customer as well as their total Asset Balances across all accounts.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetCustomerResponse get(@Nonnull String uid) {
        GetCustomerRequest request = new GetCustomerRequest(uid);
        RequestOperation<GetCustomerRequest, GetCustomerResponse> operation
              = new GetCustomer.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Adjust Customer Data
     * 
     * <p>Submit or update a Customer's personally identifiable information (PII) after the Customer is
     * created. Before a Customer has been onboarded to a product with [Customer
     * Product](https://developers.newline53.com/reference/post_customer-products), this endpoint may be
     * used to update or remove any details without validations. After the Customer has been onboarded to a
     * product, all validations will be enforced.
     * 
     * <p>This endpoint is used to supply the remaining personally identifiable information (PII) for each
     * Customer after they are created. The PII for a Customer must be submitted in full. Newline will not
     * accept your request if any field is incomplete or missing.
     * 
     * <p>PII can be edited for a Customer up until a valid request is sent to the Customer Product endpoint.
     * Once a Customer is in a status of Active, subsequent calls to this endpoint will result in
     * additional KYC/AML evaluations. Each KYC/AML evaluation will result in a billable event for your
     * Program.
     * 
     * <p>Please work with Newline on how you plan to implement PII modifications for your Customers.
     * 
     * <p>Only first_name, middle_name, last_name, suffix, email, phone, and address will be editable after a
     * Customer is in a status of Active. Once Customer data is adjusted, the pii_confirmed_at field on the
     * Customer record will be updated.
     * 
     * <p>Newline accepts Tax Identifier Number in the Social Security Number field of the API. Newline
     * performs validation on the SSN field supplied with a Customer to prevent invalid SSN values. Newline
     * will reject a Customer record with a SSN value that does not adhere to the following parameters:
     * 
     * <p>- The 1st part, 3-digits, may not include 000, 666
     * - The 2nd part, 2-digits, may range from 01 to 99
     * - The 3rd part, 4-digits, may range from 0001 to 9999
     * 
     * <p>We will accept SSN and TIN in the SSN field of the /customers endpoint.
     * 
     * @return The call builder
     */
    public UpdateCustomerRequestBuilder update() {
        return new UpdateCustomerRequestBuilder(sdkConfiguration);
    }

    /**
     * Adjust Customer Data
     * 
     * <p>Submit or update a Customer's personally identifiable information (PII) after the Customer is
     * created. Before a Customer has been onboarded to a product with [Customer
     * Product](https://developers.newline53.com/reference/post_customer-products), this endpoint may be
     * used to update or remove any details without validations. After the Customer has been onboarded to a
     * product, all validations will be enforced.
     * 
     * <p>This endpoint is used to supply the remaining personally identifiable information (PII) for each
     * Customer after they are created. The PII for a Customer must be submitted in full. Newline will not
     * accept your request if any field is incomplete or missing.
     * 
     * <p>PII can be edited for a Customer up until a valid request is sent to the Customer Product endpoint.
     * Once a Customer is in a status of Active, subsequent calls to this endpoint will result in
     * additional KYC/AML evaluations. Each KYC/AML evaluation will result in a billable event for your
     * Program.
     * 
     * <p>Please work with Newline on how you plan to implement PII modifications for your Customers.
     * 
     * <p>Only first_name, middle_name, last_name, suffix, email, phone, and address will be editable after a
     * Customer is in a status of Active. Once Customer data is adjusted, the pii_confirmed_at field on the
     * Customer record will be updated.
     * 
     * <p>Newline accepts Tax Identifier Number in the Social Security Number field of the API. Newline
     * performs validation on the SSN field supplied with a Customer to prevent invalid SSN values. Newline
     * will reject a Customer record with a SSN value that does not adhere to the following parameters:
     * 
     * <p>- The 1st part, 3-digits, may not include 000, 666
     * - The 2nd part, 2-digits, may range from 01 to 99
     * - The 3rd part, 4-digits, may range from 0001 to 9999
     * 
     * <p>We will accept SSN and TIN in the SSN field of the /customers endpoint.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateCustomerResponse update(@Nonnull String uid, @Nonnull UpdateCustomerRequestBody body) {
        UpdateCustomerRequest request = new UpdateCustomerRequest(uid, body);
        RequestOperation<UpdateCustomerRequest, UpdateCustomerResponse> operation
              = new UpdateCustomer.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Archive a Customer
     * 
     * <p>Archiving a Customer refunds any remaining balance, closes all of their active Synthetic and
     * Custodial Accounts and closes their Debit Cards. This process can take up to 8 business days to
     * complete as the Transfers take place.
     * 
     * <p>When archiving a customer, you can prevent them from reapplying to your program by setting
     * `can_apply_again` to false. If you do not set any value, `can_apply_again` defaults to true.
     * 
     * <p>When a request to archive a Customer is first received, the customer status will update to
     * `pending_archival` and their accounts will be locked. When the archival process is complete, their
     * customer status will update to `archived`. For a customer to move to the `archived` status, they
     * must carry a $0 balance and have no pending transactions.
     * 
     * <p>If the Customer has a positive balance across any accounts and a connected external account, Newline
     * will initiate an ACH transfer to zero out the account balance and move the customer to the
     * `archived` status.
     * 
     * <p>If the Customer does not have an external account or the ACH transfer fails, Newline will mail a
     * paper check to the Customer address on file to zero out the account balance and move the customer to
     * the `archived` status.
     * 
     * <p>If the Customer has a negative balance across any accounts, the negative account balances must be
     * brought up to or greater than $0.00 before the archival workflow can continue.
     * 
     * <p>Once archived, a Customer's records will still be available for historical purposes (according to
     * the bank’s record retention schedule), but they will not be able to open any new Accounts. The
     * Customer can still apply again as long as `can_apply_again` is not set to false.
     * 
     * @return The call builder
     */
    public DeleteCustomerRequestBuilder delete() {
        return new DeleteCustomerRequestBuilder(sdkConfiguration);
    }

    /**
     * Archive a Customer
     * 
     * <p>Archiving a Customer refunds any remaining balance, closes all of their active Synthetic and
     * Custodial Accounts and closes their Debit Cards. This process can take up to 8 business days to
     * complete as the Transfers take place.
     * 
     * <p>When archiving a customer, you can prevent them from reapplying to your program by setting
     * `can_apply_again` to false. If you do not set any value, `can_apply_again` defaults to true.
     * 
     * <p>When a request to archive a Customer is first received, the customer status will update to
     * `pending_archival` and their accounts will be locked. When the archival process is complete, their
     * customer status will update to `archived`. For a customer to move to the `archived` status, they
     * must carry a $0 balance and have no pending transactions.
     * 
     * <p>If the Customer has a positive balance across any accounts and a connected external account, Newline
     * will initiate an ACH transfer to zero out the account balance and move the customer to the
     * `archived` status.
     * 
     * <p>If the Customer does not have an external account or the ACH transfer fails, Newline will mail a
     * paper check to the Customer address on file to zero out the account balance and move the customer to
     * the `archived` status.
     * 
     * <p>If the Customer has a negative balance across any accounts, the negative account balances must be
     * brought up to or greater than $0.00 before the archival workflow can continue.
     * 
     * <p>Once archived, a Customer's records will still be available for historical purposes (according to
     * the bank’s record retention schedule), but they will not be able to open any new Accounts. The
     * Customer can still apply again as long as `can_apply_again` is not set to false.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteCustomerResponse delete(@Nonnull String uid, @Nonnull DeleteCustomerRequestBody body) {
        DeleteCustomerRequest request = new DeleteCustomerRequest(uid, body);
        RequestOperation<DeleteCustomerRequest, DeleteCustomerResponse> operation
              = new DeleteCustomer.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
