/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.models.operations.GetPoolRequest;
import com.newline53.sdk.models.operations.GetPoolRequestBuilder;
import com.newline53.sdk.models.operations.GetPoolResponse;
import com.newline53.sdk.models.operations.ListPoolsRequest;
import com.newline53.sdk.models.operations.ListPoolsRequestBuilder;
import com.newline53.sdk.models.operations.ListPoolsResponse;
import com.newline53.sdk.operations.GetPool;
import com.newline53.sdk.operations.ListPools;
import com.newline53.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.String;

/**
 * Pools group multiple Customers for asset sharing and distributed account ownership. Each Pool is
 * unique to a Customer or program.
 * 
 * <p>**Endpoints:**
 * 
 * <p>- GET [List Pools: GET /pools](https://developers.newline53.com/reference/get_pools)
 * 
 * <p>- GET [Get a single Pool: GET
 * /pools/{uid}](https://developers.newline53.com/reference/get_pools-uid)
 * 
 * <p>A pool is a construct that Newline uses to associate multiple customers with each other. A Pool is
 * always associated with at least one Customer, but all accounts are only ever associated with a
 * single Pool. This enables asset sharing and distributed ownership of accounts across multiple
 * Customers.
 * 
 * <p>Newline currently supports single Customer Pools, where **one Customer is associated with one Pool
 * and vice versa**. All accounts, transfers, and transactions are related to the Customer's Pool, not
 * the Customer. The Pool UID appears on several endpoint responses and may be required by the API in
 * some instances.
 */
public class Pools {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncPools asyncSDK;

    Pools(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncPools(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncPools toAsync() {
        return asyncSDK;
    }

    /**
     * List Pools
     * 
     * <p>Retrieves a list of Pools filtered by the given parameters.
     * 
     * @return The call builder
     */
    public ListPoolsRequestBuilder list() {
        return new ListPoolsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Pools
     * 
     * <p>Retrieves a list of Pools filtered by the given parameters.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListPoolsResponse listDirect() {
        return list(null, null, null);
    }

    /**
     * List Pools
     * 
     * <p>Retrieves a list of Pools filtered by the given parameters.
     * 
     * @param customerUid Filter by Customer. Multiple values are allowed, e.g. `customer_uid[]=uKxmLxUEiSj5h4M3&customer_uid[]=y9reyPMNEWuuYSC1`.
     *         
     * @param limit Maximum number of items to retrieve. This filter is automatically applied with the default value if not given.
     *         
     * @param offset Index of the items to start retrieving from
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListPoolsResponse list(
            @Nullable String customerUid, @Nullable Long limit,
            @Nullable Long offset) {
        ListPoolsRequest request = new ListPoolsRequest(customerUid, limit, offset);
        RequestOperation<ListPoolsRequest, ListPoolsResponse> operation
              = new ListPools.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a single Pool
     * 
     * <p>Retrieve overall status about a Pool as well as its total Asset Balances across all associated
     * accounts.
     * 
     * @return The call builder
     */
    public GetPoolRequestBuilder get() {
        return new GetPoolRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Pool
     * 
     * <p>Retrieve overall status about a Pool as well as its total Asset Balances across all associated
     * accounts.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetPoolResponse get(@Nonnull String uid) {
        GetPoolRequest request = new GetPoolRequest(uid);
        RequestOperation<GetPoolRequest, GetPoolResponse> operation
              = new GetPool.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
