/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.models.operations.GetCustodialLineItemsRequest;
import com.newline53.sdk.models.operations.GetCustodialLineItemsRequestBuilder;
import com.newline53.sdk.models.operations.GetCustodialLineItemsResponse;
import com.newline53.sdk.models.operations.GetCustodialLineItemsUidRequest;
import com.newline53.sdk.models.operations.GetCustodialLineItemsUidRequestBuilder;
import com.newline53.sdk.models.operations.GetCustodialLineItemsUidResponse;
import com.newline53.sdk.models.operations.GetSyntheticLineItemsRequest;
import com.newline53.sdk.models.operations.GetSyntheticLineItemsRequestBuilder;
import com.newline53.sdk.models.operations.GetSyntheticLineItemsResponse;
import com.newline53.sdk.models.operations.GetSyntheticLineItemsUidRequest;
import com.newline53.sdk.models.operations.GetSyntheticLineItemsUidRequestBuilder;
import com.newline53.sdk.models.operations.GetSyntheticLineItemsUidResponse;
import com.newline53.sdk.models.operations.GetTransactionEventsRequest;
import com.newline53.sdk.models.operations.GetTransactionEventsRequestBuilder;
import com.newline53.sdk.models.operations.GetTransactionEventsResponse;
import com.newline53.sdk.models.operations.GetTransactionEventsUidRequest;
import com.newline53.sdk.models.operations.GetTransactionEventsUidRequestBuilder;
import com.newline53.sdk.models.operations.GetTransactionEventsUidResponse;
import com.newline53.sdk.models.operations.GetTransactionsRequest;
import com.newline53.sdk.models.operations.GetTransactionsRequestBuilder;
import com.newline53.sdk.models.operations.GetTransactionsResponse;
import com.newline53.sdk.models.operations.GetTransactionsUidRequest;
import com.newline53.sdk.models.operations.GetTransactionsUidRequestBuilder;
import com.newline53.sdk.models.operations.GetTransactionsUidResponse;
import com.newline53.sdk.models.operations.PutTransactionsUidAuthorizeRequest;
import com.newline53.sdk.models.operations.PutTransactionsUidAuthorizeRequestBody;
import com.newline53.sdk.models.operations.PutTransactionsUidAuthorizeRequestBuilder;
import com.newline53.sdk.models.operations.PutTransactionsUidAuthorizeResponse;
import com.newline53.sdk.operations.GetCustodialLineItems;
import com.newline53.sdk.operations.GetCustodialLineItemsUid;
import com.newline53.sdk.operations.GetSyntheticLineItems;
import com.newline53.sdk.operations.GetSyntheticLineItemsUid;
import com.newline53.sdk.operations.GetTransactionEvents;
import com.newline53.sdk.operations.GetTransactionEventsUid;
import com.newline53.sdk.operations.GetTransactions;
import com.newline53.sdk.operations.GetTransactionsUid;
import com.newline53.sdk.operations.PutTransactionsUidAuthorize;
import com.newline53.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import java.lang.String;

/**
 * Transactions represent asset movements, such as ACH payments, wire transfers, or card purchases.
 * Track transaction statuses and events through these endpoints.
 * **Endpoints:**
 * 
 * <p>- GET [List Transactions: GET
 * /transactions](https://developers.newline53.com/reference/get_transactions)
 * 
 * <p>- GET [Get a single Transaction: GET
 * /transactions/{uid}](https://developers.newline53.com/reference/get_transactions-uid)
 * 
 * <p>- PUT [Approve or deny a Transaction: PUT
 * /transactions/{uid}/authorize](https://developers.newline53.com/reference/put_transactions-uid-authorize)
 * 
 * <p>- GET [List Transaction Events: GET
 * /transaction_events](https://developers.newline53.com/reference/get_transaction-events)
 * 
 * <p>- GET [Get a single Transaction Event: GET
 * /transaction_events/{uid}](https://developers.newline53.com/reference/get_transaction-events-uid)
 * 
 * <p>- GET [List Synthetic Line Items: GET
 * /synthetic_line_items](https://developers.newline53.com/reference/get_synthetic-line-items)
 * 
 * <p>- GET [Get a single Synthetic Line Item: GET
 * /synthetic_line_items/{uid}](https://developers.newline53.com/reference/get_synthetic-line-items-uid)
 * 
 * <p>- GET [List Custodial Line Items: GET
 * /custodial_line_items](https://developers.newline53.com/reference/get_custodial-line-items)
 * 
 * <p>- GET [Get a single Custodial Line Item: GET
 * /custodial_line_items/{uid}](https://developers.newline53.com/reference/get_custodial-line-items-uid)
 * 
 * <p>Transactions are created based on how you instruct Newline to move assets (a Transfer) or how assets
 * are moved or spent outside your application (ATM withdrawals, debit card purchases, wire transfers,
 * etc…). The Transaction contains the amount, origin, and destination of assets. Newline categorizes
 * Transactions into types to assist in their classification and representation.
 * 
 * <p>Transactions fall into many categories, including debit card purchases, direct deposits, interest,
 * and fees. This endpoint can retrieve a list of Transactions or track the status of an ongoing
 * Transaction.
 * 
 * <p>Transaction Events are created as a result of a Transaction. They capture the steps required to
 * complete the Transaction. These can be used to view the progress of an in-flight Transaction or see
 * the history of a completed Transaction.
 * 
 * <p>Line Items are created for each Transaction Event. They catalog the individual credits and debits
 * associated with the accounts involved in the Transaction.
 */
public class Transactions {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTransactions asyncSDK;

    Transactions(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncTransactions(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTransactions toAsync() {
        return asyncSDK;
    }

    /**
     * List Transactions
     * 
     * <p>Retrieves a list of Transactions. Transactions representing expired authorizations or expired
     * reversals are suppressed by default.
     * 
     * @return The call builder
     */
    public GetTransactionsRequestBuilder list() {
        return new GetTransactionsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Transactions
     * 
     * <p>Retrieves a list of Transactions. Transactions representing expired authorizations or expired
     * reversals are suppressed by default.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTransactionsResponse list(@Nonnull GetTransactionsRequest request) {
        RequestOperation<GetTransactionsRequest, GetTransactionsResponse> operation
              = new GetTransactions.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a single Transaction
     * 
     * <p>Retrieves a single Transaction resource along with its details, including amount, origin,
     * destination, and status.
     * 
     * @return The call builder
     */
    public GetTransactionsUidRequestBuilder get() {
        return new GetTransactionsUidRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Transaction
     * 
     * <p>Retrieves a single Transaction resource along with its details, including amount, origin,
     * destination, and status.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTransactionsUidResponse get(@Nonnull String uid) {
        GetTransactionsUidRequest request = new GetTransactionsUidRequest(uid);
        RequestOperation<GetTransactionsUidRequest, GetTransactionsUidResponse> operation
              = new GetTransactionsUid.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Approve or deny a transaction
     * 
     * <p>Approves or denies a pending Transaction. This endpoint is used to explicitly authorize or reject a
     * Transaction before it is executed.
     * 
     * @return The call builder
     */
    public PutTransactionsUidAuthorizeRequestBuilder authorize() {
        return new PutTransactionsUidAuthorizeRequestBuilder(sdkConfiguration);
    }

    /**
     * Approve or deny a transaction
     * 
     * <p>Approves or denies a pending Transaction. This endpoint is used to explicitly authorize or reject a
     * Transaction before it is executed.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PutTransactionsUidAuthorizeResponse authorize(@Nonnull String uid, @Nonnull PutTransactionsUidAuthorizeRequestBody body) {
        PutTransactionsUidAuthorizeRequest request = new PutTransactionsUidAuthorizeRequest(uid, body);
        RequestOperation<PutTransactionsUidAuthorizeRequest, PutTransactionsUidAuthorizeResponse> operation
              = new PutTransactionsUidAuthorize.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Transaction Events
     * 
     * <p>Retrieves a list of Transaction Events. Transaction Events represent the steps required to complete
     * a Transaction and can be used to track its progress or review its history.
     * 
     * @return The call builder
     */
    public GetTransactionEventsRequestBuilder listEvents() {
        return new GetTransactionEventsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Transaction Events
     * 
     * <p>Retrieves a list of Transaction Events. Transaction Events represent the steps required to complete
     * a Transaction and can be used to track its progress or review its history.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTransactionEventsResponse listEvents(@Nonnull GetTransactionEventsRequest request) {
        RequestOperation<GetTransactionEventsRequest, GetTransactionEventsResponse> operation
              = new GetTransactionEvents.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a single Transaction Event
     * 
     * <p>Retrieves a single Transaction Event resource, including its status, timestamps, and associated
     * Transaction details.
     * 
     * @return The call builder
     */
    public GetTransactionEventsUidRequestBuilder getTransactionEvent() {
        return new GetTransactionEventsUidRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Transaction Event
     * 
     * <p>Retrieves a single Transaction Event resource, including its status, timestamps, and associated
     * Transaction details.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTransactionEventsUidResponse getTransactionEvent(@Nonnull String uid) {
        GetTransactionEventsUidRequest request = new GetTransactionEventsUidRequest(uid);
        RequestOperation<GetTransactionEventsUidRequest, GetTransactionEventsUidResponse> operation
              = new GetTransactionEventsUid.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Synthetic Line Items
     * 
     * <p>Retrieves a list of Synthetic Line Items. These represent individual debits and credits associated
     * with Synthetic Accounts as part of a Transaction Event.
     * 
     * @return The call builder
     */
    public GetSyntheticLineItemsRequestBuilder listSyntheticLineItems() {
        return new GetSyntheticLineItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Synthetic Line Items
     * 
     * <p>Retrieves a list of Synthetic Line Items. These represent individual debits and credits associated
     * with Synthetic Accounts as part of a Transaction Event.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetSyntheticLineItemsResponse listSyntheticLineItems(@Nonnull GetSyntheticLineItemsRequest request) {
        RequestOperation<GetSyntheticLineItemsRequest, GetSyntheticLineItemsResponse> operation
              = new GetSyntheticLineItems.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a single Synthetic Line Item
     * 
     * <p>Retrieves a single Synthetic Line Item resource, including the amount, account, and associated
     * Transaction Event.
     * 
     * @return The call builder
     */
    public GetSyntheticLineItemsUidRequestBuilder getSyntheticLineItem() {
        return new GetSyntheticLineItemsUidRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Synthetic Line Item
     * 
     * <p>Retrieves a single Synthetic Line Item resource, including the amount, account, and associated
     * Transaction Event.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetSyntheticLineItemsUidResponse getSyntheticLineItem(@Nonnull String uid) {
        GetSyntheticLineItemsUidRequest request = new GetSyntheticLineItemsUidRequest(uid);
        RequestOperation<GetSyntheticLineItemsUidRequest, GetSyntheticLineItemsUidResponse> operation
              = new GetSyntheticLineItemsUid.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Custodial Line Items
     * 
     * <p>Retrieves a list of Custodial Line Items. These represent individual debits and credits associated
     * with Custodial Accounts as part of a Transaction Event.
     * 
     * @return The call builder
     */
    public GetCustodialLineItemsRequestBuilder listCustodialLineItems() {
        return new GetCustodialLineItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * List Custodial Line Items
     * 
     * <p>Retrieves a list of Custodial Line Items. These represent individual debits and credits associated
     * with Custodial Accounts as part of a Transaction Event.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetCustodialLineItemsResponse listCustodialLineItems(@Nonnull GetCustodialLineItemsRequest request) {
        RequestOperation<GetCustodialLineItemsRequest, GetCustodialLineItemsResponse> operation
              = new GetCustodialLineItems.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a single Custodial Line Item
     * 
     * <p>Retrieves a single Custodial Line Item resource, including the amount, account, and associated
     * Transaction Event.
     * 
     * @return The call builder
     */
    public GetCustodialLineItemsUidRequestBuilder getCustodialLineItem() {
        return new GetCustodialLineItemsUidRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Custodial Line Item
     * 
     * <p>Retrieves a single Custodial Line Item resource, including the amount, account, and associated
     * Transaction Event.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetCustodialLineItemsUidResponse getCustodialLineItem(@Nonnull String uid) {
        GetCustodialLineItemsUidRequest request = new GetCustodialLineItemsUidRequest(uid);
        RequestOperation<GetCustodialLineItemsUidRequest, GetCustodialLineItemsUidResponse> operation
              = new GetCustodialLineItemsUid.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
