/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk;

import static com.newline53.sdk.operations.Operations.RequestOperation;

import com.newline53.sdk.models.operations.CreateTransferRequest;
import com.newline53.sdk.models.operations.CreateTransferRequestBuilder;
import com.newline53.sdk.models.operations.CreateTransferResponse;
import com.newline53.sdk.models.operations.GetTransferRequest;
import com.newline53.sdk.models.operations.GetTransferRequestBuilder;
import com.newline53.sdk.models.operations.GetTransferResponse;
import com.newline53.sdk.models.operations.ListTransfersRequest;
import com.newline53.sdk.models.operations.ListTransfersRequestBuilder;
import com.newline53.sdk.models.operations.ListTransfersResponse;
import com.newline53.sdk.models.operations.PutTransfersUidCancelRequest;
import com.newline53.sdk.models.operations.PutTransfersUidCancelRequestBody;
import com.newline53.sdk.models.operations.PutTransfersUidCancelRequestBuilder;
import com.newline53.sdk.models.operations.PutTransfersUidCancelResponse;
import com.newline53.sdk.operations.CreateTransfer;
import com.newline53.sdk.operations.GetTransfer;
import com.newline53.sdk.operations.ListTransfers;
import com.newline53.sdk.operations.PutTransfersUidCancel;
import com.newline53.sdk.utils.Headers;
import jakarta.annotation.Nonnull;
import java.lang.String;

/**
 * Transfers facilitate the movement of assets between accounts, enabling transactions such as payments
 * and withdrawals.
 * 
 * <p>**Endpoints:**
 * 
 * <p>- GET [List Transfers: GET /transfers](https://developers.newline53.com/reference/get_transfers)
 * 
 * <p>- POST [Initiate a Transfer: POST
 * /transfers](https://developers.newline53.com/reference/post_transfers)
 * 
 * <p>- GET [Get a single Transfer: GET
 * /transfers/{uid}](https://developers.newline53.com/reference/get_transfers-uid)
 * 
 * <p>- PUT [Cancel a Transfer: PUT
 * /transfers/{uid}/cancel](https://developers.newline53.com/reference/put_transfers-uid-cancel)
 * 
 * <p>A Transfer is the Action of moving assets between two Synthetic Accounts. Most asset movement
 * initiated by your application will result in a Transfer. Asset movement is determined by the makeup
 * of assets in both participating accounts, the Synthetic Account Type of the participating accounts,
 * the available Custodial Accounts for all participating Customers, and the overall Program
 * configuration.
 * 
 * <p>A Transfer can never be initiated between two external accounts.
 * 
 * <p>### Company ID Behavior
 * 
 * <p>The company_id field is optional when initiating a transfer. However, it becomes required if your
 * organization has multiple company IDs or multiple custodial accounts, to ensure accurate routing of
 * funds. If provided, the value will be validated.
 * 
 * <p>In sandbox environments:
 * 
 * <p>- `company_id` is optional and will be validated if supplied.
 * - `company_id` and custodial accounts are always in a 1:1 relationship.
 * 
 * <p>&gt; **Note**
 * &gt; Any time a Transfer is created, it creates 1+ Transactions, which are returned in the response
 * payload for a successful Transfer. Please note or record these uids, as they will be needed to query
 * the Transaction object and any associated key data points. For instance, Fed IMAD or CHIPS SSN is
 * used for outgoing wires.
 */
public class Transfers {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTransfers asyncSDK;

    Transfers(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncTransfers(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTransfers toAsync() {
        return asyncSDK;
    }

    /**
     * List Transfers
     * 
     * <p>Retrieves a list of Transfers filtered by the given parameters. Transfers facilitate the movement of
     * assets between accounts, enabling transactions such as payments and withdrawals.
     * 
     * @return The call builder
     */
    public ListTransfersRequestBuilder list() {
        return new ListTransfersRequestBuilder(sdkConfiguration);
    }

    /**
     * List Transfers
     * 
     * <p>Retrieves a list of Transfers filtered by the given parameters. Transfers facilitate the movement of
     * assets between accounts, enabling transactions such as payments and withdrawals.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListTransfersResponse list(@Nonnull ListTransfersRequest request) {
        RequestOperation<ListTransfersRequest, ListTransfersResponse> operation
              = new ListTransfers.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Initiate a Transfer
     * 
     * <p>Attempt to initiate a Transfer between two Synthetic Accounts. Before the Transfer will be
     * initiated, several checks will be performed to ensure there is sufficient balance in the source
     * account and that the initiating Customer has all the necessary access to both Synthetic Accounts.
     * 
     * <p>The Synthetic Accounts allowed in a Transfer request are listed below
     * 
     * <p>- between a liability Synthetic Account in the `general` category and a Synthetic Account in the
     * `ach_external`, `wire_external`, or `instant_payments_external` category
     * - between two liability Synthetic Accounts in the `general` category that are also owned by the same
     * Customer.
     * 
     * <p>&gt; **Note**
     * &gt; Please note that if utilizing the Transmitter information, the initiator type should be set to
     * transmitter. If not set, the field defaults to customer and any data provided in that field will be
     * ignored.
     * 
     * @return The call builder
     */
    public CreateTransferRequestBuilder create() {
        return new CreateTransferRequestBuilder(sdkConfiguration);
    }

    /**
     * Initiate a Transfer
     * 
     * <p>Attempt to initiate a Transfer between two Synthetic Accounts. Before the Transfer will be
     * initiated, several checks will be performed to ensure there is sufficient balance in the source
     * account and that the initiating Customer has all the necessary access to both Synthetic Accounts.
     * 
     * <p>The Synthetic Accounts allowed in a Transfer request are listed below
     * 
     * <p>- between a liability Synthetic Account in the `general` category and a Synthetic Account in the
     * `ach_external`, `wire_external`, or `instant_payments_external` category
     * - between two liability Synthetic Accounts in the `general` category that are also owned by the same
     * Customer.
     * 
     * <p>&gt; **Note**
     * &gt; Please note that if utilizing the Transmitter information, the initiator type should be set to
     * transmitter. If not set, the field defaults to customer and any data provided in that field will be
     * ignored.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateTransferResponse create(@Nonnull CreateTransferRequest request) {
        RequestOperation<CreateTransferRequest, CreateTransferResponse> operation
              = new CreateTransfer.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a single Transfer
     * 
     * <p>Retrieves a single Transfer resource along with its details, including status, participating
     * accounts, and associated Transactions.
     * 
     * <p>Filter parameters are not case sensitive but will only return exact matches.
     * 
     * @return The call builder
     */
    public GetTransferRequestBuilder get() {
        return new GetTransferRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a single Transfer
     * 
     * <p>Retrieves a single Transfer resource along with its details, including status, participating
     * accounts, and associated Transactions.
     * 
     * <p>Filter parameters are not case sensitive but will only return exact matches.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTransferResponse get(@Nonnull String uid) {
        GetTransferRequest request = new GetTransferRequest(uid);
        RequestOperation<GetTransferRequest, GetTransferResponse> operation
              = new GetTransfer.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Cancel a Transfer
     * 
     * <p>Transfers must be canceled by the originating Customer (or Authorized Representative).
     * 
     * <p>Transfers can only enter the canceled state if Newline receives a request while the Transfer is in
     * `queued` or `pending states`.
     * 
     * <p>A cancellation request during the `pending` state is not guaranteed, as this state may include
     * payment execution. At that stage, a cancel request will result in an error.
     * 
     * @return The call builder
     */
    public PutTransfersUidCancelRequestBuilder cancel() {
        return new PutTransfersUidCancelRequestBuilder(sdkConfiguration);
    }

    /**
     * Cancel a Transfer
     * 
     * <p>Transfers must be canceled by the originating Customer (or Authorized Representative).
     * 
     * <p>Transfers can only enter the canceled state if Newline receives a request while the Transfer is in
     * `queued` or `pending states`.
     * 
     * <p>A cancellation request during the `pending` state is not guaranteed, as this state may include
     * payment execution. At that stage, a cancel request will result in an error.
     * 
     * @param uid Newline-generated unique id resource specific to the current endpoint
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public PutTransfersUidCancelResponse cancel(@Nonnull String uid, @Nonnull PutTransfersUidCancelRequestBody body) {
        PutTransfersUidCancelRequest request = new PutTransfersUidCancelRequest(uid, body);
        RequestOperation<PutTransfersUidCancelRequest, PutTransfersUidCancelResponse> operation
              = new PutTransfersUidCancel.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
