/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.utils;

public final class Constants {

    public static final boolean HAS_CLIENT_CREDENTIALS_BASIC = false;

}