/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.newline53.sdk.models.operations.async;

import static com.newline53.sdk.operations.Operations.AsyncRequestOperation;

import com.newline53.sdk.SDKConfiguration;
import com.newline53.sdk.models.operations.GetCustomerRequest;
import com.newline53.sdk.operations.GetCustomer;
import com.newline53.sdk.utils.Headers;
import com.newline53.sdk.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class GetCustomerRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetCustomerRequest.Builder pojoBuilder;
    private GetCustomerRequest request;
    private boolean _setterCalled;

    public GetCustomerRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetCustomerRequest.builder();
    }

    public GetCustomerRequestBuilder uid(@Nonnull String uid) {
        this.pojoBuilder.uid(uid);
        this._setterCalled = true;
        return this;
    }

    private GetCustomerRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public GetCustomerRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<GetCustomerResponse> call() {
        AsyncRequestOperation<GetCustomerRequest, GetCustomerResponse> operation
              = new GetCustomer.Async(sdkConfiguration, _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
